package com.jiuyv.hhc.model.common.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.common.ResMediaVo;

// Generated by AutoCode4J
/**
 * Interface: 媒体附件表 : TBL_RES_MEDIA
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface ResMediaDao extends BaseDao<ResMediaVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.common.dao.ResMediaDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.common.dao.ResMediaDao.filterQuery";

	/**
	 * Find ResMediaVo by Primary Key. 
	 * 
	 * @param medId : 文件ID	 
	 * @return ResMediaVo : 媒体附件表
	 */
	ResMediaVo findByKey(Long medId ) ;
	
	/**
	 * Find thumb by path.
	 * 获取缩略图
	 * 
	 * @param medPath the med path
	 * @return the res media vo
	 */
	ResMediaVo findThumbByPath(String medPath);

	/**
	 * Find content by path.
	 * 获取完整图片
	 * 
	 * @param medPath the med path
	 * @return the res media vo
	 */
	ResMediaVo findContentByPath(String medPath);
}
