package com.jiuyv.hhc.model.message ;

// Generated by AutoCode4J
/**
 * EntityBean: 邮件内容表 : TBL_MSG_MAIL
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MsgMailVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** mailId : 邮件ID. MAIL_ID: int */
	private Long mailId ;
	
	/** version : VERSION. VERSION: int */
	private Long version ;
	
	/** status : 状态. STATUS: varchar(1) */
	private String status ;
	
	/** procInfo : 发送处理信息. PROC_INFO: varchar(1000) */
	private String procInfo ;
	
	/** toAddrs : 邮件地址. TO_ADDRS: varchar(500) */
	private String toAddrs ;
	
	/** ccAddrs : 抄送地址. CC_ADDRS: varchar(500) */
	private String ccAddrs ;
	
	/** subject : 邮件主题. SUBJECT: varchar(255) */
	private String subject ;
	
	/** content : 邮件内容. CONTENT: text */
	private String content ;
	
	/** sendTime : 邮件发送时间. SEND_TIME: char(14) */
	private String sendTime ;
	
	/** recCrtDttm : 记录创建时间. REC_CRT_DTTM: char(14) */
	private String recCrtTime ;
	
	/** recCrtUserId : 记录创建用户帐号. REC_CRT_USER_ID: varchar(10) */
	private String recCrtAcc ;
	
	/** lstUpdDttm : 最后修改时间. LST_UPD_DTTM: char(14) */
	private String lastUptTime ;
	
	/** lstUpdUserId : 最后修改用户帐号. LST_UPD_USER_ID: varchar(10) */
	private String lastUptAcc ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public MsgMailVo() {
		// Default Construtor
	}
	
	public MsgMailVo(Long mailId) {
		this.mailId = mailId;
	}
		
	// -- Setter And Getter
	/**
	 * Set mailId : 邮件ID. MAIL_ID: int 
	 */
	public void setMailId(Long mailId){
		this.mailId = mailId;	
	}
	
	/**
	 * Get mailId : 邮件ID. MAIL_ID: int 
	 */
	public Long getMailId(){
		return this.mailId;	
	}
	
	/**
	 * Set version : VERSION. VERSION: int 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: int 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set status : 状态. STATUS: varchar(1) 
	 */
	public void setStatus(String status){
		this.status = status;	
	}
	
	/**
	 * Get status : 状态. STATUS: varchar(1) 
	 */
	public String getStatus(){
		return this.status;	
	}
	
	/**
	 * Set procInfo : 发送处理信息. PROC_INFO: varchar(1000) 
	 */
	public void setProcInfo(String procInfo){
		this.procInfo = procInfo;	
	}
	
	/**
	 * Get procInfo : 发送处理信息. PROC_INFO: varchar(1000) 
	 */
	public String getProcInfo(){
		return this.procInfo;	
	}
	
	/**
	 * Set toAddrs : 邮件地址. TO_ADDRS: varchar(500) 
	 */
	public void setToAddrs(String toAddrs){
		this.toAddrs = toAddrs;	
	}
	
	/**
	 * Get toAddrs : 邮件地址. TO_ADDRS: varchar(500) 
	 */
	public String getToAddrs(){
		return this.toAddrs;	
	}
	
	/**
	 * Set ccAddrs : 抄送地址. CC_ADDRS: varchar(500) 
	 */
	public void setCcAddrs(String ccAddrs){
		this.ccAddrs = ccAddrs;	
	}
	
	/**
	 * Get ccAddrs : 抄送地址. CC_ADDRS: varchar(500) 
	 */
	public String getCcAddrs(){
		return this.ccAddrs;	
	}
	
	/**
	 * Set subject : 邮件主题. SUBJECT: varchar(255) 
	 */
	public void setSubject(String subject){
		this.subject = subject;	
	}
	
	/**
	 * Get subject : 邮件主题. SUBJECT: varchar(255) 
	 */
	public String getSubject(){
		return this.subject;	
	}
	
	/**
	 * Set content : 邮件内容. CONTENT: text 
	 */
	public void setContent(String content){
		this.content = content;	
	}
	
	/**
	 * Get content : 邮件内容. CONTENT: text 
	 */
	public String getContent(){
		return this.content;	
	}
	
	/**
	 * Set sendTime : 邮件发送时间. SEND_TIME: char(14) 
	 */
	public void setSendTime(String sendTime){
		this.sendTime = sendTime;	
	}
	
	/**
	 * Get sendTime : 邮件发送时间. SEND_TIME: char(14) 
	 */
	public String getSendTime(){
		return this.sendTime;	
	}

	public String getRecCrtTime() {
		return recCrtTime;
	}

	public void setRecCrtTime(String recCrtTime) {
		this.recCrtTime = recCrtTime;
	}

	public String getRecCrtAcc() {
		return recCrtAcc;
	}

	public void setRecCrtAcc(String recCrtAcc) {
		this.recCrtAcc = recCrtAcc;
	}

	public String getLastUptTime() {
		return lastUptTime;
	}

	public void setLastUptTime(String lastUptTime) {
		this.lastUptTime = lastUptTime;
	}

	public String getLastUptAcc() {
		return lastUptAcc;
	}

	public void setLastUptAcc(String lastUptAcc) {
		this.lastUptAcc = lastUptAcc;
	}
	

	
}