package com.jiuyv.hhc.model.message ;

// Generated by AutoCode4J
/**
 * EntityBean: 系统消息表 : TBL_MSG_MESSAGE
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MsgMessageVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** msgId : 消息ID. MSG_ID: int */
	private Long msgId;

	/** version : VERSION. VERSION: int */
	private Long version;

	/** msgTitle : 标题. MSG_TITLE: varchar(255) */
	private String msgTitle;

	/** msgContent : 内容. MSG_CONTENT: text */
	private String msgContent;

	/** sendTime : 发送时间. SEND_TIME: char(14) */
	private String sendTime;

	/** sendAcct : 作者. SEND_ACCT: varchar(10) */
	private String sendAcct;

	/** status : 状态. STATUS: varchar(1) */
	private String status;

	/** expireTime : 过期时间. EXPIRE_TIME: char(14) */
	private String expireTime;

	/** showFlag : 显示标识. SHOW_FLAG: varchar(1) */
	private String showFlag;

	/** lastUptTime : 更新时间. LAST_UPT_TIME: char(14) */
	private String lastUptTime;

	// -- Extend --
	/** recvId : 收件人ID. RECV_ID: int */
	private Long recvId;

	/** sendId : 发件人ID. SEND_ID: int */
	private Long sendId;

	/** readFlag : 信件状态. READ_FLAG: varchar(1) */
	private String readFlag;

	/** status : 状态. STATUS: varchar(1) */
	private String statusDesc;
	/** showFlag : 显示标识. SHOW_FLAG: varchar(1) */
	private String showFlagDesc;
	/** readFlag : 信件状态. READ_FLAG: varchar(1) */
	private String readFlagDesc;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public MsgMessageVo() {
		// Default Construtor
	}
	
	public MsgMessageVo(Long msgId) {
		this.msgId = msgId;
	}
		
	// -- Setter And Getter
	/**
	 * Set msgId : 消息ID. MSG_ID: int 
	 */
	public void setMsgId(Long msgId){
		this.msgId = msgId;	
	}
	
	/**
	 * Get msgId : 消息ID. MSG_ID: int 
	 */
	public Long getMsgId(){
		return this.msgId;	
	}
	
	/**
	 * Set version : VERSION. VERSION: int 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: int 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set msgTitle : 标题. MSG_TITLE: varchar(255) 
	 */
	public void setMsgTitle(String msgTitle){
		this.msgTitle = msgTitle;	
	}
	
	/**
	 * Get msgTitle : 标题. MSG_TITLE: varchar(255) 
	 */
	public String getMsgTitle(){
		return this.msgTitle;	
	}
	
	/**
	 * Set msgContent : 内容. MSG_CONTENT: text 
	 */
	public void setMsgContent(String msgContent){
		this.msgContent = msgContent;	
	}
	
	/**
	 * Get msgContent : 内容. MSG_CONTENT: text 
	 */
	public String getMsgContent(){
		return this.msgContent;	
	}
	
	/**
	 * Set sendTime : 发送时间. SEND_TIME: char(14) 
	 */
	public void setSendTime(String sendTime){
		this.sendTime = sendTime;	
	}
	
	/**
	 * Get sendTime : 发送时间. SEND_TIME: char(14) 
	 */
	public String getSendTime(){
		return this.sendTime;	
	}
	
	/**
	 * Set sendAcct : 作者. SEND_ACCT: varchar(10) 
	 */
	public void setSendAcct(String sendAcct){
		this.sendAcct = sendAcct;	
	}
	
	/**
	 * Get sendAcct : 作者. SEND_ACCT: varchar(10) 
	 */
	public String getSendAcct(){
		return this.sendAcct;	
	}
	
	/**
	 * Set status : 状态. STATUS: varchar(1) 
	 */
	public void setStatus(String status){
		this.status = status;	
	}
	
	/**
	 * Get status : 状态. STATUS: varchar(1) 
	 */
	public String getStatus(){
		return this.status;	
	}
	
	/**
	 * Set expireTime : 过期时间. EXPIRE_TIME: char(14) 
	 */
	public void setExpireTime(String expireTime){
		this.expireTime = expireTime;	
	}
	
	/**
	 * Get expireTime : 过期时间. EXPIRE_TIME: char(14) 
	 */
	public String getExpireTime(){
		return this.expireTime;	
	}
	
	/**
	 * Set showFlag : 显示标识. SHOW_FLAG: varchar(1) 
	 */
	public void setShowFlag(String showFlag){
		this.showFlag = showFlag;	
	}
	
	/**
	 * Get showFlag : 显示标识. SHOW_FLAG: varchar(1) 
	 */
	public String getShowFlag(){
		return this.showFlag;	
	}
	

	public String getLastUptTime() {
		return lastUptTime;
	}

	public void setLastUptTime(String lastUptTime) {
		this.lastUptTime = lastUptTime;
	}

	public Long getRecvId() {
		return recvId;
	}

	public void setRecvId(Long recvId) {
		this.recvId = recvId;
	}

	public Long getSendId() {
		return sendId;
	}

	public void setSendId(Long sendId) {
		this.sendId = sendId;
	}

	public String getReadFlag() {
		return readFlag;
	}

	public void setReadFlag(String readFlag) {
		this.readFlag = readFlag;
	}

	public String getStatusDesc() {
		return statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	public String getShowFlagDesc() {
		return showFlagDesc;
	}

	public void setShowFlagDesc(String showFlagDesc) {
		this.showFlagDesc = showFlagDesc;
	}

	public String getReadFlagDesc() {
		return readFlagDesc;
	}

	public void setReadFlagDesc(String readFlagDesc) {
		this.readFlagDesc = readFlagDesc;
	}
	
}