package com.jiuyv.hhc.model.message ;

// Generated by AutoCode4J
/**
 * EntityBean: 信息模板表 : TBL_MSG_TPL
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MsgTplVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** tplId : 模版ID. TPL_ID: int */
	private Long tplId ;
	
	/** version : VERSION. VERSION: int */
	private Long version ;
	
	/** tplName : 模版名称. TPL_NAME: varchar(255) */
	private String tplName ;
	
	/** tplContent : 模版内容. TPL_CONTENT: text */
	private String tplContent ;
	
	/** tplRemark : 备注. TPL_REMARK: varchar(255) */
	private String tplRemark ;
	
	/** recCrtDttm : 记录创建时间. REC_CRT_DTTM: char(14) */
	private String recCrtTime ;
	
	/** recCrtUserId : 记录创建用户帐号. REC_CRT_USER_ID: varchar(10) */
	private String recCrtAcc ;
	
	/** lstUpdDttm : 最后修改时间. LST_UPD_DTTM: char(14) */
	private String lastUptTime ;
	
	/** lstUpdUserId : 最后修改用户帐号. LST_UPD_USER_ID: varchar(10) */
	private String lastUptAcc ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public MsgTplVo() {
		// Default Construtor
	}
	
	public MsgTplVo(Long tplId) {
		this.tplId = tplId;
	}
		
	// -- Setter And Getter
	/**
	 * Set tplId : 模版ID. TPL_ID: int 
	 */
	public void setTplId(Long tplId){
		this.tplId = tplId;	
	}
	
	/**
	 * Get tplId : 模版ID. TPL_ID: int 
	 */
	public Long getTplId(){
		return this.tplId;	
	}
	
	/**
	 * Set version : VERSION. VERSION: int 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: int 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set tplName : 模版名称. TPL_NAME: varchar(255) 
	 */
	public void setTplName(String tplName){
		this.tplName = tplName;	
	}
	
	/**
	 * Get tplName : 模版名称. TPL_NAME: varchar(255) 
	 */
	public String getTplName(){
		return this.tplName;	
	}
	
	/**
	 * Set tplContent : 模版内容. TPL_CONTENT: text 
	 */
	public void setTplContent(String tplContent){
		this.tplContent = tplContent;	
	}
	
	/**
	 * Get tplContent : 模版内容. TPL_CONTENT: text 
	 */
	public String getTplContent(){
		return this.tplContent;	
	}
	
	/**
	 * Set tplRemark : 备注. TPL_REMARK: varchar(255) 
	 */
	public void setTplRemark(String tplRemark){
		this.tplRemark = tplRemark;	
	}
	
	/**
	 * Get tplRemark : 备注. TPL_REMARK: varchar(255) 
	 */
	public String getTplRemark(){
		return this.tplRemark;	
	}
	
	public String getRecCrtTime() {
		return recCrtTime;
	}

	public void setRecCrtTime(String recCrtTime) {
		this.recCrtTime = recCrtTime;
	}

	public String getRecCrtAcc() {
		return recCrtAcc;
	}

	public void setRecCrtAcc(String recCrtAcc) {
		this.recCrtAcc = recCrtAcc;
	}

	public String getLastUptTime() {
		return lastUptTime;
	}

	public void setLastUptTime(String lastUptTime) {
		this.lastUptTime = lastUptTime;
	}

	public String getLastUptAcc() {
		return lastUptAcc;
	}

	public void setLastUptAcc(String lastUptAcc) {
		this.lastUptAcc = lastUptAcc;
	}

	
}