package com.jiuyv.hhc.model.message ;

// Generated by AutoCode4J
/**
 * EntityBean: 信息模板参数表 : TBL_MSG_TPL_PARAM
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MsgTplParamVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** paramCode : 参数代码. PARAM_CODE: varchar(255) */
	private String paramCode ;
	
	/** paramName : 参数名. PARAM_NAME: varchar(255) */
	private String paramName ;
	
	/** paramType : 参数类型. PARAM_TYPE: varchar(4) */
	private String paramType ;
	
	/** paramDemo : 范例. PARAM_DEMO: text */
	private String paramDemo ;
	
	/** paramComment : 备注. PARAM_COMMENT: varchar(255) */
	private String paramComment ;
	
	/** status : 状态. STATUS: varchar(1) */
	private String status ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public MsgTplParamVo() {
		// Default Construtor
	}
	
	public MsgTplParamVo(String paramCode) {
		this.paramCode = paramCode;
	}
		
	// -- Setter And Getter
	/**
	 * Set paramCode : 参数代码. PARAM_CODE: varchar(255) 
	 */
	public void setParamCode(String paramCode){
		this.paramCode = paramCode;	
	}
	
	/**
	 * Get paramCode : 参数代码. PARAM_CODE: varchar(255) 
	 */
	public String getParamCode(){
		return this.paramCode;	
	}
	
	/**
	 * Set paramName : 参数名. PARAM_NAME: varchar(255) 
	 */
	public void setParamName(String paramName){
		this.paramName = paramName;	
	}
	
	/**
	 * Get paramName : 参数名. PARAM_NAME: varchar(255) 
	 */
	public String getParamName(){
		return this.paramName;	
	}
	
	/**
	 * Set paramType : 参数类型. PARAM_TYPE: varchar(4) 
	 */
	public void setParamType(String paramType){
		this.paramType = paramType;	
	}
	
	/**
	 * Get paramType : 参数类型. PARAM_TYPE: varchar(4) 
	 */
	public String getParamType(){
		return this.paramType;	
	}
	
	/**
	 * Set paramDemo : 范例. PARAM_DEMO: text 
	 */
	public void setParamDemo(String paramDemo){
		this.paramDemo = paramDemo;	
	}
	
	/**
	 * Get paramDemo : 范例. PARAM_DEMO: text 
	 */
	public String getParamDemo(){
		return this.paramDemo;	
	}
	
	/**
	 * Set paramComment : 备注. PARAM_COMMENT: varchar(255) 
	 */
	public void setParamComment(String paramComment){
		this.paramComment = paramComment;	
	}
	
	/**
	 * Get paramComment : 备注. PARAM_COMMENT: varchar(255) 
	 */
	public String getParamComment(){
		return this.paramComment;	
	}
	
	/**
	 * Set status : 状态. STATUS: varchar(1) 
	 */
	public void setStatus(String status){
		this.status = status;	
	}
	
	/**
	 * Get status : 状态. STATUS: varchar(1) 
	 */
	public String getStatus(){
		return this.status;	
	}
	
}