package com.jiuyv.hhc.model.customer.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.customer.MemberInfoVo;

// Generated by AutoCode4J
/**
 * Interface: 会员基本信息表 : TBL_MEMBER_INFO
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface MemberInfoDao extends BaseDao<MemberInfoVo>{
	
	/** mapped key is : com.jiuyv.hhc.model.customer.dao.MemberInfoDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.customer.dao.MemberInfoDao.filterQuery";

	/**
	 * Find MemberInfoVo by Primary Key. 
	 * 
	 * @param customerCode : 会员代码	 
	 * @return MemberInfoVo : 会员基本信息表
	 */
	MemberInfoVo findByKey(Long customerCode ) ;
	
	/**
	 * Update MemberInfoVo by Primary Key.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int updateByKey(MemberInfoVo vo);
	

	/**
	 * Insert MemberInfoVo.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int insert(MemberInfoVo vo) ;



}