package com.jiuyv.hhc.model.customer.dao ;

import java.util.List;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.customer.MhtBaseInfoVo;

// Generated by AutoCode4J
/**
 * Interface: 商户基本信息表 : TBL_MHT_BASE_INFO
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface MhtBaseInfoDao extends BaseDao<MhtBaseInfoVo>{
	
	/** mapped key is : com.jiuyv.hhc.model.customer.dao.MhtBaseInfoDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.customer.dao.MhtBaseInfoDao.filterQuery";

	/**
	 * Find MhtBaseInfoVo by Primary Key. 
	 * 
	 * @param mchntCode : 内部商户号	 
	 * @return MhtBaseInfoVo : 商户基本信息表
	 */
	MhtBaseInfoVo findByKey(Long mchntCode ) ;
	
	/**
	 * Update MhtBaseInfoVo by Primary Key.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int updateByKey(MhtBaseInfoVo vo);
	

	/**
	 * Insert MhtBaseInfoVo.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int insert(MhtBaseInfoVo vo) ;

	List<MhtBaseInfoVo> filterQuerybyAgentCustomerCode(Long customerCode);

}