package com.jiuyv.hhc.model.customer.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.customer.*;

// Generated by AutoCode4J
/**
 * Interface: 会员基本信息表 : TBL_WEB_MEMBER_INFO
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface WebMemberInfoDao extends BaseDao<WebMemberInfoVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.customer.dao.WebMemberInfoDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.customer.dao.WebMemberInfoDao.filterQuery";

	/**
	 * Find WebMemberInfoVo by Primary Key. 
	 * 
	 * @param customerCode : 会员代码	 
	 * @return WebMemberInfoVo : 会员基本信息表
	 */
	WebMemberInfoVo findByKey(Long customerCode ) ;
	
	
//	List<WebUser> findUserInfo(String userName);
	
	WebMemberInfoVo findByKeyandPwd(WebMemberInfoVo vo ) ;
	
	WebMemberInfoVo findByMobile(String mobile ) ;
	
	WebMemberInfoVo findByMobileandPwd(WebMemberInfoVo vo ) ;
	
	int updateAttempt(String mobile ) ;
	
	int cleanAttempt(String mobile ) ;
}
