package com.jiuyv.hhc.model.customer ;

// Generated by AutoCode4J
/**
 * EntityBean: 会员基本信息表 : TBL_MEMBER_INFO
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
@Deprecated
public class MemberInfoVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** customerCode : 会员代码. CUSTOMER_CODE: VARCHAR2(50) */
	private Long customerCode ;
	
	/** fatherCustomerCode : 代理会员代码. FATHER_CUSTOMER_CODE: VARCHAR2(50) */
	private String fatherCustomerCode ;
	
	/** mobile : 手机号码. MOBILE: VARCHAR2(50) */
	private String mobile ;
	
	/** password : 密码. PASSWORD: VARCHAR2(50) */
	private String password ;
	
	/** realName : 姓名. REAL_NAME: VARCHAR2(50) */
	private String realName ;
	
	/** phone : 电话. PHONE: VARCHAR2(50) */
	private String phone ;
	
	/** address : 地址. ADDRESS: VARCHAR2(150) */
	private String address ;
	
	/** zip : 邮编. ZIP: VARCHAR2(50) */
	private String zip ;
	
	/** face : 头像. FACE: VARCHAR2(100) */
	private String face ;
	
	/** email : 电子邮件. EMAIL: VARCHAR2(150) */
	private String email ;
	
	/** customerType : 会员类型. CUSTOMER_TYPE: VARCHAR2(1) */
	private String customerType ;
	
	/** registerIp : 注册IP. REGISTER_IP: VARCHAR2(50) */
	private String registerIp ;
	
	/** linkCustomerSeq : 关联序号. LINK_CUSTOMER_SEQ: NUMBER(18) */
	private Long linkCustomerSeq ;
	
	/** isActive : 是否有效. IS_ACTIVE: VARCHAR2(1) */
	private String isActive ;
	
	/** lastLoginTime : 最后登录时间. LAST_LOGIN_TIME: CHAR(14) */
	private String lastLoginTime ;
	
	/** lastLoginIp : 最后登录IP. LAST_LOGIN_IP: VARCHAR2(50) */
	private String lastLoginIp ;
	
	/** idNumber : 证件号码. ID_NUMBER: VARCHAR2(50) */
	private String idNumber ;
	
	/** idType : 证件类型. ID_TYPE: VARCHAR2(2) */
	private String idType ;
	
	/** recTime : 创建时间. REC_TIME: char(14) */
	private String recTime ;
	
	/** lastUptTime : 最后更新时间. LAST_UPT_TIME: char(14) */
	private String lastUptTime ;
	
	/** lastUptAcc : 最后更新账户. LAST_UPT_ACC: varchar(10) */
	private String lastUptAcc ;
	
	/** lastUptOrg : 最后更新机构. LAST_UPT_ORG: varchar(30) */
	private String lastUptOrg ;
	
	/** version : VERSION. VERSION: int */
	private Long version ;
	
	/** passwdErr: PASSWD_ERR. PASSWD_ERR: NUMBER(10) */
	private Long passwdErr;
	
	/** lockTime: LOCK_TIME. LOCK_TIME: CHAR(14) */
	private String lockTime;
	
	private String isActiveDesc;
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public MemberInfoVo() {
		// Default Construtor
	}
	
	public MemberInfoVo(Long customerCode) {
		this.customerCode = customerCode;
	}
		
	// -- Setter And Getter
	/**
	 * Set customerCode : 会员代码. CUSTOMER_CODE: VARCHAR2(50) 
	 */
	public void setCustomerCode(Long customerCode){
		this.customerCode = customerCode;	
	}
	
	/**
	 * Get customerCode : 会员代码. CUSTOMER_CODE: VARCHAR2(50) 
	 */
	public Long getCustomerCode(){
		return this.customerCode;	
	}
	
	/**
	 * Set mobile : 手机号码. MOBILE: VARCHAR2(50) 
	 */
	public void setMobile(String mobile){
		this.mobile = mobile;	
	}
	
	/**
	 * Get mobile : 手机号码. MOBILE: VARCHAR2(50) 
	 */
	public String getMobile(){
		return this.mobile;	
	}
	
	/**
	 * Set password : 密码. PASSWORD: VARCHAR2(50) 
	 */
	public void setPassword(String password){
		this.password = password;	
	}
	
	/**
	 * Get password : 密码. PASSWORD: VARCHAR2(50) 
	 */
	public String getPassword(){
		return this.password;	
	}
	
	/**
	 * Set realName : 姓名. REAL_NAME: VARCHAR2(50) 
	 */
	public void setRealName(String realName){
		this.realName = realName;	
	}
	
	/**
	 * Get realName : 姓名. REAL_NAME: VARCHAR2(50) 
	 */
	public String getRealName(){
		return this.realName;	
	}
	
	/**
	 * Set phone : 电话. PHONE: VARCHAR2(50) 
	 */
	public void setPhone(String phone){
		this.phone = phone;	
	}
	
	/**
	 * Get phone : 电话. PHONE: VARCHAR2(50) 
	 */
	public String getPhone(){
		return this.phone;	
	}
	
	/**
	 * Set address : 地址. ADDRESS: VARCHAR2(150) 
	 */
	public void setAddress(String address){
		this.address = address;	
	}
	
	/**
	 * Get address : 地址. ADDRESS: VARCHAR2(150) 
	 */
	public String getAddress(){
		return this.address;	
	}
	
	/**
	 * Set zip : 邮编. ZIP: VARCHAR2(50) 
	 */
	public void setZip(String zip){
		this.zip = zip;	
	}
	
	/**
	 * Get zip : 邮编. ZIP: VARCHAR2(50) 
	 */
	public String getZip(){
		return this.zip;	
	}
	
	/**
	 * Set face : 头像. FACE: VARCHAR2(100) 
	 */
	public void setFace(String face){
		this.face = face;	
	}
	
	/**
	 * Get face : 头像. FACE: VARCHAR2(100) 
	 */
	public String getFace(){
		return this.face;	
	}
	
	/**
	 * Set email : 电子邮件. EMAIL: VARCHAR2(150) 
	 */
	public void setEmail(String email){
		this.email = email;	
	}
	
	/**
	 * Get email : 电子邮件. EMAIL: VARCHAR2(150) 
	 */
	public String getEmail(){
		return this.email;	
	}
	
	/**
	 * Set customerType : 会员类型. CUSTOMER_TYPE: VARCHAR2(1) 
	 */
	public void setCustomerType(String customerType){
		this.customerType = customerType;	
	}
	
	/**
	 * Get customerType : 会员类型. CUSTOMER_TYPE: VARCHAR2(1) 
	 */
	public String getCustomerType(){
		return this.customerType;	
	}
	
	/**
	 * Set registerIp : 注册IP. REGISTER_IP: VARCHAR2(50) 
	 */
	public void setRegisterIp(String registerIp){
		this.registerIp = registerIp;	
	}
	
	/**
	 * Get registerIp : 注册IP. REGISTER_IP: VARCHAR2(50) 
	 */
	public String getRegisterIp(){
		return this.registerIp;	
	}
	
	/**
	 * Set linkCustomerSeq : 关联序号. LINK_CUSTOMER_SEQ: NUMBER(18) 
	 */
	public void setLinkCustomerSeq(Long linkCustomerSeq){
		this.linkCustomerSeq = linkCustomerSeq;	
	}
	
	/**
	 * Get linkCustomerSeq : 关联序号. LINK_CUSTOMER_SEQ: NUMBER(18) 
	 */
	public Long getLinkCustomerSeq(){
		return this.linkCustomerSeq;	
	}
	
	/**
	 * Set isActive : 是否有效. IS_ACTIVE: VARCHAR2(1) 
	 */
	public void setIsActive(String isActive){
		this.isActive = isActive;	
	}
	
	/**
	 * Get isActive : 是否有效. IS_ACTIVE: VARCHAR2(1) 
	 */
	public String getIsActive(){
		return this.isActive;	
	}
	
	/**
	 * Set lastLoginTime : 最后登录时间. LAST_LOGIN_TIME: CHAR(14) 
	 */
	public void setLastLoginTime(String lastLoginTime){
		this.lastLoginTime = lastLoginTime;	
	}
	
	/**
	 * Get lastLoginTime : 最后登录时间. LAST_LOGIN_TIME: CHAR(14) 
	 */
	public String getLastLoginTime(){
		return this.lastLoginTime;	
	}
	
	/**
	 * Set lastLoginIp : 最后登录IP. LAST_LOGIN_IP: VARCHAR2(50) 
	 */
	public void setLastLoginIp(String lastLoginIp){
		this.lastLoginIp = lastLoginIp;	
	}
	
	/**
	 * Get lastLoginIp : 最后登录IP. LAST_LOGIN_IP: VARCHAR2(50) 
	 */
	public String getLastLoginIp(){
		return this.lastLoginIp;	
	}
	
	/**
	 * Set idNumber : 证件号码. ID_NUMBER: VARCHAR2(50) 
	 */
	public void setIdNumber(String idNumber){
		this.idNumber = idNumber;	
	}
	
	/**
	 * Get idNumber : 证件号码. ID_NUMBER: VARCHAR2(50) 
	 */
	public String getIdNumber(){
		return this.idNumber;	
	}
	
	/**
	 * Set idType : 证件类型. ID_TYPE: VARCHAR2(2) 
	 */
	public void setIdType(String idType){
		this.idType = idType;	
	}
	
	/**
	 * Get idType : 证件类型. ID_TYPE: VARCHAR2(2) 
	 */
	public String getIdType(){
		return this.idType;	
	}

	public String getRecTime() {
		return recTime;
	}

	public void setRecTime(String recTime) {
		this.recTime = recTime;
	}

	public String getLastUptTime() {
		return lastUptTime;
	}

	public void setLastUptTime(String lastUptTime) {
		this.lastUptTime = lastUptTime;
	}

	public String getLastUptAcc() {
		return lastUptAcc;
	}

	public void setLastUptAcc(String lastUptAcc) {
		this.lastUptAcc = lastUptAcc;
	}

	public String getLastUptOrg() {
		return lastUptOrg;
	}

	public void setLastUptOrg(String lastUptOrg) {
		this.lastUptOrg = lastUptOrg;
	}

	public String getFatherCustomerCode() {
		return fatherCustomerCode;
	}

	public void setFatherCustomerCode(String fatherCustomerCode) {
		this.fatherCustomerCode = fatherCustomerCode;
	}

	public String getIsActiveDesc() {
		return isActiveDesc;
	}

	public void setIsActiveDesc(String isActiveDesc) {
		this.isActiveDesc = isActiveDesc;
	}
	
	/** version : VERSION. VERSION: int */
	public Long getVersion() {
		return version;
	}
	
	/** version : VERSION. VERSION: int */
	public void setVersion(Long version) {
		this.version = version;
	}

	public Long getPasswdErr() {
		return passwdErr;
	}

	public void setPasswdErr(Long passwdErr) {
		this.passwdErr = passwdErr;
	}

	public String getLockTime() {
		return lockTime;
	}

	public void setLockTime(String lockTime) {
		this.lockTime = lockTime;
	}
	
}