package com.jiuyv.hhc.model.customer ;

// Generated by AutoCode4J
/**
 * EntityBean: 商户基本信息表 : TBL_MHT_BASE_INFO<br/>
 * This is a value object(VO). <br/>
 * Description: 
 * 
 * 
 * @author AutoCode4J
 * @version 1.0
 * @see com.jiuyv.hhc.model.mchnt.BizMerchantVo
 */
@Deprecated
public class MhtBaseInfoVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) */
	private Long mchntCode ;
	
	/** licNo : 营业执照号码. LIC_NO: VARCHAR(70) */
	private String licNo ;
	
	/** customerCode : 会员代码. CUSTOMER_CODE: VARCHAR2(50) */
	private Long customerCode ;
	
	/** mchntCd : 商户代码. MCHNT_CD: VARCHAR(15) */
	private String mchntCd ;
	
	/** acqInsIdCd : 收单机构代码. ACQ_INS_ID_CD: VARCHAR(20) */
	private String acqInsIdCd ;
	
	/** reveRegCd : 税务登记代码. REVE_REG_CD: VARCHAR(70) */
	private String reveRegCd ;
	
	/** mchntCnName : 商户中文名称. MCHNT_CN_NAME: VARCHAR(100) */
	private String mchntCnName ;
	
	/** regAddr : 注册地址. REG_ADDR: VARCHAR(90) */
	private String regAddr ;
	
	/** artifNm : 法人代表姓名. ARTIF_NM: VARCHAR(40) */
	private String artifNm ;
	
	/** artifCertifId : 法人代表证件号. ARTIF_CERTIF_ID: VARCHAR(22) */
	private String artifCertifId ;
	
	/** artifCertifType : 法人代表证件类型. ARTIF_CERTIF_TYPE: VARCHAR(2) */
	private String artifCertifType ;
	
	/** mchntTp : 商户类型. MCHNT_TP: VARCHAR(2) */
	private String mchntTp ;
	
	/** mchntGrp : 商户组别. MCHNT_GRP: VARCHAR(4) */
	private String mchntGrp ;
	
	/** phone : 联系电话. PHONE: VARCHAR(40) */
	private String phone ;
	
	/** mchntCrtDt : 商户入网时间. MCHNT_CRT_DT: CHAR(8) */
	private String mchntCrtDt ;
	
	/** posNum : 装机数量. POS_NUM: NUMBER */
	private Long posNum ;
	
	/** remark : 备注. REMARK: VARCHAR(200) */
	private String remark ;
	
	/** mchntSt : 商户状态. MCHNT_ST: VARCHAR(2) */
	private String mchntSt ;
	
	/** respInfo : 银联返回信息. RESP_INFO: VARCHAR2(200) */
	private String respInfo ;
	
	/** auditTime : 资质申请时间. AUDIT_TIME: CHAR(14) */
	private String auditTime ;
	
	/** beforeTime : 贷前查询时间. BEFORE_TIME: CHAR(14) */
	private String beforeTime ;
	
	/** recAcc : 记录账户. REC_ACC: VARCHAR2(30) */
	private String recAcc ;
	
	/** recTime : 记录创建时间. REC_TIME: CHAR(14) */
	private String recTime ;
	
	/** lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) */
	private String lastUptTime ;
	
	/** lastUptAcc : 最后更新账户. LAST_UPT_ACC: VARCHAR2(30) */
	private String lastUptAcc ;
	
	/** lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) */
	private String lastUptOrg ;
	
	/** version : VERSION. VERSION: int */
	private Long version ;
	
	private String mchntStDesc;
	
	/** mchntTp : 商户类型. MCHNT_TP: VARCHAR(2) */
	private String mchntTpDesc ;
	
	/** mchntGrp : 商户组别. MCHNT_GRP: VARCHAR(4) */
	private String mchntGrpDesc ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public MhtBaseInfoVo() {
		// Default Construtor
	}
	
	public MhtBaseInfoVo(Long mchntCode) {
		this.mchntCode = mchntCode;
	}
		
	// -- Setter And Getter
	/**
	 * Set mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public void setMchntCode(Long mchntCode){
		this.mchntCode = mchntCode;	
	}
	
	/**
	 * Get mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public Long getMchntCode(){
		return this.mchntCode;	
	}
	
	/**
	 * Set licNo : 营业执照号码. LIC_NO: VARCHAR(70) 
	 */
	public void setLicNo(String licNo){
		this.licNo = licNo;	
	}
	
	/**
	 * Get licNo : 营业执照号码. LIC_NO: VARCHAR(70) 
	 */
	public String getLicNo(){
		return this.licNo;	
	}
	
	/**
	 * Set customerCode : 会员代码. CUSTOMER_CODE: VARCHAR2(50) 
	 */
	public void setCustomerCode(Long customerCode){
		this.customerCode = customerCode;	
	}
	
	/**
	 * Get customerCode : 会员代码. CUSTOMER_CODE: VARCHAR2(50) 
	 */
	public Long getCustomerCode(){
		return this.customerCode;	
	}
	
	/**
	 * Set mchntCd : 商户代码. MCHNT_CD: VARCHAR(15) 
	 */
	public void setMchntCd(String mchntCd){
		this.mchntCd = mchntCd;	
	}
	
	/**
	 * Get mchntCd : 商户代码. MCHNT_CD: VARCHAR(15) 
	 */
	public String getMchntCd(){
		return this.mchntCd;	
	}
	
	/**
	 * Set acqInsIdCd : 收单机构代码. ACQ_INS_ID_CD: VARCHAR(20) 
	 */
	public void setAcqInsIdCd(String acqInsIdCd){
		this.acqInsIdCd = acqInsIdCd;	
	}
	
	/**
	 * Get acqInsIdCd : 收单机构代码. ACQ_INS_ID_CD: VARCHAR(20) 
	 */
	public String getAcqInsIdCd(){
		return this.acqInsIdCd;	
	}
	
	/**
	 * Set reveRegCd : 税务登记代码. REVE_REG_CD: VARCHAR(70) 
	 */
	public void setReveRegCd(String reveRegCd){
		this.reveRegCd = reveRegCd;	
	}
	
	/**
	 * Get reveRegCd : 税务登记代码. REVE_REG_CD: VARCHAR(70) 
	 */
	public String getReveRegCd(){
		return this.reveRegCd;	
	}
	
	/**
	 * Set mchntCnName : 商户中文名称. MCHNT_CN_NAME: VARCHAR(100) 
	 */
	public void setMchntCnName(String mchntCnName){
		this.mchntCnName = mchntCnName;	
	}
	
	/**
	 * Get mchntCnName : 商户中文名称. MCHNT_CN_NAME: VARCHAR(100) 
	 */
	public String getMchntCnName(){
		return this.mchntCnName;	
	}
	
	/**
	 * Set regAddr : 注册地址. REG_ADDR: VARCHAR(90) 
	 */
	public void setRegAddr(String regAddr){
		this.regAddr = regAddr;	
	}
	
	/**
	 * Get regAddr : 注册地址. REG_ADDR: VARCHAR(90) 
	 */
	public String getRegAddr(){
		return this.regAddr;	
	}
	
	/**
	 * Set artifNm : 法人代表姓名. ARTIF_NM: VARCHAR(40) 
	 */
	public void setArtifNm(String artifNm){
		this.artifNm = artifNm;	
	}
	
	/**
	 * Get artifNm : 法人代表姓名. ARTIF_NM: VARCHAR(40) 
	 */
	public String getArtifNm(){
		return this.artifNm;	
	}
	
	/**
	 * Set artifCertifId : 法人代表证件号. ARTIF_CERTIF_ID: VARCHAR(22) 
	 */
	public void setArtifCertifId(String artifCertifId){
		this.artifCertifId = artifCertifId;	
	}
	
	/**
	 * Get artifCertifId : 法人代表证件号. ARTIF_CERTIF_ID: VARCHAR(22) 
	 */
	public String getArtifCertifId(){
		return this.artifCertifId;	
	}
	
	/**
	 * Set artifCertifType : 法人代表证件类型. ARTIF_CERTIF_TYPE: VARCHAR(2) 
	 */
	public void setArtifCertifType(String artifCertifType){
		this.artifCertifType = artifCertifType;	
	}
	
	/**
	 * Get artifCertifType : 法人代表证件类型. ARTIF_CERTIF_TYPE: VARCHAR(2) 
	 */
	public String getArtifCertifType(){
		return this.artifCertifType;	
	}
	
	/**
	 * Set mchntTp : 商户类型. MCHNT_TP: VARCHAR(2) 
	 */
	public void setMchntTp(String mchntTp){
		this.mchntTp = mchntTp;	
	}
	
	/**
	 * Get mchntTp : 商户类型. MCHNT_TP: VARCHAR(2) 
	 */
	public String getMchntTp(){
		return this.mchntTp;	
	}
	
	/**
	 * Set mchntGrp : 商户组别. MCHNT_GRP: VARCHAR(4) 
	 */
	public void setMchntGrp(String mchntGrp){
		this.mchntGrp = mchntGrp;	
	}
	
	/**
	 * Get mchntGrp : 商户组别. MCHNT_GRP: VARCHAR(4) 
	 */
	public String getMchntGrp(){
		return this.mchntGrp;	
	}
	
	/**
	 * Set phone : 联系电话. PHONE: VARCHAR(40) 
	 */
	public void setPhone(String phone){
		this.phone = phone;	
	}
	
	/**
	 * Get phone : 联系电话. PHONE: VARCHAR(40) 
	 */
	public String getPhone(){
		return this.phone;	
	}
	
	/**
	 * Set mchntCrtDt : 商户入网时间. MCHNT_CRT_DT: CHAR(8) 
	 */
	public void setMchntCrtDt(String mchntCrtDt){
		this.mchntCrtDt = mchntCrtDt;	
	}
	
	/**
	 * Get mchntCrtDt : 商户入网时间. MCHNT_CRT_DT: CHAR(8) 
	 */
	public String getMchntCrtDt(){
		return this.mchntCrtDt;	
	}
	
	/**
	 * Set posNum : 装机数量. POS_NUM: NUMBER 
	 */
	public void setPosNum(Long posNum){
		this.posNum = posNum;	
	}
	
	/**
	 * Get posNum : 装机数量. POS_NUM: NUMBER 
	 */
	public Long getPosNum(){
		return this.posNum;	
	}
	
	/**
	 * Set remark : 备注. REMARK: VARCHAR(200) 
	 */
	public void setRemark(String remark){
		this.remark = remark;	
	}
	
	/**
	 * Get remark : 备注. REMARK: VARCHAR(200) 
	 */
	public String getRemark(){
		return this.remark;	
	}
	
	/**
	 * Set mchntSt : 商户状态. MCHNT_ST: VARCHAR(2) 
	 */
	public void setMchntSt(String mchntSt){
		this.mchntSt = mchntSt;	
	}
	
	/**
	 * Get mchntSt : 商户状态. MCHNT_ST: VARCHAR(2) 
	 */
	public String getMchntSt(){
		return this.mchntSt;	
	}
	
	/**
	 * Set lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public void setLastUptTime(String lastUptTime){
		this.lastUptTime = lastUptTime;	
	}
	
	/**
	 * Get lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public String getLastUptTime(){
		return this.lastUptTime;	
	}
	
	/**
	 * Set lastUptAcc : 最后更新账户. LAST_UPT_ACC: VARCHAR2(30) 
	 */
	public void setLastUptAcc(String lastUptAcc){
		this.lastUptAcc = lastUptAcc;	
	}
	
	/**
	 * Get lastUptAcc : 最后更新账户. LAST_UPT_ACC: VARCHAR2(30) 
	 */
	public String getLastUptAcc(){
		return this.lastUptAcc;	
	}
	
	/**
	 * Set lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) 
	 */
	public void setLastUptOrg(String lastUptOrg){
		this.lastUptOrg = lastUptOrg;	
	}
	
	/**
	 * Get lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) 
	 */
	public String getLastUptOrg(){
		return this.lastUptOrg;	
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getMchntStDesc() {
		return mchntStDesc;
	}

	public void setMchntStDesc(String mchntStDesc) {
		this.mchntStDesc = mchntStDesc;
	}

	/**
	 * @return the mchntTpDesc
	 */
	public String getMchntTpDesc() {
		return mchntTpDesc;
	}

	/**
	 * @param mchntTpDesc the mchntTpDesc to set
	 */
	public void setMchntTpDesc(String mchntTpDesc) {
		this.mchntTpDesc = mchntTpDesc;
	}

	/**
	 * @return the mchntGrpDesc
	 */
	public String getMchntGrpDesc() {
		return mchntGrpDesc;
	}

	/**
	 * @param mchntGrpDesc the mchntGrpDesc to set
	 */
	public void setMchntGrpDesc(String mchntGrpDesc) {
		this.mchntGrpDesc = mchntGrpDesc;
	}

	/**
	 * @return the respInfo
	 */
	public String getRespInfo() {
		return respInfo;
	}

	/**
	 * @param respInfo the respInfo to set
	 */
	public void setRespInfo(String respInfo) {
		this.respInfo = respInfo;
	}

	/**
	 * @return the auditTime
	 */
	public String getAuditTime() {
		return auditTime;
	}

	/**
	 * @param auditTime the auditTime to set
	 */
	public void setAuditTime(String auditTime) {
		this.auditTime = auditTime;
	}

	/**
	 * @return the beforeTime
	 */
	public String getBeforeTime() {
		return beforeTime;
	}

	/**
	 * @param beforeTime the beforeTime to set
	 */
	public void setBeforeTime(String beforeTime) {
		this.beforeTime = beforeTime;
	}

	/**
	 * @return the recAcc
	 */
	public String getRecAcc() {
		return recAcc;
	}

	/**
	 * @param recAcc the recAcc to set
	 */
	public void setRecAcc(String recAcc) {
		this.recAcc = recAcc;
	}

	/**
	 * @return the recTime
	 */
	public String getRecTime() {
		return recTime;
	}

	/**
	 * @param recTime the recTime to set
	 */
	public void setRecTime(String recTime) {
		this.recTime = recTime;
	}
	
}