package com.jiuyv.hhc.model.customer ;

// Generated by AutoCode4J
/**
 * EntityBean: 代理商推荐号信息表 : TBL_WEB_AGENT_RCMD
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class WebAgentRcmdVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** rcmdCode : 推荐号. RCMD_CODE: NVARCHAR2(50) */
	private String rcmdCode ;
	
	/** customerCode : 会员代码. CUSTOMER_CODE: NUMBER(10) */
	private Long customerCode ;
	
	/** rcmdDesc : 描述. RCMD_DESC: NVARCHAR2(200) */
	private String rcmdDesc ;
	
	/** rcmdCnt : 推荐数量. RCMD_CNT: NUMBER(10) */
	private Long rcmdCnt ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public WebAgentRcmdVo() {
		// Default Construtor
	}
	
	public WebAgentRcmdVo(String rcmdCode) {
		this.rcmdCode = rcmdCode;
	}
		
	// -- Setter And Getter
	/**
	 * Set rcmdCode : 推荐号. RCMD_CODE: NVARCHAR2(50) 
	 */
	public void setRcmdCode(String rcmdCode){
		this.rcmdCode = rcmdCode;	
	}
	
	/**
	 * Get rcmdCode : 推荐号. RCMD_CODE: NVARCHAR2(50) 
	 */
	public String getRcmdCode(){
		return this.rcmdCode;	
	}
	
	/**
	 * Set customerCode : 会员代码. CUSTOMER_CODE: NUMBER(10) 
	 */
	public void setCustomerCode(Long customerCode){
		this.customerCode = customerCode;	
	}
	
	/**
	 * Get customerCode : 会员代码. CUSTOMER_CODE: NUMBER(10) 
	 */
	public Long getCustomerCode(){
		return this.customerCode;	
	}
	
	/**
	 * Set rcmdDesc : 描述. RCMD_DESC: NVARCHAR2(200) 
	 */
	public void setRcmdDesc(String rcmdDesc){
		this.rcmdDesc = rcmdDesc;	
	}
	
	/**
	 * Get rcmdDesc : 描述. RCMD_DESC: NVARCHAR2(200) 
	 */
	public String getRcmdDesc(){
		return this.rcmdDesc;	
	}
	
	/**
	 * Set rcmdCnt : 推荐数量. RCMD_CNT: NUMBER(10) 
	 */
	public void setRcmdCnt(Long rcmdCnt){
		this.rcmdCnt = rcmdCnt;	
	}
	
	/**
	 * Get rcmdCnt : 推荐数量. RCMD_CNT: NUMBER(10) 
	 */
	public Long getRcmdCnt(){
		return this.rcmdCnt;	
	}
	
}