package com.jiuyv.hhc.model.message.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.message.MsgMailVo;

// Generated by AutoCode4J
/**
 * Interface: 邮件内容表 : TBL_MSG_MAIL
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface MsgMailDao extends BaseDao<MsgMailVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.message.dao.MsgMailDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.message.dao.MsgMailDao.filterQuery";

	/**
	 * Find MsgMailVo by Primary Key. 
	 * 
	 * @param mailId : 邮件ID	 
	 * @return MsgMailVo : 邮件内容表
	 */
	MsgMailVo findByKey(Long mailId ) ;
}
