package com.jiuyv.hhc.model.message.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.message.MsgMessageVo;

// Generated by AutoCode4J
/**
 * Interface: 系统消息表 : TBL_MSG_MESSAGE
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface MsgMessageDao extends BaseDao<MsgMessageVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.message.dao.MsgMessageDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.message.dao.MsgMessageDao.filterQuery";
	/** No Content Single Table */
	String MAPPED_FIND_NCS = "com.jiuyv.hhc.model.message.dao.MsgMessageDao.filterNCSingleQuery";
	/** No Content */
	String MAPPED_FIND_NC = "com.jiuyv.hhc.model.message.dao.MsgMessageDao.filterNoContentQuery";

	/**
	 * Find MsgMessageVo by Primary Key. 
	 * 
	 * @param msgId : 消息ID	 
	 * @return MsgMessageVo : 系统消息表
	 */
	MsgMessageVo findByKey(Long msgId ) ;

}