package com.jiuyv.hhc.model.message.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.message.MsgRecvVo;

// Generated by AutoCode4J
/**
 * Interface: 系统消息接收方 : TBL_MSG_RECV
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface MsgRecvDao extends BaseDao<MsgRecvVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.message.dao.MsgRecvDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.message.dao.MsgRecvDao.filterQuery";

	/**
	 * Find MsgRecvVo by Primary Key. 
	 * 
	 * @param msgId : 消息ID
	 * @param recvId : 收件人ID	 
	 * @return MsgRecvVo : 系统消息接收方
	 */
	MsgRecvVo findByKey(Long msgId , Long recvId ) ;
	
	/**
	 * Delete by msg id.
	 * 根据消息Id删除收件人信息
	 * @param msgId the msg id
	 * @return the int
	 */
	int deleteByMsgId(Long msgId);
	
}