package com.jiuyv.hhc.model.message.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.message.MsgTplParamVo;

// Generated by AutoCode4J
/**
 * Interface: 信息模板参数表 : TBL_MSG_TPL_PARAM
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface MsgTplParamDao extends BaseDao<MsgTplParamVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.message.dao.MsgTplParamDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.message.dao.MsgTplParamDao.filterQuery";

	/**
	 * Find MsgTplParamVo by Primary Key. 
	 * 
	 * @param paramCode : 参数代码	 
	 * @return MsgTplParamVo : 信息模板参数表
	 */
	MsgTplParamVo findByKey(String paramCode ) ;
}
