package com.jiuyv.hhc.model.mchnt ;

// Generated by AutoCode4J
/**
 * EntityBean: [New]商户附件定义表 : TBL_BIZ_ATTACH_DEF
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class BizAttachDefVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** attachType : 附件类型. ATTACH_TYPE: VARCHAR2(20) */
	private String attachType ;
	
	/** attachName : 附件名称. ATTACH_NAME: NVARCHAR2(20) */
	private String attachName ;
	
	/** attachGroup : 分组. ATTACH_GROUP: VARCHAR2(2) */
	private String attachGroup ;
	
	/** attachSort : 排序. ATTACH_SORT: NUMBER(5) */
	private Long attachSort ;
	
	/** necessary : 是否必填. NECESSARY: CHAR(1) */
	private String necessary ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public BizAttachDefVo() {
		// Default Construtor
	}
	
	public BizAttachDefVo(String attachType) {
		this.attachType = attachType;
	}
		
	// -- Setter And Getter
	/**
	 * Set attachType : 附件类型. ATTACH_TYPE: VARCHAR2(20) 
	 */
	public void setAttachType(String attachType){
		this.attachType = attachType;	
	}
	
	/**
	 * Get attachType : 附件类型. ATTACH_TYPE: VARCHAR2(20) 
	 */
	public String getAttachType(){
		return this.attachType;	
	}
	
	/**
	 * Set attachName : 附件名称. ATTACH_NAME: NVARCHAR2(20) 
	 */
	public void setAttachName(String attachName){
		this.attachName = attachName;	
	}
	
	/**
	 * Get attachName : 附件名称. ATTACH_NAME: NVARCHAR2(20) 
	 */
	public String getAttachName(){
		return this.attachName;	
	}
	
	/**
	 * Set attachGroup : 分组. ATTACH_GROUP: VARCHAR2(2) 
	 */
	public void setAttachGroup(String attachGroup){
		this.attachGroup = attachGroup;	
	}
	
	/**
	 * Get attachGroup : 分组. ATTACH_GROUP: VARCHAR2(2) 
	 */
	public String getAttachGroup(){
		return this.attachGroup;	
	}
	
	/**
	 * Set attachSort : 排序. ATTACH_SORT: NUMBER(5) 
	 */
	public void setAttachSort(Long attachSort){
		this.attachSort = attachSort;	
	}
	
	/**
	 * Get attachSort : 排序. ATTACH_SORT: NUMBER(5) 
	 */
	public Long getAttachSort(){
		return this.attachSort;	
	}
	
	/**
	 * Set necessary : 是否必填. NECESSARY: CHAR(1) 
	 */
	public void setNecessary(String necessary){
		this.necessary = necessary;	
	}
	
	/**
	 * Get necessary : 是否必填. NECESSARY: CHAR(1) 
	 */
	public String getNecessary(){
		return this.necessary;	
	}
	
}