package com.jiuyv.hhc.model.mchnt ;

// Generated by AutoCode4J
/**
 * EntityBean: [New]商户信息附件表 : TBL_BIZ_MCHNT_ATTACH
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class BizMchntAttachVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** attachSeq : 附件编号. ATTACH_SEQ: NUMBER(10) */
	private Long attachSeq ;
	
	/** mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) */
	private Long mchntCode ;
	
	/** attachType : 附件类型. ATTACH_TYPE: VARCHAR2(20) */
	private String attachType ;
	
	/** attachDesc : 附件描述. ATTACH_DESC: NVARCHAR2(40) */
	private String attachDesc ;
	
	/** attachUrl : 附件URL. ATTACH_URL: VARCHAR2(256) */
	private String attachUrl ;
	
	/** attachTime : 上传时间. ATTACH_TIME: CHAR(14) */
	private String attachTime ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public BizMchntAttachVo() {
		// Default Construtor
	}
	
	public BizMchntAttachVo(Long attachSeq) {
		this.attachSeq = attachSeq;
	}
		
	// -- Setter And Getter
	/**
	 * Set attachSeq : 附件编号. ATTACH_SEQ: NUMBER(10) 
	 */
	public void setAttachSeq(Long attachSeq){
		this.attachSeq = attachSeq;	
	}
	
	/**
	 * Get attachSeq : 附件编号. ATTACH_SEQ: NUMBER(10) 
	 */
	public Long getAttachSeq(){
		return this.attachSeq;	
	}
	
	/**
	 * Set mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public void setMchntCode(Long mchntCode){
		this.mchntCode = mchntCode;	
	}
	
	/**
	 * Get mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public Long getMchntCode(){
		return this.mchntCode;	
	}
	
	/**
	 * Set attachType : 附件类型. ATTACH_TYPE: VARCHAR2(20) 
	 */
	public void setAttachType(String attachType){
		this.attachType = attachType;	
	}
	
	/**
	 * Get attachType : 附件类型. ATTACH_TYPE: VARCHAR2(20) 
	 */
	public String getAttachType(){
		return this.attachType;	
	}
	
	/**
	 * Set attachDesc : 附件描述. ATTACH_DESC: NVARCHAR2(40) 
	 */
	public void setAttachDesc(String attachDesc){
		this.attachDesc = attachDesc;	
	}
	
	/**
	 * Get attachDesc : 附件描述. ATTACH_DESC: NVARCHAR2(40) 
	 */
	public String getAttachDesc(){
		return this.attachDesc;	
	}
	
	/**
	 * Set attachUrl : 附件URL. ATTACH_URL: VARCHAR2(256) 
	 */
	public void setAttachUrl(String attachUrl){
		this.attachUrl = attachUrl;	
	}
	
	/**
	 * Get attachUrl : 附件URL. ATTACH_URL: VARCHAR2(256) 
	 */
	public String getAttachUrl(){
		return this.attachUrl;	
	}
	
	/**
	 * Set attachTime : 上传时间. ATTACH_TIME: CHAR(14) 
	 */
	public void setAttachTime(String attachTime){
		this.attachTime = attachTime;	
	}
	
	/**
	 * Get attachTime : 上传时间. ATTACH_TIME: CHAR(14) 
	 */
	public String getAttachTime(){
		return this.attachTime;	
	}
	
}