package com.jiuyv.hhc.model.mchnt ;

// Generated by AutoCode4J
/**
 * EntityBean: [New]商户信息表 : TBL_BIZ_MERCHANT
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class BizMerchantVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) */
	private Long mchntCode ;
	
	/** version : VERSION. VERSION: NUMBER(10) */
	private Long version ;
	
	/** licNo : 营业执照号码. LIC_NO: VARCHAR2(70) */
	private String licNo ;
	
	/** customerCode : 会员代码. CUSTOMER_CODE: NUMBER(10) */
	private Long customerCode ;
	
	/** mchntCd : 商户代码. MCHNT_CD: VARCHAR2(15) */
	private String mchntCd ;
	
	/** acqInsIdCd : 收单机构代码. ACQ_INS_ID_CD: VARCHAR2(20) */
	private String acqInsIdCd ;
	
	/** reveRegCd : 税务登记代码. REVE_REG_CD: VARCHAR2(70) */
	private String reveRegCd ;
	
	/** mchntCnName : 工商注册名称. MCHNT_CN_NAME: NVARCHAR2(100) */
	private String mchntCnName ;
	
	/** regAddr : 注册地址. REG_ADDR: NVARCHAR2(90) */
	private String regAddr ;
	
	/** artifNm : 法人代表姓名. ARTIF_NM: NVARCHAR2(40) */
	private String artifNm ;
	
	/** artifCertifId : 法人代表证件号. ARTIF_CERTIF_ID: VARCHAR2(22) */
	private String artifCertifId ;
	
	/** artifCertifType : 法人代表证件类型. ARTIF_CERTIF_TYPE: VARCHAR2(2) */
	private String artifCertifType ;
	
	/** mchntTp : 商户类型. MCHNT_TP: VARCHAR2(4) */
	private String mchntTp ;
	
	/** mchntGrp : 商户组别. MCHNT_GRP: VARCHAR2(4) */
	private String mchntGrp ;
	
	/** phone : 联系电话. PHONE: VARCHAR2(40) */
	private String phone ;
	
	/** mchntCrtDt : 商户入网时间. MCHNT_CRT_DT: CHAR(8) */
	private String mchntCrtDt ;
	
	/** posNum : 装机数量. POS_NUM: NUMBER */
	private Long posNum ;
	
	/** remark : 备注. REMARK: NVARCHAR2(200) */
	private String remark ;
	
	/** mchntSt : 商户状态. MCHNT_ST: VARCHAR(2) */
	private String mchntSt ;
	
	/** dispMchntSt : 客户端显示状态. DISP_MCHNT_ST: VARCHAR(2) */
	private String dispMchntSt ;
	
	/** recAcc : 记录创建账户. REC_ACC: NVARCHAR2(30) */
	private String recAcc ;
	
	/** recTime : 记录创建时间. REC_TIME: CHAR(14) */
	private String recTime ;
	
	/** lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) */
	private String lastUptTime ;
	
	/** lastUptAcc : 最后更新账户. LAST_UPT_ACC: NVARCHAR2(30) */
	private String lastUptAcc ;
	
	/** lastUptOrg : 最后更新机构. LAST_UPT_ORG: NVARCHAR2(30) */
	private String lastUptOrg ;
	
	/** lastCupOpr : 最近接口操作. LAST_CUP_OPR: VARCHAR2(40) */
	private String lastCupOpr ;
	
	/** lastCupTime : 最近接口调用时间. LAST_CUP_TIME: CHAR(14) */
	private String lastCupTime ;
	
	/** lastCupResp : 最近接口返回信息. LAST_CUP_RESP: NVARCHAR2(200) */
	private String lastCupResp ;
	
	/** auditTime : 最近资质申请成功时间. AUDIT_TIME: CHAR(14) */
	private String auditTime ;
	
	/** beforeTime : 最近贷前查询成功时间. BEFORE_TIME: CHAR(14) */
	private String beforeTime ;
	
	/** cupMchntInfo : 银联商户数据内容. CUP_MCHNT_INFO: NVARCHAR2(1500) */
	private String cupMchntInfo ;
	
	// -- mchntProp --

	/** mchntEnType : 商户性质. MCHNT_EN_TYPE: CHAR(1) */
	private String mchntEnType ;
	
	/** mchntDispName : 商户名称. MCHNT_DISP_NAME: NVARCHAR2(200) */
	private String mchntDispName ;
	
	/** mchntContact : 商户联系人. MCHNT_CONTACT: NVARCHAR2(20) */
	private String mchntContact ;
	
	/** mchntContactMobile : 商户联系人移动电话. MCHNT_CONTACT_MOBILE: VARCHAR2(40) */
	private String mchntContactMobile ;
	
	/** mchntArtifMobile : 企业法人代表/个体商户主移动电话. MCHNT_ARTIF_MOBILE: VARCHAR2(40) */
	private String mchntArtifMobile ;
	
	/** telephone : 固定电话. TELEPHONE: VARCHAR2(40) */
	private String telephone ;
	
	/** mchntStartDate : 经营起始日期. MCHNT_START_DATE: CHAR(8) */
	private String mchntStartDate ;
	
	/** regCapital : 企业注册资本. REG_CAPITAL: NUMBER(12) */
	private Long regCapital ;
	
	/** orgCode : 企业组织结构代码证编号. ORG_CODE: VARCHAR2(20) */
	private String orgCode ;
	
	/** othBankName : 他行储蓄账户开户行. OTH_BANK_NAME: NVARCHAR2(80) */
	private String othBankName ;
	
	/** othCardNo : 他行储蓄账户卡号. OTH_CARD_NO: VARCHAR2(30) */
	private String othCardNo ;
	
	// -- Extended --
	/** mchntStDesc : 商户状态描述.  */
	private String mchntStDesc;
	
	/** dispMchntStDesc : 客户端显示状态. */
	private String dispMchntStDesc ;
	
	/** mchntTpDesc : 商户类型描述. */
	private String mchntTpDesc ;
	
	/** mchntGrpDesc : 商户组别描述. */
	private String mchntGrpDesc ;
	
	/** customerCode : 会员代码. CUSTOMER_CODE: NUMBER(10) */
	private String customerCodeDesc ;
	
	/** customerMobile : 会员手机号.  */
	private String customerMobile ; 
	
	/** mchntEnType : 商户性质. MCHNT_EN_TYPE: CHAR(1) */
	private String mchntEnTypeDesc ;
	
	/** lastCupOprDesc : 最近接口操作. */
	private String lastCupOprDesc ;
	
	/** recAccDesc : 记录创建账户.*/
	private String recAccDesc ;
	
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public BizMerchantVo() {
		// Default Construtor
	}
	
	public BizMerchantVo(Long mchntCode) {
		this.mchntCode = mchntCode;
	}
		
	// -- Setter And Getter
	/**
	 * Set mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public void setMchntCode(Long mchntCode){
		this.mchntCode = mchntCode;	
	}
	
	/**
	 * Get mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public Long getMchntCode(){
		return this.mchntCode;	
	}
	
	/**
	 * Set version : VERSION. VERSION: NUMBER(10) 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: NUMBER(10) 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set licNo : 营业执照号码. LIC_NO: VARCHAR2(70) 
	 */
	public void setLicNo(String licNo){
		this.licNo = licNo;	
	}
	
	/**
	 * Get licNo : 营业执照号码. LIC_NO: VARCHAR2(70) 
	 */
	public String getLicNo(){
		return this.licNo;	
	}
	
	/**
	 * Set customerCode : 会员代码. CUSTOMER_CODE: NUMBER(10) 
	 */
	public void setCustomerCode(Long customerCode){
		this.customerCode = customerCode;	
	}
	
	/**
	 * Get customerCode : 会员代码. CUSTOMER_CODE: NUMBER(10) 
	 */
	public Long getCustomerCode(){
		return this.customerCode;	
	}
	
	/**
	 * Set mchntCd : 商户代码. MCHNT_CD: VARCHAR2(15) 
	 */
	public void setMchntCd(String mchntCd){
		this.mchntCd = mchntCd;	
	}
	
	/**
	 * Get mchntCd : 商户代码. MCHNT_CD: VARCHAR2(15) 
	 */
	public String getMchntCd(){
		return this.mchntCd;	
	}
	
	/**
	 * Set acqInsIdCd : 收单机构代码. ACQ_INS_ID_CD: VARCHAR2(20) 
	 */
	public void setAcqInsIdCd(String acqInsIdCd){
		this.acqInsIdCd = acqInsIdCd;	
	}
	
	/**
	 * Get acqInsIdCd : 收单机构代码. ACQ_INS_ID_CD: VARCHAR2(20) 
	 */
	public String getAcqInsIdCd(){
		return this.acqInsIdCd;	
	}
	
	/**
	 * Set reveRegCd : 税务登记代码. REVE_REG_CD: VARCHAR2(70) 
	 */
	public void setReveRegCd(String reveRegCd){
		this.reveRegCd = reveRegCd;	
	}
	
	/**
	 * Get reveRegCd : 税务登记代码. REVE_REG_CD: VARCHAR2(70) 
	 */
	public String getReveRegCd(){
		return this.reveRegCd;	
	}
	
	/**
	 * Set mchntCnName : 工商注册名称. MCHNT_CN_NAME: NVARCHAR2(100) 
	 */
	public void setMchntCnName(String mchntCnName){
		this.mchntCnName = mchntCnName;	
	}
	
	/**
	 * Get mchntCnName : 工商注册名称. MCHNT_CN_NAME: NVARCHAR2(100) 
	 */
	public String getMchntCnName(){
		return this.mchntCnName;	
	}
	
	/**
	 * Set regAddr : 注册地址. REG_ADDR: NVARCHAR2(90) 
	 */
	public void setRegAddr(String regAddr){
		this.regAddr = regAddr;	
	}
	
	/**
	 * Get regAddr : 注册地址. REG_ADDR: NVARCHAR2(90) 
	 */
	public String getRegAddr(){
		return this.regAddr;	
	}
	
	/**
	 * Set artifNm : 法人代表姓名. ARTIF_NM: NVARCHAR2(40) 
	 */
	public void setArtifNm(String artifNm){
		this.artifNm = artifNm;	
	}
	
	/**
	 * Get artifNm : 法人代表姓名. ARTIF_NM: NVARCHAR2(40) 
	 */
	public String getArtifNm(){
		return this.artifNm;	
	}
	
	/**
	 * Set artifCertifId : 法人代表证件号. ARTIF_CERTIF_ID: VARCHAR2(22) 
	 */
	public void setArtifCertifId(String artifCertifId){
		this.artifCertifId = artifCertifId;	
	}
	
	/**
	 * Get artifCertifId : 法人代表证件号. ARTIF_CERTIF_ID: VARCHAR2(22) 
	 */
	public String getArtifCertifId(){
		return this.artifCertifId;	
	}
	
	/**
	 * Set artifCertifType : 法人代表证件类型. ARTIF_CERTIF_TYPE: VARCHAR2(2) 
	 */
	public void setArtifCertifType(String artifCertifType){
		this.artifCertifType = artifCertifType;	
	}
	
	/**
	 * Get artifCertifType : 法人代表证件类型. ARTIF_CERTIF_TYPE: VARCHAR2(2) 
	 */
	public String getArtifCertifType(){
		return this.artifCertifType;	
	}
	
	/**
	 * Set mchntTp : 商户类型. MCHNT_TP: VARCHAR2(4) 
	 */
	public void setMchntTp(String mchntTp){
		this.mchntTp = mchntTp;	
	}
	
	/**
	 * Get mchntTp : 商户类型. MCHNT_TP: VARCHAR2(4) 
	 */
	public String getMchntTp(){
		return this.mchntTp;	
	}
	
	/**
	 * Set mchntGrp : 商户组别. MCHNT_GRP: VARCHAR2(4) 
	 */
	public void setMchntGrp(String mchntGrp){
		this.mchntGrp = mchntGrp;	
	}
	
	/**
	 * Get mchntGrp : 商户组别. MCHNT_GRP: VARCHAR2(4) 
	 */
	public String getMchntGrp(){
		return this.mchntGrp;	
	}
	
	/**
	 * Set phone : 联系电话. PHONE: VARCHAR2(40) 
	 */
	public void setPhone(String phone){
		this.phone = phone;	
	}
	
	/**
	 * Get phone : 联系电话. PHONE: VARCHAR2(40) 
	 */
	public String getPhone(){
		return this.phone;	
	}
	
	/**
	 * Set mchntCrtDt : 商户入网时间. MCHNT_CRT_DT: CHAR(8) 
	 */
	public void setMchntCrtDt(String mchntCrtDt){
		this.mchntCrtDt = mchntCrtDt;	
	}
	
	/**
	 * Get mchntCrtDt : 商户入网时间. MCHNT_CRT_DT: CHAR(8) 
	 */
	public String getMchntCrtDt(){
		return this.mchntCrtDt;	
	}
	
	/**
	 * Set posNum : 装机数量. POS_NUM: NUMBER 
	 */
	public void setPosNum(Long posNum){
		this.posNum = posNum;	
	}
	
	/**
	 * Get posNum : 装机数量. POS_NUM: NUMBER 
	 */
	public Long getPosNum(){
		return this.posNum;	
	}
	
	/**
	 * Set remark : 备注. REMARK: NVARCHAR2(200) 
	 */
	public void setRemark(String remark){
		this.remark = remark;	
	}
	
	/**
	 * Get remark : 备注. REMARK: NVARCHAR2(200) 
	 */
	public String getRemark(){
		return this.remark;	
	}
	
	/**
	 * Set mchntSt : 商户状态. MCHNT_ST: VARCHAR(2) 
	 */
	public void setMchntSt(String mchntSt){
		this.mchntSt = mchntSt;	
	}
	
	/**
	 * Get mchntSt : 商户状态. MCHNT_ST: VARCHAR(2) 
	 */
	public String getMchntSt(){
		return this.mchntSt;	
	}
	
	/**
	 * Set dispMchntSt : 客户端显示状态. DISP_MCHNT_ST: VARCHAR(2) 
	 */
	public void setDispMchntSt(String dispMchntSt){
		this.dispMchntSt = dispMchntSt;	
	}
	
	/**
	 * Get dispMchntSt : 客户端显示状态. DISP_MCHNT_ST: VARCHAR(2) 
	 */
	public String getDispMchntSt(){
		return this.dispMchntSt;	
	}
	
	/**
	 * Set recAcc : 记录创建账户. REC_ACC: NVARCHAR2(30) 
	 */
	public void setRecAcc(String recAcc){
		this.recAcc = recAcc;	
	}
	
	/**
	 * Get recAcc : 记录创建账户. REC_ACC: NVARCHAR2(30) 
	 */
	public String getRecAcc(){
		return this.recAcc;	
	}
	
	/**
	 * Set recTime : 记录创建时间. REC_TIME: CHAR(14) 
	 */
	public void setRecTime(String recTime){
		this.recTime = recTime;	
	}
	
	/**
	 * Get recTime : 记录创建时间. REC_TIME: CHAR(14) 
	 */
	public String getRecTime(){
		return this.recTime;	
	}
	
	/**
	 * Set lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public void setLastUptTime(String lastUptTime){
		this.lastUptTime = lastUptTime;	
	}
	
	/**
	 * Get lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public String getLastUptTime(){
		return this.lastUptTime;	
	}
	
	/**
	 * Set lastUptAcc : 最后更新账户. LAST_UPT_ACC: NVARCHAR2(30) 
	 */
	public void setLastUptAcc(String lastUptAcc){
		this.lastUptAcc = lastUptAcc;	
	}
	
	/**
	 * Get lastUptAcc : 最后更新账户. LAST_UPT_ACC: NVARCHAR2(30) 
	 */
	public String getLastUptAcc(){
		return this.lastUptAcc;	
	}
	
	/**
	 * Set lastUptOrg : 最后更新机构. LAST_UPT_ORG: NVARCHAR2(30) 
	 */
	public void setLastUptOrg(String lastUptOrg){
		this.lastUptOrg = lastUptOrg;	
	}
	
	/**
	 * Get lastUptOrg : 最后更新机构. LAST_UPT_ORG: NVARCHAR2(30) 
	 */
	public String getLastUptOrg(){
		return this.lastUptOrg;	
	}
	
	/**
	 * Set lastCupOpr : 最近接口操作. LAST_CUP_OPR: VARCHAR2(40) 
	 */
	public void setLastCupOpr(String lastCupOpr){
		this.lastCupOpr = lastCupOpr;	
	}
	
	/**
	 * Get lastCupOpr : 最近接口操作. LAST_CUP_OPR: VARCHAR2(40) 
	 */
	public String getLastCupOpr(){
		return this.lastCupOpr;	
	}
	
	/**
	 * Set lastCupTime : 最近接口调用时间. LAST_CUP_TIME: CHAR(14) 
	 */
	public void setLastCupTime(String lastCupTime){
		this.lastCupTime = lastCupTime;	
	}
	
	/**
	 * Get lastCupTime : 最近接口调用时间. LAST_CUP_TIME: CHAR(14) 
	 */
	public String getLastCupTime(){
		return this.lastCupTime;	
	}
	
	/**
	 * Set lastCupResp : 最近接口返回信息. LAST_CUP_RESP: NVARCHAR2(200) 
	 */
	public void setLastCupResp(String lastCupResp){
		this.lastCupResp = lastCupResp;	
	}
	
	/**
	 * Get lastCupResp : 最近接口返回信息. LAST_CUP_RESP: NVARCHAR2(200) 
	 */
	public String getLastCupResp(){
		return this.lastCupResp;	
	}
	
	/**
	 * Set auditTime : 最近资质申请成功时间. AUDIT_TIME: CHAR(14) 
	 */
	public void setAuditTime(String auditTime){
		this.auditTime = auditTime;	
	}
	
	/**
	 * Get auditTime : 最近资质申请成功时间. AUDIT_TIME: CHAR(14) 
	 */
	public String getAuditTime(){
		return this.auditTime;	
	}
	
	/**
	 * Set beforeTime : 最近贷前查询成功时间. BEFORE_TIME: CHAR(14) 
	 */
	public void setBeforeTime(String beforeTime){
		this.beforeTime = beforeTime;	
	}
	
	/**
	 * Get beforeTime : 最近贷前查询成功时间. BEFORE_TIME: CHAR(14) 
	 */
	public String getBeforeTime(){
		return this.beforeTime;	
	}

	/**
	 * @return the mchntStDesc
	 */
	public String getMchntStDesc() {
		return mchntStDesc;
	}

	/**
	 * @param mchntStDesc the mchntStDesc to set
	 */
	public void setMchntStDesc(String mchntStDesc) {
		this.mchntStDesc = mchntStDesc;
	}

	/**
	 * @return the dispMchntStDesc
	 */
	public String getDispMchntStDesc() {
		return dispMchntStDesc;
	}

	/**
	 * @param dispMchntStDesc the dispMchntStDesc to set
	 */
	public void setDispMchntStDesc(String dispMchntStDesc) {
		this.dispMchntStDesc = dispMchntStDesc;
	}

	/**
	 * @return the mchntTpDesc
	 */
	public String getMchntTpDesc() {
		return mchntTpDesc;
	}

	/**
	 * @param mchntTpDesc the mchntTpDesc to set
	 */
	public void setMchntTpDesc(String mchntTpDesc) {
		this.mchntTpDesc = mchntTpDesc;
	}

	/**
	 * @return the mchntGrpDesc
	 */
	public String getMchntGrpDesc() {
		return mchntGrpDesc;
	}

	/**
	 * @param mchntGrpDesc the mchntGrpDesc to set
	 */
	public void setMchntGrpDesc(String mchntGrpDesc) {
		this.mchntGrpDesc = mchntGrpDesc;
	}

	/**
	 * @return the mchntEnType
	 */
	public String getMchntEnType() {
		return mchntEnType;
	}

	/**
	 * @param mchntEnType the mchntEnType to set
	 */
	public void setMchntEnType(String mchntEnType) {
		this.mchntEnType = mchntEnType;
	}

	/**
	 * @return the mchntDispName
	 */
	public String getMchntDispName() {
		return mchntDispName;
	}

	/**
	 * @param mchntDispName the mchntDispName to set
	 */
	public void setMchntDispName(String mchntDispName) {
		this.mchntDispName = mchntDispName;
	}

	/**
	 * @return the mchntContact
	 */
	public String getMchntContact() {
		return mchntContact;
	}

	/**
	 * @param mchntContact the mchntContact to set
	 */
	public void setMchntContact(String mchntContact) {
		this.mchntContact = mchntContact;
	}

	/**
	 * @return the mchntContactMobile
	 */
	public String getMchntContactMobile() {
		return mchntContactMobile;
	}

	/**
	 * @param mchntContactMobile the mchntContactMobile to set
	 */
	public void setMchntContactMobile(String mchntContactMobile) {
		this.mchntContactMobile = mchntContactMobile;
	}

	/**
	 * @return the mchntArtifMobile
	 */
	public String getMchntArtifMobile() {
		return mchntArtifMobile;
	}

	/**
	 * @param mchntArtifMobile the mchntArtifMobile to set
	 */
	public void setMchntArtifMobile(String mchntArtifMobile) {
		this.mchntArtifMobile = mchntArtifMobile;
	}

	/**
	 * @return the telephone
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * @param telephone the telephone to set
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * @return the mchntStartDate
	 */
	public String getMchntStartDate() {
		return mchntStartDate;
	}

	/**
	 * @param mchntStartDate the mchntStartDate to set
	 */
	public void setMchntStartDate(String mchntStartDate) {
		this.mchntStartDate = mchntStartDate;
	}

	/**
	 * @return the regCapital
	 */
	public Long getRegCapital() {
		return regCapital;
	}

	/**
	 * @param regCapital the regCapital to set
	 */
	public void setRegCapital(Long regCapital) {
		this.regCapital = regCapital;
	}

	/**
	 * @return the orgCode
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * @param orgCode the orgCode to set
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	/**
	 * @return the othBankName
	 */
	public String getOthBankName() {
		return othBankName;
	}

	/**
	 * @param othBankName the othBankName to set
	 */
	public void setOthBankName(String othBankName) {
		this.othBankName = othBankName;
	}

	/**
	 * @return the othCardNo
	 */
	public String getOthCardNo() {
		return othCardNo;
	}

	/**
	 * @param othCardNo the othCardNo to set
	 */
	public void setOthCardNo(String othCardNo) {
		this.othCardNo = othCardNo;
	}

	/**
	 * @return the cupMchntInfo
	 */
	public String getCupMchntInfo() {
		return cupMchntInfo;
	}

	/**
	 * @param cupMchntInfo the cupMchntInfo to set
	 */
	public void setCupMchntInfo(String cupMchntInfo) {
		this.cupMchntInfo = cupMchntInfo;
	}

	/**
	 * @return the customerCodeDesc
	 */
	public String getCustomerCodeDesc() {
		return customerCodeDesc;
	}

	/**
	 * @param customerCodeDesc the customerCodeDesc to set
	 */
	public void setCustomerCodeDesc(String customerCodeDesc) {
		this.customerCodeDesc = customerCodeDesc;
	}

	/**
	 * @return the mchntEnTypeDesc
	 */
	public String getMchntEnTypeDesc() {
		return mchntEnTypeDesc;
	}

	/**
	 * @param mchntEnTypeDesc the mchntEnTypeDesc to set
	 */
	public void setMchntEnTypeDesc(String mchntEnTypeDesc) {
		this.mchntEnTypeDesc = mchntEnTypeDesc;
	}

	/**
	 * @return the customerMobile
	 */
	public String getCustomerMobile() {
		return customerMobile;
	}

	/**
	 * @param customerMobile the customerMobile to set
	 */
	public void setCustomerMobile(String customerMobile) {
		this.customerMobile = customerMobile;
	}

	/**
	 * @return the lastCupOprDesc
	 */
	public String getLastCupOprDesc() {
		return lastCupOprDesc;
	}

	/**
	 * @param lastCupOprDesc the lastCupOprDesc to set
	 */
	public void setLastCupOprDesc(String lastCupOprDesc) {
		this.lastCupOprDesc = lastCupOprDesc;
	}

	/**
	 * @return the recAccDesc
	 */
	public String getRecAccDesc() {
		return recAccDesc;
	}

	/**
	 * @param recAccDesc the recAccDesc to set
	 */
	public void setRecAccDesc(String recAccDesc) {
		this.recAccDesc = recAccDesc;
	}
	
}