package com.jiuyv.hhc.model.mchnt ;

// Generated by AutoCode4J
/**
 * EntityBean: [New]商户信息附加表 : TBL_BIZ_MCHNT_PROP
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class BizMchntPropVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) */
	private Long mchntCode ;
	
	/** mchntEnType : 商户性质. MCHNT_EN_TYPE: CHAR(1) */
	private String mchntEnType ;
	
	/** mchntDispName : 商户名称. MCHNT_DISP_NAME: NVARCHAR2(200) */
	private String mchntDispName ;
	
	/** mchntContact : 商户联系人. MCHNT_CONTACT: NVARCHAR2(20) */
	private String mchntContact ;
	
	/** mchntContactMobile : 商户联系人移动电话. MCHNT_CONTACT_MOBILE: VARCHAR2(40) */
	private String mchntContactMobile ;
	
	/** mchntArtifMobile : 企业法人代表/个体商户主移动电话. MCHNT_ARTIF_MOBILE: VARCHAR2(40) */
	private String mchntArtifMobile ;
	
	/** telephone : 固定电话. TELEPHONE: VARCHAR2(40) */
	private String telephone ;
	
	/** mchntStartDate : 经营起始日期. MCHNT_START_DATE: CHAR(8) */
	private String mchntStartDate ;
	
	/** regCapital : 企业注册资本. REG_CAPITAL: NUMBER(12) */
	private Long regCapital ;
	
	/** orgCode : 企业组织结构代码证编号. ORG_CODE: VARCHAR2(20) */
	private String orgCode ;
	
	/** othBankName : 他行储蓄账户开户行. OTH_BANK_NAME: NVARCHAR2(80) */
	private String othBankName ;
	
	/** othCardNo : 他行储蓄账户卡号. OTH_CARD_NO: VARCHAR2(30) */
	private String othCardNo ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public BizMchntPropVo() {
		// Default Construtor
	}
	
	public BizMchntPropVo(Long mchntCode) {
		this.mchntCode = mchntCode;
	}
		
	// -- Setter And Getter
	/**
	 * Set mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public void setMchntCode(Long mchntCode){
		this.mchntCode = mchntCode;	
	}
	
	/**
	 * Get mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public Long getMchntCode(){
		return this.mchntCode;	
	}
	
	/**
	 * Set mchntEnType : 商户性质. MCHNT_EN_TYPE: CHAR(1) 
	 */
	public void setMchntEnType(String mchntEnType){
		this.mchntEnType = mchntEnType;	
	}
	
	/**
	 * Get mchntEnType : 商户性质. MCHNT_EN_TYPE: CHAR(1) 
	 */
	public String getMchntEnType(){
		return this.mchntEnType;	
	}
	
	/**
	 * Set mchntDispName : 商户名称. MCHNT_DISP_NAME: NVARCHAR2(200) 
	 */
	public void setMchntDispName(String mchntDispName){
		this.mchntDispName = mchntDispName;	
	}
	
	/**
	 * Get mchntDispName : 商户名称. MCHNT_DISP_NAME: NVARCHAR2(200) 
	 */
	public String getMchntDispName(){
		return this.mchntDispName;	
	}
	
	/**
	 * Set mchntContact : 商户联系人. MCHNT_CONTACT: NVARCHAR2(20) 
	 */
	public void setMchntContact(String mchntContact){
		this.mchntContact = mchntContact;	
	}
	
	/**
	 * Get mchntContact : 商户联系人. MCHNT_CONTACT: NVARCHAR2(20) 
	 */
	public String getMchntContact(){
		return this.mchntContact;	
	}
	
	/**
	 * Set mchntContactMobile : 商户联系人移动电话. MCHNT_CONTACT_MOBILE: VARCHAR2(40) 
	 */
	public void setMchntContactMobile(String mchntContactMobile){
		this.mchntContactMobile = mchntContactMobile;	
	}
	
	/**
	 * Get mchntContactMobile : 商户联系人移动电话. MCHNT_CONTACT_MOBILE: VARCHAR2(40) 
	 */
	public String getMchntContactMobile(){
		return this.mchntContactMobile;	
	}
	
	/**
	 * Set mchntArtifMobile : 企业法人代表/个体商户主移动电话. MCHNT_ARTIF_MOBILE: VARCHAR2(40) 
	 */
	public void setMchntArtifMobile(String mchntArtifMobile){
		this.mchntArtifMobile = mchntArtifMobile;	
	}
	
	/**
	 * Get mchntArtifMobile : 企业法人代表/个体商户主移动电话. MCHNT_ARTIF_MOBILE: VARCHAR2(40) 
	 */
	public String getMchntArtifMobile(){
		return this.mchntArtifMobile;	
	}
	
	/**
	 * Set telephone : 固定电话. TELEPHONE: VARCHAR2(40) 
	 */
	public void setTelephone(String telephone){
		this.telephone = telephone;	
	}
	
	/**
	 * Get telephone : 固定电话. TELEPHONE: VARCHAR2(40) 
	 */
	public String getTelephone(){
		return this.telephone;	
	}
	
	/**
	 * Set mchntStartDate : 经营起始日期. MCHNT_START_DATE: CHAR(8) 
	 */
	public void setMchntStartDate(String mchntStartDate){
		this.mchntStartDate = mchntStartDate;	
	}
	
	/**
	 * Get mchntStartDate : 经营起始日期. MCHNT_START_DATE: CHAR(8) 
	 */
	public String getMchntStartDate(){
		return this.mchntStartDate;	
	}
	
	/**
	 * Set regCapital : 企业注册资本. REG_CAPITAL: NUMBER(12) 
	 */
	public void setRegCapital(Long regCapital){
		this.regCapital = regCapital;	
	}
	
	/**
	 * Get regCapital : 企业注册资本. REG_CAPITAL: NUMBER(12) 
	 */
	public Long getRegCapital(){
		return this.regCapital;	
	}
	
	/**
	 * Set orgCode : 企业组织结构代码证编号. ORG_CODE: VARCHAR2(20) 
	 */
	public void setOrgCode(String orgCode){
		this.orgCode = orgCode;	
	}
	
	/**
	 * Get orgCode : 企业组织结构代码证编号. ORG_CODE: VARCHAR2(20) 
	 */
	public String getOrgCode(){
		return this.orgCode;	
	}
	
	/**
	 * Set othBankName : 他行储蓄账户开户行. OTH_BANK_NAME: NVARCHAR2(80) 
	 */
	public void setOthBankName(String othBankName){
		this.othBankName = othBankName;	
	}
	
	/**
	 * Get othBankName : 他行储蓄账户开户行. OTH_BANK_NAME: NVARCHAR2(80) 
	 */
	public String getOthBankName(){
		return this.othBankName;	
	}
	
	/**
	 * Set othCardNo : 他行储蓄账户卡号. OTH_CARD_NO: VARCHAR2(30) 
	 */
	public void setOthCardNo(String othCardNo){
		this.othCardNo = othCardNo;	
	}
	
	/**
	 * Get othCardNo : 他行储蓄账户卡号. OTH_CARD_NO: VARCHAR2(30) 
	 */
	public String getOthCardNo(){
		return this.othCardNo;	
	}
	
}