package com.jiuyv.hhc.model.information ;

// Generated by AutoCode4J
/**
 * EntityBean: 网站内容基本信息 : TBL_CM_ARTICLE
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class CmArticleVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** artSeq : 内部序号. ART_SEQ: NUMBER(18) */
	private Long artSeq ;
	
	/** version : VERSION. VERSION: NUMBER(10) */
	private Long version ;
	
	/** catSeq : 所属栏目. CAT_SEQ: NUMBER(18) */
	private Long catSeq ;
	
	/** artRemark : 摘要. ART_REMARK: VARCHAR2(300) */
	private String artRemark ;
	
	/** artContent : 内容. ART_CONTENT: CLOB */
	private String artContent ;
	
	/** artTitle : 标题. ART_TITLE: VARCHAR2(255) */
	private String artTitle ;
	
	/** artAuthor : 作者. ART_AUTHOR: VARCHAR2(255) */
	private String artAuthor ;
	
	/** artPubTime : 发布时间. ART_PUB_TIME: CHAR(14) */
	private String artPubTime ;
	
	/** artStatus : 文章状态. ART_STATUS: VARCHAR2(2) */
	private String artStatus ;
	
	/** isRecmd : 是否推荐. IS_RECMD: VARCHAR2(2) */
	private String isRecmd ;
	
	/** isTops : 是否置顶. IS_TOPS: VARCHAR2(2) */
	private String isTops ;
	
	/** metaWords : 页面关键词. META_WORDS: VARCHAR2(255) */
	private String metaWords ;
	
	/** metaDes : 页面描述. META_DES: VARCHAR2(255) */
	private String metaDes ;
	
	/** artHits : 点击数. ART_HITS: NUMBER(10) */
	private Long artHits ;
	
	/** artUrl : 静态地址. ART_URL: VARCHAR2(255) */
	private String artUrl ;
	
	/** artImg : 文章滚动图. ART_IMG: NVARCHAR2(255) */
	private String artImg;
	
	/** recCrtTime : 记录创建时间. REC_CRT_TIME: CHAR(14) */
	private String recCrtTime ;
	
	/** recCrtAcc : 记录创建用户帐号. REC_CRT_ACC: VARCHAR2(30) */
	private String recCrtAcc ;
	
	/** lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) */
	private String lastUptOrg ;
	
	/** lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) */
	private String lastUptTime ;
	
	/** lastUptAcc : 最后修改用户帐号. LAST_UPT_ACC: VARCHAR2(30) */
	private String lastUptAcc ;
	
	private String catName;
	
	private String isRecmdDesc;
	
	private String isTopsDesc;
	
	private String artStatusDesc;
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public CmArticleVo() {
		// Default Construtor
	}
	
	public CmArticleVo(Long artSeq) {
		this.artSeq = artSeq;
	}
		
	// -- Setter And Getter
	/**
	 * Set artSeq : 内部序号. ART_SEQ: NUMBER(18) 
	 */
	public void setArtSeq(Long artSeq){
		this.artSeq = artSeq;	
	}
	
	/**
	 * Get artSeq : 内部序号. ART_SEQ: NUMBER(18) 
	 */
	public Long getArtSeq(){
		return this.artSeq;	
	}
	
	/**
	 * Set version : VERSION. VERSION: NUMBER(10) 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: NUMBER(10) 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set catSeq : 所属栏目. CAT_SEQ: NUMBER(18) 
	 */
	public void setCatSeq(Long catSeq){
		this.catSeq = catSeq;	
	}
	
	/**
	 * Get catSeq : 所属栏目. CAT_SEQ: NUMBER(18) 
	 */
	public Long getCatSeq(){
		return this.catSeq;	
	}
	
	/**
	 * Set artRemark : 摘要. ART_REMARK: VARCHAR2(300) 
	 */
	public void setArtRemark(String artRemark){
		this.artRemark = artRemark;	
	}
	
	/**
	 * Get artRemark : 摘要. ART_REMARK: VARCHAR2(300) 
	 */
	public String getArtRemark(){
		return this.artRemark;	
	}
	
	/**
	 * Set artContent : 内容. ART_CONTENT: CLOB 
	 */
	public void setArtContent(String artContent){
		this.artContent = artContent;	
	}
	
	/**
	 * Get artContent : 内容. ART_CONTENT: CLOB 
	 */
	public String getArtContent(){
		return this.artContent;	
	}
	
	/**
	 * Set artTitle : 标题. ART_TITLE: VARCHAR2(255) 
	 */
	public void setArtTitle(String artTitle){
		this.artTitle = artTitle;	
	}
	
	/**
	 * Get artTitle : 标题. ART_TITLE: VARCHAR2(255) 
	 */
	public String getArtTitle(){
		return this.artTitle;	
	}
	
	/**
	 * Set artAuthor : 作者. ART_AUTHOR: VARCHAR2(255) 
	 */
	public void setArtAuthor(String artAuthor){
		this.artAuthor = artAuthor;	
	}
	
	/**
	 * Get artAuthor : 作者. ART_AUTHOR: VARCHAR2(255) 
	 */
	public String getArtAuthor(){
		return this.artAuthor;	
	}
	
	/**
	 * Set artPubTime : 发布时间. ART_PUB_TIME: CHAR(14) 
	 */
	public void setArtPubTime(String artPubTime){
		this.artPubTime = artPubTime;	
	}
	
	/**
	 * Get artPubTime : 发布时间. ART_PUB_TIME: CHAR(14) 
	 */
	public String getArtPubTime(){
		return this.artPubTime;	
	}
	
	/**
	 * Set artStatus : 文章状态. ART_STATUS: VARCHAR2(2) 
	 */
	public void setArtStatus(String artStatus){
		this.artStatus = artStatus;	
	}
	
	/**
	 * Get artStatus : 文章状态. ART_STATUS: VARCHAR2(2) 
	 */
	public String getArtStatus(){
		return this.artStatus;	
	}
	
	/**
	 * Set isRecmd : 是否推荐. IS_RECMD: VARCHAR2(2) 
	 */
	public void setIsRecmd(String isRecmd){
		this.isRecmd = isRecmd;	
	}
	
	/**
	 * Get isRecmd : 是否推荐. IS_RECMD: VARCHAR2(2) 
	 */
	public String getIsRecmd(){
		return this.isRecmd;	
	}
	
	/**
	 * Set isTops : 是否置顶. IS_TOPS: VARCHAR2(2) 
	 */
	public void setIsTops(String isTops){
		this.isTops = isTops;	
	}
	
	/**
	 * Get isTops : 是否置顶. IS_TOPS: VARCHAR2(2) 
	 */
	public String getIsTops(){
		return this.isTops;	
	}
	
	/**
	 * Set metaWords : 页面关键词. META_WORDS: VARCHAR2(255) 
	 */
	public void setMetaWords(String metaWords){
		this.metaWords = metaWords;	
	}
	
	/**
	 * Get metaWords : 页面关键词. META_WORDS: VARCHAR2(255) 
	 */
	public String getMetaWords(){
		return this.metaWords;	
	}
	
	/**
	 * Set metaDes : 页面描述. META_DES: VARCHAR2(255) 
	 */
	public void setMetaDes(String metaDes){
		this.metaDes = metaDes;	
	}
	
	/**
	 * Get metaDes : 页面描述. META_DES: VARCHAR2(255) 
	 */
	public String getMetaDes(){
		return this.metaDes;	
	}
	
	/**
	 * Set artHits : 点击数. ART_HITS: NUMBER(10) 
	 */
	public void setArtHits(Long artHits){
		this.artHits = artHits;	
	}
	
	/**
	 * Get artHits : 点击数. ART_HITS: NUMBER(10) 
	 */
	public Long getArtHits(){
		return this.artHits;	
	}
	
	/**
	 * Set artUrl : 静态地址. ART_URL: VARCHAR2(255) 
	 */
	public void setArtUrl(String artUrl){
		this.artUrl = artUrl;	
	}
	
	/**
	 * Get artUrl : 静态地址. ART_URL: VARCHAR2(255) 
	 */
	public String getArtUrl(){
		return this.artUrl;	
	}
	
	/**
	 * Set recCrtTime : 记录创建时间. REC_CRT_TIME: CHAR(14) 
	 */
	public void setRecCrtTime(String recCrtTime){
		this.recCrtTime = recCrtTime;	
	}
	
	/**
	 * Get recCrtTime : 记录创建时间. REC_CRT_TIME: CHAR(14) 
	 */
	public String getRecCrtTime(){
		return this.recCrtTime;	
	}
	
	/**
	 * Set recCrtAcc : 记录创建用户帐号. REC_CRT_ACC: VARCHAR2(30) 
	 */
	public void setRecCrtAcc(String recCrtAcc){
		this.recCrtAcc = recCrtAcc;	
	}
	
	/**
	 * Get recCrtAcc : 记录创建用户帐号. REC_CRT_ACC: VARCHAR2(30) 
	 */
	public String getRecCrtAcc(){
		return this.recCrtAcc;	
	}
	
	/**
	 * Set lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) 
	 */
	public void setLastUptOrg(String lastUptOrg){
		this.lastUptOrg = lastUptOrg;	
	}
	
	/**
	 * Get lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) 
	 */
	public String getLastUptOrg(){
		return this.lastUptOrg;	
	}
	
	/**
	 * Set lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public void setLastUptTime(String lastUptTime){
		this.lastUptTime = lastUptTime;	
	}
	
	/**
	 * Get lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public String getLastUptTime(){
		return this.lastUptTime;	
	}
	
	/**
	 * Set lastUptAcc : 最后修改用户帐号. LAST_UPT_ACC: VARCHAR2(30) 
	 */
	public void setLastUptAcc(String lastUptAcc){
		this.lastUptAcc = lastUptAcc;	
	}
	
	/**
	 * Get lastUptAcc : 最后修改用户帐号. LAST_UPT_ACC: VARCHAR2(30) 
	 */
	public String getLastUptAcc(){
		return this.lastUptAcc;	
	}

	public String getCatName() {
		return catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	public String getIsRecmdDesc() {
		return isRecmdDesc;
	}

	public void setIsRecmdDesc(String isRecmdDesc) {
		this.isRecmdDesc = isRecmdDesc;
	}

	public String getIsTopsDesc() {
		return isTopsDesc;
	}

	public void setIsTopsDesc(String isTopsDesc) {
		this.isTopsDesc = isTopsDesc;
	}

	public String getArtStatusDesc() {
		return artStatusDesc;
	}

	public void setArtStatusDesc(String artStatusDesc) {
		this.artStatusDesc = artStatusDesc;
	}

	public String getArtImg() {
		return artImg;
	}

	public void setArtImg(String artImg) {
		this.artImg = artImg;
	}
	
}