package com.jiuyv.hhc.model.information ;

// Generated by AutoCode4J
/**
 * EntityBean: 网站栏目分类 : TBL_CM_ART_CAT
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class CmArtCatVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** catSeq : 内部序号. CAT_SEQ: NUMBER(18) */
	private Long catSeq ;
	
	/** version : VERSION. VERSION: NUMBER(10) */
	private Long version ;
	
	/** catParent : 父节点. CAT_PARENT: NUMBER(18) */
	private Long catParent ;
	
	/** catName : 名称. CAT_NAME: VARCHAR2(255) */
	private String catName ;

	/** catTitle : 栏目副标题. CAT_TITLE: VARCHAR2(255) */
	private String catTitle;
	
	/** catCode : 栏目代码. CAT_CODE: VARCHAR2(100) */
	private String catCode ;
	
	/** catLogo : 栏目LOGO. CAT_LOGO: VARCHAR2(255) */
	private String catLogo ;
	
	/** catBanner : 栏目BAN. CAT_BANNER: VARCHAR2(255) */
	private String catBanner ;
	
	/** catSort : 排序. CAT_SORT: NUMBER(10) */
	private Long catSort ;
	
	/** isVisible : 是否显示. IS_VISIBLE: VARCHAR2(1) */
	private String isVisible ;
	
	/** catStatus : 栏目状态. CAT_STATUS: VARCHAR2(2) */
	private String catStatus ;
	
	/** recCrtTime : 记录创建时间. REC_CRT_TIME: CHAR(14) */
	private String recCrtTime ;
	
	/** recCrtAcc : 记录创建用户帐号. REC_CRT_ACC: VARCHAR2(30) */
	private String recCrtAcc ;
	
	/** lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) */
	private String lastUptOrg ;
	
	/** lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) */
	private String lastUptTime ;
	
	/** lastUptAcc : 最后修改用户帐号. LAST_UPT_ACC: VARCHAR2(30) */
	private String lastUptAcc ;
	
	private String catStatusDesc;
	
	private String parentCatName;
	
	private String isVisibleDesc;
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public CmArtCatVo() {
		// Default Construtor
	}
	
	public CmArtCatVo(Long catSeq) {
		this.catSeq = catSeq;
	}
		
	// -- Setter And Getter
	/**
	 * Set catSeq : 内部序号. CAT_SEQ: NUMBER(18) 
	 */
	public void setCatSeq(Long catSeq){
		this.catSeq = catSeq;	
	}
	
	/**
	 * Get catSeq : 内部序号. CAT_SEQ: NUMBER(18) 
	 */
	public Long getCatSeq(){
		return this.catSeq;	
	}
	
	/**
	 * Set version : VERSION. VERSION: NUMBER(10) 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: NUMBER(10) 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set catParent : 父节点. CAT_PARENT: NUMBER(18) 
	 */
	public void setCatParent(Long catParent){
		this.catParent = catParent;	
	}
	
	/**
	 * Get catParent : 父节点. CAT_PARENT: NUMBER(18) 
	 */
	public Long getCatParent(){
		return this.catParent;	
	}
	
	/**
	 * Set catName : 名称. CAT_NAME: VARCHAR2(255) 
	 */
	public void setCatName(String catName){
		this.catName = catName;	
	}
	
	/**
	 * Get catName : 名称. CAT_NAME: VARCHAR2(255) 
	 */
	public String getCatName(){
		return this.catName;	
	}
	
	/**
	 * Set catCode : 栏目代码. CAT_CODE: VARCHAR2(100) 
	 */
	public void setCatCode(String catCode){
		this.catCode = catCode;	
	}
	
	/**
	 * Get catCode : 栏目代码. CAT_CODE: VARCHAR2(100) 
	 */
	public String getCatCode(){
		return this.catCode;	
	}
	
	/**
	 * Set catLogo : 栏目LOGO. CAT_LOGO: VARCHAR2(255) 
	 */
	public void setCatLogo(String catLogo){
		this.catLogo = catLogo;	
	}
	
	/**
	 * Get catLogo : 栏目LOGO. CAT_LOGO: VARCHAR2(255) 
	 */
	public String getCatLogo(){
		return this.catLogo;	
	}
	
	/**
	 * Set catBanner : 栏目BAN. CAT_BANNER: VARCHAR2(255) 
	 */
	public void setCatBanner(String catBanner){
		this.catBanner = catBanner;	
	}
	
	/**
	 * Get catBanner : 栏目BAN. CAT_BANNER: VARCHAR2(255) 
	 */
	public String getCatBanner(){
		return this.catBanner;	
	}
	
	/**
	 * Set catSort : 排序. CAT_SORT: NUMBER(10) 
	 */
	public void setCatSort(Long catSort){
		this.catSort = catSort;	
	}
	
	/**
	 * Get catSort : 排序. CAT_SORT: NUMBER(10) 
	 */
	public Long getCatSort(){
		return this.catSort;	
	}
	
	/**
	 * Set isVisible : 是否显示. IS_VISIBLE: VARCHAR2(1) 
	 */
	public void setIsVisible(String isVisible){
		this.isVisible = isVisible;	
	}
	
	/**
	 * Get isVisible : 是否显示. IS_VISIBLE: VARCHAR2(1) 
	 */
	public String getIsVisible(){
		return this.isVisible;	
	}
	
	/**
	 * Set catStatus : 栏目状态. CAT_STATUS: VARCHAR2(2) 
	 */
	public void setCatStatus(String catStatus){
		this.catStatus = catStatus;	
	}
	
	/**
	 * Get catStatus : 栏目状态. CAT_STATUS: VARCHAR2(2) 
	 */
	public String getCatStatus(){
		return this.catStatus;	
	}
	
	/**
	 * Set recCrtTime : 记录创建时间. REC_CRT_TIME: CHAR(14) 
	 */
	public void setRecCrtTime(String recCrtTime){
		this.recCrtTime = recCrtTime;	
	}
	
	/**
	 * Get recCrtTime : 记录创建时间. REC_CRT_TIME: CHAR(14) 
	 */
	public String getRecCrtTime(){
		return this.recCrtTime;	
	}
	
	/**
	 * Set recCrtAcc : 记录创建用户帐号. REC_CRT_ACC: VARCHAR2(30) 
	 */
	public void setRecCrtAcc(String recCrtAcc){
		this.recCrtAcc = recCrtAcc;	
	}
	
	/**
	 * Get recCrtAcc : 记录创建用户帐号. REC_CRT_ACC: VARCHAR2(30) 
	 */
	public String getRecCrtAcc(){
		return this.recCrtAcc;	
	}
	
	/**
	 * Set lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) 
	 */
	public void setLastUptOrg(String lastUptOrg){
		this.lastUptOrg = lastUptOrg;	
	}
	
	/**
	 * Get lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) 
	 */
	public String getLastUptOrg(){
		return this.lastUptOrg;	
	}
	
	/**
	 * Set lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public void setLastUptTime(String lastUptTime){
		this.lastUptTime = lastUptTime;	
	}
	
	/**
	 * Get lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public String getLastUptTime(){
		return this.lastUptTime;	
	}
	
	/**
	 * Set lastUptAcc : 最后修改用户帐号. LAST_UPT_ACC: VARCHAR2(30) 
	 */
	public void setLastUptAcc(String lastUptAcc){
		this.lastUptAcc = lastUptAcc;	
	}
	
	/**
	 * Get lastUptAcc : 最后修改用户帐号. LAST_UPT_ACC: VARCHAR2(30) 
	 */
	public String getLastUptAcc(){
		return this.lastUptAcc;	
	}
	
		public String getCatStatusDesc() {
		return catStatusDesc;
	}

	public void setCatStatusDesc(String catStatusDesc) {
		this.catStatusDesc = catStatusDesc;
	}

	public String getParentCatName() {
		return parentCatName;
	}

	public void setParentCatName(String parentCatName) {
		this.parentCatName = parentCatName;
	}

	public String getIsVisibleDesc() {
		return isVisibleDesc;
	}

	public void setIsVisibleDesc(String isVisibleDesc) {
		this.isVisibleDesc = isVisibleDesc;
	}

	public String getCatTitle() {
		return catTitle;
	}

	public void setCatTitle(String catTitle) {
		this.catTitle = catTitle;
	}
	
}