package com.jiuyv.hhc.model.information ;

// Generated by AutoCode4J
/**
 * EntityBean: 友情链接 : TBL_CM_FRD_LINK
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class CmFrdLinkVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** frdSeq : 内部序号. FRD_SEQ: NUMBER(18) */
	private Long frdSeq ;
	
	/** version : VERSION. VERSION: NUMBER(10) */
	private Long version ;
	
	/** frdName : 名称. FRD_NAME: VARCHAR2(255)  */
	private String frdName ;
	
	/** frdType : 类型. FRD_TYPE: VARCHAR2(2) */
	private String frdType ;
	
	/** frdStyle : 样式. FRD_STYLE: VARCHAR2(255) */
	private String frdStyle ;
	
	/** frdLogo : 图片. FRD_LOGO: VARCHAR2(255)  */
	private String frdLogo ;
	
	/** frdLogoHover : 图片浮动. FRD_LOGO_HOVER: VARCHAR2(255)  */
	private String frdLogoHover ;
	
	/** frdSort : 排序. FRD_SORT: NUMBER(10) */
	private Long frdSort ;
	
	/** frdUrl : 链接地址. FRD_URL: VARCHAR2(255)  */
	private String frdUrl ;
	
	/** isVisible : 是否显示. IS_VISIBLE: VARCHAR2(2) */
	private String isVisible ;
	
	/** frdStatus : 状态. FRD_STATUS: VARCHAR2(2) */
	private String frdStatus ;
	
	/** recCrtTime : 记录创建时间. REC_CRT_TIME: CHAR(14) */
	private String recCrtTime ;
	
	/** recCrtAcc : 记录创建用户帐号. REC_CRT_ACC: VARCHAR2(30) */
	private String recCrtAcc ;
	
	/** lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) */
	private String lastUptOrg ;
	
	/** lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) */
	private String lastUptTime ;
	
	/** lastUptAcc : 最后修改用户帐号. LAST_UPT_ACC: VARCHAR2(30) */
	private String lastUptAcc ;
	
	private String isVisibleDesc;
	
	private String frdStatusDesc;
	
	private String frdTypeDesc;
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public CmFrdLinkVo() {
		// Default Construtor
	}
	
	public CmFrdLinkVo(Long frdSeq) {
		this.frdSeq = frdSeq;
	}
		
	// -- Setter And Getter
	/**
	 * Set frdSeq : 内部序号. FRD_SEQ: NUMBER(18) 
	 */
	public void setFrdSeq(Long frdSeq){
		this.frdSeq = frdSeq;	
	}
	
	/**
	 * Get frdSeq : 内部序号. FRD_SEQ: NUMBER(18) 
	 */
	public Long getFrdSeq(){
		return this.frdSeq;	
	}
	
	/**
	 * Set version : VERSION. VERSION: NUMBER(10) 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: NUMBER(10) 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set frdName : 名称. FRD_NAME: VARCHAR2(255)  
	 */
	public void setFrdName(String frdName){
		this.frdName = frdName;	
	}
	
	/**
	 * Get frdName : 名称. FRD_NAME: VARCHAR2(255)  
	 */
	public String getFrdName(){
		return this.frdName;	
	}
	
	/**
	 * Set frdType : 类型. FRD_TYPE: VARCHAR2(2) 
	 */
	public void setFrdType(String frdType){
		this.frdType = frdType;	
	}
	
	/**
	 * Get frdType : 类型. FRD_TYPE: VARCHAR2(2) 
	 */
	public String getFrdType(){
		return this.frdType;	
	}
	
	/**
	 * Set frdStyle : 样式. FRD_STYLE: VARCHAR2(255) 
	 */
	public void setFrdStyle(String frdStyle){
		this.frdStyle = frdStyle;	
	}
	
	/**
	 * Get frdStyle : 样式. FRD_STYLE: VARCHAR2(255) 
	 */
	public String getFrdStyle(){
		return this.frdStyle;	
	}
	
	/**
	 * Set frdLogo : 图片. FRD_LOGO: VARCHAR2(255)  
	 */
	public void setFrdLogo(String frdLogo){
		this.frdLogo = frdLogo;	
	}
	
	/**
	 * Get frdLogo : 图片. FRD_LOGO: VARCHAR2(255)  
	 */
	public String getFrdLogo(){
		return this.frdLogo;	
	}
	
	/**
	 * Set frdSort : 排序. FRD_SORT: NUMBER(10) 
	 */
	public void setFrdSort(Long frdSort){
		this.frdSort = frdSort;	
	}
	
	/**
	 * Get frdSort : 排序. FRD_SORT: NUMBER(10) 
	 */
	public Long getFrdSort(){
		return this.frdSort;	
	}
	
	/**
	 * Set frdUrl : 链接地址. FRD_URL: VARCHAR2(255)  
	 */
	public void setFrdUrl(String frdUrl){
		this.frdUrl = frdUrl;	
	}
	
	/**
	 * Get frdUrl : 链接地址. FRD_URL: VARCHAR2(255)  
	 */
	public String getFrdUrl(){
		return this.frdUrl;	
	}
	
	/**
	 * Set isVisible : 是否显示. IS_VISIBLE: VARCHAR2(2) 
	 */
	public void setIsVisible(String isVisible){
		this.isVisible = isVisible;	
	}
	
	/**
	 * Get isVisible : 是否显示. IS_VISIBLE: VARCHAR2(2) 
	 */
	public String getIsVisible(){
		return this.isVisible;	
	}
	
	/**
	 * Set frdStatus : 状态. FRD_STATUS: VARCHAR2(2) 
	 */
	public void setFrdStatus(String frdStatus){
		this.frdStatus = frdStatus;	
	}
	
	/**
	 * Get frdStatus : 状态. FRD_STATUS: VARCHAR2(2) 
	 */
	public String getFrdStatus(){
		return this.frdStatus;	
	}
	
	/**
	 * Set recCrtTime : 记录创建时间. REC_CRT_TIME: CHAR(14) 
	 */
	public void setRecCrtTime(String recCrtTime){
		this.recCrtTime = recCrtTime;	
	}
	
	/**
	 * Get recCrtTime : 记录创建时间. REC_CRT_TIME: CHAR(14) 
	 */
	public String getRecCrtTime(){
		return this.recCrtTime;	
	}
	
	/**
	 * Set recCrtAcc : 记录创建用户帐号. REC_CRT_ACC: VARCHAR2(30) 
	 */
	public void setRecCrtAcc(String recCrtAcc){
		this.recCrtAcc = recCrtAcc;	
	}
	
	/**
	 * Get recCrtAcc : 记录创建用户帐号. REC_CRT_ACC: VARCHAR2(30) 
	 */
	public String getRecCrtAcc(){
		return this.recCrtAcc;	
	}
	
	/**
	 * Set lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) 
	 */
	public void setLastUptOrg(String lastUptOrg){
		this.lastUptOrg = lastUptOrg;	
	}
	
	/**
	 * Get lastUptOrg : 最后更新机构. LAST_UPT_ORG: VARCHAR2(30) 
	 */
	public String getLastUptOrg(){
		return this.lastUptOrg;	
	}
	
	/**
	 * Set lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public void setLastUptTime(String lastUptTime){
		this.lastUptTime = lastUptTime;	
	}
	
	/**
	 * Get lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public String getLastUptTime(){
		return this.lastUptTime;	
	}
	
	/**
	 * Set lastUptAcc : 最后修改用户帐号. LAST_UPT_ACC: VARCHAR2(30) 
	 */
	public void setLastUptAcc(String lastUptAcc){
		this.lastUptAcc = lastUptAcc;	
	}
	
	/**
	 * Get lastUptAcc : 最后修改用户帐号. LAST_UPT_ACC: VARCHAR2(30) 
	 */
	public String getLastUptAcc(){
		return this.lastUptAcc;	
	}

	public String getFrdLogoHover() {
		return frdLogoHover;
	}

	public void setFrdLogoHover(String frdLogoHover) {
		this.frdLogoHover = frdLogoHover;
	}

	public String getIsVisibleDesc() {
		return isVisibleDesc;
	}

	public void setIsVisibleDesc(String isVisibleDesc) {
		this.isVisibleDesc = isVisibleDesc;
	}

	public String getFrdStatusDesc() {
		return frdStatusDesc;
	}

	public void setFrdStatusDesc(String frdStatusDesc) {
		this.frdStatusDesc = frdStatusDesc;
	}

	public String getFrdTypeDesc() {
		return frdTypeDesc;
	}

	public void setFrdTypeDesc(String frdTypeDesc) {
		this.frdTypeDesc = frdTypeDesc;
	}
	
}