package com.jiuyv.hhc.model.security ;

// Generated by AutoCode4J
/**
 * EntityBean: 控制台操作流水表 : TBL_SYS_OPRLOG
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class SysOprlogVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** oprNo : 操作流水号. OPR_NO: int */
	private Long oprNo ;
	
	/** stlmDate : 清算日期. STLM_DATE: char(8) */
	private String stlmDate ;
	
	/** resId : 资源id. RES_ID: varchar(40) */
	private String resId ;
	
	/** resZh : 资源中文. RES_ZH: varchar(60) */
	private String resZh ;
	
	/** oprOrgCode : 操作人所属机构. OPR_ORG_CODE: varchar(30) */
	private String oprOrgCode ;
	
	/** oprUserId : 操作人id. OPR_USER_ID: int */
	private Long oprUserId ;
	
	/** oprLoginId : 操作人登陆id. OPR_LOGIN_ID: varchar(10) */
	private String oprLoginId ;
	
	/** oprUrl : 操作URL. OPR_URL: varchar(1024) */
	private String oprUrl ;
	
	/** oprSysCode : 操作系统代码. OPR_SYS_CODE: varchar(6) */
	private String oprSysCode ;
	
	/** oprTime : 操作时间. OPR_TIME: char(14) */
	private String oprTime ;
	
	/** oprIp : 操作方ip. OPR_IP: varchar(50) */
	private String oprIp ;
	
	/** oprSuccess : 操作是否成功. OPR_SUCCESS: varchar(4) */
	private String oprSuccess ;
	
	/** oprResultInfo : 操作结果. OPR_RESULT_INFO: text */
	private String oprResultInfo ;
	
	/** oprRemark : OPR_REMARK. OPR_REMARK: text */
	private String oprRemark ;
	
	// -- Extend --
	/** 操作人姓名 */
	private String oprUserName;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public SysOprlogVo() {
		// Default Construtor
	}
	
	public SysOprlogVo(Long oprNo) {
		this.oprNo = oprNo;
	}
		
	// -- Setter And Getter
	/**
	 * Set oprNo : 操作流水号. OPR_NO: int 
	 */
	public void setOprNo(Long oprNo){
		this.oprNo = oprNo;	
	}
	
	/**
	 * Get oprNo : 操作流水号. OPR_NO: int 
	 */
	public Long getOprNo(){
		return this.oprNo;	
	}
	
	/**
	 * Set stlmDate : 清算日期. STLM_DATE: char(8) 
	 */
	public void setStlmDate(String stlmDate){
		this.stlmDate = stlmDate;	
	}
	
	/**
	 * Get stlmDate : 清算日期. STLM_DATE: char(8) 
	 */
	public String getStlmDate(){
		return this.stlmDate;	
	}
	
	/**
	 * Set resId : 资源id. RES_ID: varchar(40) 
	 */
	public void setResId(String resId){
		this.resId = resId;	
	}
	
	/**
	 * Get resId : 资源id. RES_ID: varchar(40) 
	 */
	public String getResId(){
		return this.resId;	
	}
	
	/**
	 * Set resZh : 资源中文. RES_ZH: varchar(60) 
	 */
	public void setResZh(String resZh){
		this.resZh = resZh;	
	}
	
	/**
	 * Get resZh : 资源中文. RES_ZH: varchar(60) 
	 */
	public String getResZh(){
		return this.resZh;	
	}
	
	/**
	 * Set oprOrgCode : 操作人所属机构. OPR_ORG_CODE: varchar(30) 
	 */
	public void setOprOrgCode(String oprOrgCode){
		this.oprOrgCode = oprOrgCode;	
	}
	
	/**
	 * Get oprOrgCode : 操作人所属机构. OPR_ORG_CODE: varchar(30) 
	 */
	public String getOprOrgCode(){
		return this.oprOrgCode;	
	}
	
	/**
	 * Set oprUserId : 操作人id. OPR_USER_ID: int 
	 */
	public void setOprUserId(Long oprUserId){
		this.oprUserId = oprUserId;	
	}
	
	/**
	 * Get oprUserId : 操作人id. OPR_USER_ID: int 
	 */
	public Long getOprUserId(){
		return this.oprUserId;	
	}
	
	/**
	 * Set oprLoginId : 操作人登陆id. OPR_LOGIN_ID: varchar(10) 
	 */
	public void setOprLoginId(String oprLoginId){
		this.oprLoginId = oprLoginId;	
	}
	
	/**
	 * Get oprLoginId : 操作人登陆id. OPR_LOGIN_ID: varchar(10) 
	 */
	public String getOprLoginId(){
		return this.oprLoginId;	
	}
	
	/**
	 * Set oprUrl : 操作URL. OPR_URL: varchar(1024) 
	 */
	public void setOprUrl(String oprUrl){
		this.oprUrl = oprUrl;	
	}
	
	/**
	 * Get oprUrl : 操作URL. OPR_URL: varchar(1024) 
	 */
	public String getOprUrl(){
		return this.oprUrl;	
	}
	
	/**
	 * Set oprSysCode : 操作系统代码. OPR_SYS_CODE: varchar(6) 
	 */
	public void setOprSysCode(String oprSysCode){
		this.oprSysCode = oprSysCode;	
	}
	
	/**
	 * Get oprSysCode : 操作系统代码. OPR_SYS_CODE: varchar(6) 
	 */
	public String getOprSysCode(){
		return this.oprSysCode;	
	}
	
	/**
	 * Set oprTime : 操作时间. OPR_TIME: char(14) 
	 */
	public void setOprTime(String oprTime){
		this.oprTime = oprTime;	
	}
	
	/**
	 * Get oprTime : 操作时间. OPR_TIME: char(14) 
	 */
	public String getOprTime(){
		return this.oprTime;	
	}
	
	/**
	 * Set oprIp : 操作方ip. OPR_IP: varchar(50) 
	 */
	public void setOprIp(String oprIp){
		this.oprIp = oprIp;	
	}
	
	/**
	 * Get oprIp : 操作方ip. OPR_IP: varchar(50) 
	 */
	public String getOprIp(){
		return this.oprIp;	
	}
	
	/**
	 * Set oprSuccess : 操作是否成功. OPR_SUCCESS: varchar(4) 
	 */
	public void setOprSuccess(String oprSuccess){
		this.oprSuccess = oprSuccess;	
	}
	
	/**
	 * Get oprSuccess : 操作是否成功. OPR_SUCCESS: varchar(4) 
	 */
	public String getOprSuccess(){
		return this.oprSuccess;	
	}
	
	/**
	 * Set oprResultInfo : 操作结果. OPR_RESULT_INFO: text 
	 */
	public void setOprResultInfo(String oprResultInfo){
		this.oprResultInfo = oprResultInfo;	
	}
	
	/**
	 * Get oprResultInfo : 操作结果. OPR_RESULT_INFO: text 
	 */
	public String getOprResultInfo(){
		return this.oprResultInfo;	
	}
	
	/**
	 * Set oprRemark : OPR_REMARK. OPR_REMARK: text 
	 */
	public void setOprRemark(String oprRemark){
		this.oprRemark = oprRemark;	
	}
	
	/**
	 * Get oprRemark : OPR_REMARK. OPR_REMARK: text 
	 */
	public String getOprRemark(){
		return this.oprRemark;	
	}

	public String getOprUserName() {
		return oprUserName;
	}

	public void setOprUserName(String oprUserName) {
		this.oprUserName = oprUserName;
	}
	
}