package com.jiuyv.hhc.model.security ;

// Generated by AutoCode4J
/**
 * EntityBean: 控制台资源表 : TBL_SYS_RESOURCE
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class SysResourceVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** resId : 资源ID. RES_ID: varchar(40) */
	private String resId ;
	
	/** fatherId : 上级ID. FATHER_ID: varchar(40) */
	private String fatherId ;
	
	/** resZh : 资源中文名. RES_ZH: varchar(60) */
	private String resZh ;
	
	/** resEn : 资源英文名. RES_EN: varchar(60) */
	private String resEn ;
	
	/** sysCode : 系统代码. SYS_CODE: varchar(6) */
	private String sysCode ;
	
	/** resUrl : 资源URL. RES_URL: varchar(100) */
	private String resUrl ;
	
	/** showType : 资源类型. SHOW_TYPE: char(1) */
	private String showType ;
	
	/** orderNum : 排序号. ORDER_NUM: varchar(5) */
	private String orderNum ;
	
	/** logFlag : 是否记日志. LOG_FLAG: char(1) */
	private String logFlag ;
	
	/** remarks : 备注. REMARKS: varchar(200) */
	private String remarks ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public SysResourceVo() {
		// Default Construtor
	}
	
	public SysResourceVo(String resId) {
		this.resId = resId;
	}
		
	// -- Setter And Getter
	/**
	 * Set resId : 资源ID. RES_ID: varchar(40) 
	 */
	public void setResId(String resId){
		this.resId = resId;	
	}
	
	/**
	 * Get resId : 资源ID. RES_ID: varchar(40) 
	 */
	public String getResId(){
		return this.resId;	
	}
	
	/**
	 * Set fatherId : 上级ID. FATHER_ID: varchar(40) 
	 */
	public void setFatherId(String fatherId){
		this.fatherId = fatherId;	
	}
	
	/**
	 * Get fatherId : 上级ID. FATHER_ID: varchar(40) 
	 */
	public String getFatherId(){
		return this.fatherId;	
	}
	
	/**
	 * Set resZh : 资源中文名. RES_ZH: varchar(60) 
	 */
	public void setResZh(String resZh){
		this.resZh = resZh;	
	}
	
	/**
	 * Get resZh : 资源中文名. RES_ZH: varchar(60) 
	 */
	public String getResZh(){
		return this.resZh;	
	}
	
	/**
	 * Set resEn : 资源英文名. RES_EN: varchar(60) 
	 */
	public void setResEn(String resEn){
		this.resEn = resEn;	
	}
	
	/**
	 * Get resEn : 资源英文名. RES_EN: varchar(60) 
	 */
	public String getResEn(){
		return this.resEn;	
	}
	
	/**
	 * Set sysCode : 系统代码. SYS_CODE: varchar(6) 
	 */
	public void setSysCode(String sysCode){
		this.sysCode = sysCode;	
	}
	
	/**
	 * Get sysCode : 系统代码. SYS_CODE: varchar(6) 
	 */
	public String getSysCode(){
		return this.sysCode;	
	}
	
	/**
	 * Set resUrl : 资源URL. RES_URL: varchar(100) 
	 */
	public void setResUrl(String resUrl){
		this.resUrl = resUrl;	
	}
	
	/**
	 * Get resUrl : 资源URL. RES_URL: varchar(100) 
	 */
	public String getResUrl(){
		return this.resUrl;	
	}
	
	/**
	 * Set showType : 资源类型. SHOW_TYPE: char(1) 
	 */
	public void setShowType(String showType){
		this.showType = showType;	
	}
	
	/**
	 * Get showType : 资源类型. SHOW_TYPE: char(1) 
	 */
	public String getShowType(){
		return this.showType;	
	}
	
	/**
	 * Set orderNum : 排序号. ORDER_NUM: varchar(5) 
	 */
	public void setOrderNum(String orderNum){
		this.orderNum = orderNum;	
	}
	
	/**
	 * Get orderNum : 排序号. ORDER_NUM: varchar(5) 
	 */
	public String getOrderNum(){
		return this.orderNum;	
	}
	
	/**
	 * Set logFlag : 是否记日志. LOG_FLAG: char(1) 
	 */
	public void setLogFlag(String logFlag){
		this.logFlag = logFlag;	
	}
	
	/**
	 * Get logFlag : 是否记日志. LOG_FLAG: char(1) 
	 */
	public String getLogFlag(){
		return this.logFlag;	
	}
	
	/**
	 * Set remarks : 备注. REMARKS: varchar(200) 
	 */
	public void setRemarks(String remarks){
		this.remarks = remarks;	
	}
	
	/**
	 * Get remarks : 备注. REMARKS: varchar(200) 
	 */
	public String getRemarks(){
		return this.remarks;	
	}
	
}