package com.jiuyv.hhc.model.security ;

// Generated by AutoCode4J
/**
 * EntityBean: 控制台角色权限关系表 : TBL_SYS_ROLE_RES
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class SysRoleResVo implements java.io.Serializable,ResBean {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** roleId : 角色ID. ROLE_ID: int */
	private Long roleId ;
	
	/** resId : 资源ID. RES_ID: varchar(40) */
	private String resId ;
	
	// -- Extend --
	/** orderNum : 排序号. ORDER_NUM: varchar(5) */
	private String orderNum ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public SysRoleResVo() {
		// Default Construtor
	}
	
	public SysRoleResVo(Long roleId, String resId) {
		this.roleId = roleId;
		this.resId = resId;
	}
		
	// -- Setter And Getter
	/**
	 * Set roleId : 角色ID. ROLE_ID: int 
	 */
	public void setRoleId(Long roleId){
		this.roleId = roleId;	
	}
	
	/**
	 * Get roleId : 角色ID. ROLE_ID: int 
	 */
	public Long getRoleId(){
		return this.roleId;	
	}
	
	/**
	 * Set resId : 资源ID. RES_ID: varchar(40) 
	 */
	public void setResId(String resId){
		this.resId = resId;	
	}
	
	/**
	 * Get resId : 资源ID. RES_ID: varchar(40) 
	 */
	public String getResId(){
		return this.resId;	
	}

	/**
	 * 获取 orderNum : 排序号.
	 *
	 * @return the orderNum
	 */
	public String getOrderNum() {
		return orderNum;
	}

	/**
	 * 设置 orderNum : 排序号.
	 *
	 * @param orderNum the orderNum to set
	 */
	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}
	
}