package com.jiuyv.hhc.model.security ;

// Generated by AutoCode4J
/**
 * EntityBean: 用户角色关系表 : TBL_SYS_USER_ROLE
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class SysUserRoleVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** userId : 用户id. USER_ID: int */
	private Long userId ;
	
	/** roleId : 角色ID. ROLE_ID: int */
	private Long roleId ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public SysUserRoleVo() {
		// Default Construtor
	}
	
	public SysUserRoleVo(Long userId, Long roleId) {
		this.userId = userId;
		this.roleId = roleId;
	}
		
	// -- Setter And Getter
	/**
	 * Set userId : 用户id. USER_ID: int 
	 */
	public void setUserId(Long userId){
		this.userId = userId;	
	}
	
	/**
	 * Get userId : 用户id. USER_ID: int 
	 */
	public Long getUserId(){
		return this.userId;	
	}
	
	/**
	 * Set roleId : 角色ID. ROLE_ID: int 
	 */
	public void setRoleId(Long roleId){
		this.roleId = roleId;	
	}
	
	/**
	 * Get roleId : 角色ID. ROLE_ID: int 
	 */
	public Long getRoleId(){
		return this.roleId;	
	}
	
}