package com.jiuyv.hhc.model.security ;

// Generated by AutoCode4J
/**
 * EntityBean: 控制台用户表 : TBL_SYS_USER
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class SysUserVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** userId : 用户id. USER_ID: int */
	private Long userId ;
	
	/** version : VERSION. VERSION: int */
	private Long version ;
	
	/** loginId : 登陆帐户. LOGIN_ID: varchar(10) */
	private String loginId ;
	
	/** loginPasswd : 登陆密码. LOGIN_PASSWD: varchar(64) */
	private String loginPasswd ;
	
	/** userName : 用户姓名. USER_NAME: varchar(20) */
	private String userName ;
	
	/** orgCode : 用户机构. ORG_CODE: varchar(30) */
	private String orgCode ;
	
	/** userPhone : 电话号码. USER_PHONE: varchar(20) */
	private String userPhone ;
	
	/** userEmail : EMAIL. USER_EMAIL: varchar(50) */
	private String userEmail ;
	
	/** userAddr : 地址. USER_ADDR: varchar(200) */
	private String userAddr ;
	
	/** crdType : 证件类型. CRD_TYPE: varchar(2) */
	private String crdType ;
	
	/** crdNo : 证件号码. CRD_NO: varchar(30) */
	private String crdNo ;
	
	/** regTime : 注册时间. REG_TIME: char(14) */
	private String regTime ;
	
	/** status : 状态. STATUS: char(1) */
	private String status ;
	
	/** lastUptTime : 最后更新时间. LAST_UPT_TIME: char(14) */
	private String lastUptTime ;
	
	/** lastUptAcc : 最后更新账户. LAST_UPT_ACC: varchar(10) */
	private String lastUptAcc ;
	
	/** lastUptOrg : 最后更新机构. LAST_UPT_ORG: varchar(30) */
	private String lastUptOrg ;
	// -- Extend --
	/** 机构名称 */
	private String orgName ;
	/** 状态  */
	private String statusDesc;
	/** 证件类型  */
	private String crdTypeDesc;
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public SysUserVo() {
		// Default Construtor
	}
	
	public SysUserVo(Long userId) {
		this.userId = userId;
	}
		
	// -- Setter And Getter
	/**
	 * Set userId : 用户id. USER_ID: int 
	 */
	public void setUserId(Long userId){
		this.userId = userId;	
	}
	
	/**
	 * Get userId : 用户id. USER_ID: int 
	 */
	public Long getUserId(){
		return this.userId;	
	}
	
	/**
	 * Set version : VERSION. VERSION: int 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: int 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set loginId : 登陆帐户. LOGIN_ID: varchar(10) 
	 */
	public void setLoginId(String loginId){
		this.loginId = loginId;	
	}
	
	/**
	 * Get loginId : 登陆帐户. LOGIN_ID: varchar(10) 
	 */
	public String getLoginId(){
		return this.loginId;	
	}
	
	/**
	 * Set loginPasswd : 登陆密码. LOGIN_PASSWD: varchar(64) 
	 */
	public void setLoginPasswd(String loginPasswd){
		this.loginPasswd = loginPasswd;	
	}
	
	/**
	 * Get loginPasswd : 登陆密码. LOGIN_PASSWD: varchar(64) 
	 */
	public String getLoginPasswd(){
		return this.loginPasswd;	
	}
	
	/**
	 * Set userName : 用户姓名. USER_NAME: varchar(20) 
	 */
	public void setUserName(String userName){
		this.userName = userName;	
	}
	
	/**
	 * Get userName : 用户姓名. USER_NAME: varchar(20) 
	 */
	public String getUserName(){
		return this.userName;	
	}
	
	/**
	 * Set orgCode : 用户机构. ORG_CODE: varchar(30) 
	 */
	public void setOrgCode(String orgCode){
		this.orgCode = orgCode;	
	}
	
	/**
	 * Get orgCode : 用户机构. ORG_CODE: varchar(30) 
	 */
	public String getOrgCode(){
		return this.orgCode;	
	}
	
	/**
	 * Set userPhone : 电话号码. USER_PHONE: varchar(20) 
	 */
	public void setUserPhone(String userPhone){
		this.userPhone = userPhone;	
	}
	
	/**
	 * Get userPhone : 电话号码. USER_PHONE: varchar(20) 
	 */
	public String getUserPhone(){
		return this.userPhone;	
	}
	
	/**
	 * Set userEmail : EMAIL. USER_EMAIL: varchar(50) 
	 */
	public void setUserEmail(String userEmail){
		this.userEmail = userEmail;	
	}
	
	/**
	 * Get userEmail : EMAIL. USER_EMAIL: varchar(50) 
	 */
	public String getUserEmail(){
		return this.userEmail;	
	}
	
	/**
	 * Set userAddr : 地址. USER_ADDR: varchar(200) 
	 */
	public void setUserAddr(String userAddr){
		this.userAddr = userAddr;	
	}
	
	/**
	 * Get userAddr : 地址. USER_ADDR: varchar(200) 
	 */
	public String getUserAddr(){
		return this.userAddr;	
	}
	
	/**
	 * Set crdType : 证件类型. CRD_TYPE: varchar(2) 
	 */
	public void setCrdType(String crdType){
		this.crdType = crdType;	
	}
	
	/**
	 * Get crdType : 证件类型. CRD_TYPE: varchar(2) 
	 */
	public String getCrdType(){
		return this.crdType;	
	}
	
	/**
	 * Set crdNo : 证件号码. CRD_NO: varchar(30) 
	 */
	public void setCrdNo(String crdNo){
		this.crdNo = crdNo;	
	}
	
	/**
	 * Get crdNo : 证件号码. CRD_NO: varchar(30) 
	 */
	public String getCrdNo(){
		return this.crdNo;	
	}
	
	/**
	 * Set regTime : 注册时间. REG_TIME: char(14) 
	 */
	public void setRegTime(String regTime){
		this.regTime = regTime;	
	}
	
	/**
	 * Get regTime : 注册时间. REG_TIME: char(14) 
	 */
	public String getRegTime(){
		return this.regTime;	
	}
	
	/**
	 * Set status : 状态. STATUS: char(1) 
	 */
	public void setStatus(String status){
		this.status = status;	
	}
	
	/**
	 * Get status : 状态. STATUS: char(1) 
	 */
	public String getStatus(){
		return this.status;	
	}
	
	/**
	 * Set lastUptTime : 最后更新时间. LAST_UPT_TIME: char(14) 
	 */
	public void setLastUptTime(String lastUptTime){
		this.lastUptTime = lastUptTime;	
	}
	
	/**
	 * Get lastUptTime : 最后更新时间. LAST_UPT_TIME: char(14) 
	 */
	public String getLastUptTime(){
		return this.lastUptTime;	
	}
	
	/**
	 * Set lastUptAcc : 最后更新账户. LAST_UPT_ACC: varchar(10) 
	 */
	public void setLastUptAcc(String lastUptAcc){
		this.lastUptAcc = lastUptAcc;	
	}
	
	/**
	 * Get lastUptAcc : 最后更新账户. LAST_UPT_ACC: varchar(10) 
	 */
	public String getLastUptAcc(){
		return this.lastUptAcc;	
	}
	
	/**
	 * Set lastUptOrg : 最后更新机构. LAST_UPT_ORG: varchar(30) 
	 */
	public void setLastUptOrg(String lastUptOrg){
		this.lastUptOrg = lastUptOrg;	
	}
	
	/**
	 * Get lastUptOrg : 最后更新机构. LAST_UPT_ORG: varchar(30) 
	 */
	public String getLastUptOrg(){
		return this.lastUptOrg;	
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getStatusDesc() {
		return statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	public String getCrdTypeDesc() {
		return crdTypeDesc;
	}

	public void setCrdTypeDesc(String crdTypeDesc) {
		this.crdTypeDesc = crdTypeDesc;
	}
	
}