package com.jiuyv.hhc.model.mchnt.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.mchnt.*;

// Generated by AutoCode4J
/**
 * Interface: [New]商户附件定义表 : TBL_BIZ_ATTACH_DEF
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface BizAttachDefDao extends BaseDao<BizAttachDefVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.mchnt.dao.BizAttachDefDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.mchnt.dao.BizAttachDefDao.filterQuery";

	/**
	 * Find BizAttachDefVo by Primary Key. 
	 * 
	 * @param attachType : 附件类型	 
	 * @return BizAttachDefVo : [New]商户附件定义表
	 */
	BizAttachDefVo findByKey(String attachType ) ;
}
