package com.jiuyv.hhc.model.mchnt.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.mchnt.*;

// Generated by AutoCode4J
/**
 * Interface: [New]商户信息附加表 : TBL_BIZ_MCHNT_PROP
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface BizMchntPropDao extends BaseDao<BizMchntPropVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.mchnt.dao.BizMchntPropDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.mchnt.dao.BizMchntPropDao.filterQuery";

	/**
	 * Find BizMchntPropVo by Primary Key. 
	 * 
	 * @param mchntCode : 内部商户号	 
	 * @return BizMchntPropVo : [New]商户信息附加表
	 */
	BizMchntPropVo findByKey(Long mchntCode ) ;
}
