package com.jiuyv.hhc.model.mchnt.dao ;

import org.apache.ibatis.annotations.Param;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.mchnt.*;

// Generated by AutoCode4J
/**
 * Interface: [New]商户信息表 : TBL_BIZ_MERCHANT
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface BizMerchantDao extends BaseDao<BizMerchantVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.mchnt.dao.BizMerchantDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.mchnt.dao.BizMerchantDao.filterQuery";
	
	/** The String mappe d_ fin d_ brief. */
	String MAPPED_FIND_BRIEF = "com.jiuyv.hhc.model.mchnt.dao.BizMerchantDao.filterBriefQuery";
	
	/** The String mappe d_ fin d_ agen t_ code. */
	String MAPPED_FIND_AGENT_CODE = "com.jiuyv.hhc.model.mchnt.dao.BizMerchantDao.filterQueryWithAgentCode";

	/**
	 * Find BizMerchantVo by Primary Key. 
	 * 
	 * @param mchntCode : 内部商户号	 
	 * @return BizMerchantVo : [New]商户信息表
	 */
	BizMerchantVo findByKey(Long mchntCode ) ;

	/**
	 * Count audit mchnt.
	 *
	 * @param mchntCd the mchnt cd
	 * @param mchntCode the mchnt code
	 * @return the long
	 */
	Long countAuditMchnt(@Param("mchntCd")String mchntCd, @Param("mchntCode")Long mchntCode);
}
