package com.jiuyv.hhc.model.mchnt.dao ;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.mchnt.*;

// Generated by AutoCode4J
/**
 * Interface: [New]商户信息附件表 : TBL_BIZ_MCHNT_ATTACH
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface BizMchntAttachDao extends BaseDao<BizMchntAttachVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.mchnt.dao.BizMchntAttachDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.mchnt.dao.BizMchntAttachDao.filterQuery";

	/**
	 * Find BizMchntAttachVo by Primary Key. 
	 * 
	 * @param attachSeq : 附件编号	 
	 * @return BizMchntAttachVo : [New]商户信息附件表
	 */
	BizMchntAttachVo findByKey(Long attachSeq ) ;

	
	/**
	 * Delete by seq list.
	 * 根据seq列表删除记录
	 * @param attachSeqList the attach seq list
	 * @return the int
	 */
	int deleteBySeqList(@Param("attachSeqList")List<Long> attachSeqList);
}
