package com.jiuyv.hhc.model.information.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.information.*;

// Generated by AutoCode4J
/**
 * Interface: 网站内容基本信息 : TBL_CM_ARTICLE
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface CmArticleDao extends BaseDao<CmArticleVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.information.dao.CmArticleDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.information.dao.CmArticleDao.filterQuery";

	/**
	 * Find CmArticleVo by Primary Key. 
	 * 
	 * @param artSeq : 内部序号	 
	 * @return CmArticleVo : 网站内容基本信息
	 */
	CmArticleVo findByKey(Long artSeq ) ;
	
	/**
	 * Find CmArticleVo by Primary Key. 
	 * 
	 * @param artSeq : 内部序号	 
	 * @return CmArticleVo : 网站内容基本信息
	 */
	CmArticleVo findContentByKey(Long artSeq ) ;
	
	/**
	 * Update  by Primary Key.
	 *
	 * @param vo the vo
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int updateVerByKey(CmArticleVo vo);
	

	/**
	 * Insert .
	 *
	 * @param vo the vo
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int insertVer(CmArticleVo vo) ;

	
	/**
	 * Count ver by key.
	 *
	 * @param artSeq the art seq
	 * @return the int
	 */
	int countVerByKey(Long artSeq);

	
	/**
	 * Delete ver.
	 *
	 * @param dvo the dvo
	 */
	void deleteVer(CmArticleVo dvo);
}
