package com.jiuyv.hhc.model.information.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.information.CmArtCatVo;

// Generated by AutoCode4J
/**
 * Interface: 网站栏目分类 : TBL_CM_ART_CAT
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface CmArtCatDao extends BaseDao<CmArtCatVo>{
	
	/** mapped key is : com.jiuyv.hhc.model.information.dao.CmArtCatDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.information.dao.CmArtCatDao.filterQuery";
	/** mapped key is : com.jiuyv.hhc.model.information.dao.CmArtCatDao.filterQueryTreeCats */
	String CAT_TREE_FIND = "com.jiuyv.hhc.model.information.dao.CmArtCatDao.filterQueryTreeCat";
	
	/**
	 * Find CmArtCatVo by Primary Key. 
	 * 
	 * @param catSeq : 内部序号	 
	 * @return CmArtCatVo : 网站栏目分类
	 */
	CmArtCatVo findByKey(Long catSeq ) ;
	
	/**
	 * Update CmArticleCatVerVo by Primary Key.
	 *
	 * @param vo the vo
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int updateVerByKey(CmArtCatVo vo);
	

	/**
	 * Insert CmArticleCatVerVo.
	 *
	 * @param vo the vo
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int insertVer(CmArtCatVo vo) ;

	
	/**
	 * Count ver by key.
	 *
	 * @param catSeq the cat seq
	 * @return the int
	 */
	int countVerByKey(Long catSeq);

	void deleteVer(CmArtCatVo dvo);


}