package com.jiuyv.hhc.model.security.dao ;


import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.security.SysOrgVo;

// Generated by AutoCode4J
/**
 * Interface: 控制台机构表 : TBL_SYS_ORG
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface SysOrgDao extends BaseDao<SysOrgVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.security.dao.SysOrgDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.security.dao.SysOrgDao.filterQuery";
	/** mapped key is : com.jiuyv.hhc.model.security.dao.SysOrgDao.filterQueryTreeOrg */
	String MAPPED_TREEORG_FIND = "com.jiuyv.hhc.model.security.dao.SysOrgDao.filterQueryTreeOrg";

	/**
	 * Find SysOrgVo by Primary Key. 
	 * 
	 * @param orgCode : 机构代码	 
	 * @return SysOrgVo : 控制台机构表
	 */
	SysOrgVo findByKey(String orgCode ) ;
	
}