package com.jiuyv.hhc.model.security.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.security.SysOprlogVo;

// Generated by AutoCode4J
/**
 * Interface: 控制台操作流水表 : TBL_SYS_OPRLOG
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface SysOprlogDao extends BaseDao<SysOprlogVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.security.dao.SysOprlogDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.security.dao.SysOprlogDao.filterQuery";
	
	/** 查询日志流水，不包含操作结果和备注信息 */
	String MAPPED_FIND_BRIEF = "com.jiuyv.hhc.model.security.dao.SysOprlogDao.filterQueryBrief";

	/**
	 * Find SysOprlogVo by Primary Key. 
	 * 
	 * @param oprNo : 操作流水号	 
	 * @return SysOprlogVo : 控制台操作流水表
	 */
	SysOprlogVo findByKey(Long oprNo ) ;

}