package com.jiuyv.hhc.model.security.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.security.SysRoleVo;

// Generated by AutoCode4J
/**
 * Interface: 控制台角色表 : TBL_SYS_ROLE
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface SysRoleDao extends BaseDao<SysRoleVo>{
	
	/** mapped key is : com.jiuyv.hhc.model.security.dao.SysRoleDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.security.dao.SysRoleDao.filterQuery";

	/**
	 * Find SysRoleVo by Primary Key. 
	 * 
	 * @param roleId : 角色ID	 
	 * @return SysRoleVo : 控制台角色表
	 */
	SysRoleVo findByKey(Long roleId ) ;
	
}