package com.jiuyv.hhc.model.security.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.security.SysResourceVo;

// Generated by AutoCode4J
/**
 * Interface: 控制台资源表 : TBL_SYS_RESOURCE
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface SysResourceDao extends BaseDao<SysResourceVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.security.dao.SysResourceDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.security.dao.SysResourceDao.filterQuery";

	/**
	 * Find SysResourceVo by Primary Key. 
	 * 
	 * @param resId : 资源ID	 
	 * @return SysResourceVo : 控制台资源表
	 */
	SysResourceVo findByKey(String resId ) ;

}