package com.jiuyv.hhc.model.security.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.security.SysUserVo;

// Generated by AutoCode4J
/**
 * Interface: 控制台用户表 : TBL_SYS_USER
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface SysUserDao extends BaseDao<SysUserVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.security.dao.SysUserDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.security.dao.SysUserDao.filterQuery";

	/**
	 * Find SysUserVo by Primary Key. 
	 * 
	 * @param userId : 用户id	 
	 * @return SysUserVo : 控制台用户表
	 */
	SysUserVo findByKey(Long userId ) ;

}