package com.jiuyv.hhc.model.security.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.sms.inter.IWebSecCodeInterface;
import com.jiuyv.hhc.sms.model.WebSecCodeVo;

// Generated by AutoCode4J
/**
 * Interface: 验证码表 : CZD_WEB_SEC_CODE
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface WebSecCodeDao extends BaseDao<WebSecCodeVo>,IWebSecCodeInterface{
	
	/** mapped key is : com.jiuyv.hhc.model.web.dao.WebSecCodeDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.web.dao.WebSecCodeDao.filterQuery";

	/**
	 * Find WebSecCodeVo by Primary Key. 
	 * 
	 * @param seqNo : 序号	 
	 * @return WebSecCodeVo : 验证码表
	 */
	WebSecCodeVo findByKey(Long seqNo ) ;
	
	String findDatabaseTime();
	/**
	 * Update WebSecCodeVo by Primary Key.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int updateByKey(WebSecCodeVo vo);
	

	/**
	 * Insert WebSecCodeVo.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int insert(WebSecCodeVo vo) ;

	/**
	 * Insert WebSecCodeVo.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int deleteByKey(WebSecCodeVo vo) ;
	
	WebSecCodeVo findAvailbleCode(WebSecCodeVo vo ) ;
	
	WebSecCodeVo findUnUsedCode(WebSecCodeVo vo ) ;
}