package com.jiuyv.hhc.model.common ;

import java.util.Arrays;

// Generated by AutoCode4J
/**
 * EntityBean: 媒体资源 : TBL_CM_MEDIA_RES
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class CmMediaResVo implements java.io.Serializable,IMedia {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** medSeq : 内部序号. MED_SEQ: NUMBER(18) */
	private Long medSeq ;
	
	/** version : VERSION. VERSION: NUMERIC(10) */
	private Long version ;
	
	/** medPath : 路径. MED_PATH: VARCHAR2(256) */
	private String medPath ;
	
	/** medDir : 目录. MED_DIR: VARCHAR2(256) */
	private String medDir ;
	
	/** medType : 类型. MED_TYPE: VARCHAR2(4) */
	private String medType ;
	
	/** medName : 名称. MED_NAME: VARCHAR2(256) */
	private String medName ;
	
	/** medThumb : 缩略图. MED_THUMB: BLOB */
	private byte[] medThumb ;
	
	/** medContent : 内容. MED_CONTENT: BLOB */
	private byte[] medContent ;
	
	/** medDesc : 描述. MED_DESC: VARCHAR2(256) */
	private String medDesc ;
	
	/** mimeType : MIME类型. MIME_TYPE: VARCHAR2(100) */
	private String mimeType ;
	
	/** customerCode : 会员代码. CUSTOMER_CODE: NUMBER(10) */
	private Long customerCode ;
	
	/** medInfo : 图片基本信息. MED_INFO: VARCHAR2(400) */
	private String medInfo ;
	
	/** recCrtTime : 记录创建时间. REC_CRT_TIME: CHAR(14) */
	private String recCrtTime ;
	
	/** recCrtAcc : 记录创建用户帐号. REC_CRT_ACC: VARCHAR2(30) */
	private String recCrtAcc ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public CmMediaResVo() {
		// Default Construtor
	}
	
	public CmMediaResVo(Long medSeq) {
		this.medSeq = medSeq;
	}
		
	// -- Setter And Getter
	/**
	 * Set medSeq : 内部序号. MED_SEQ: NUMBER(18) 
	 */
	public void setMedSeq(Long medSeq){
		this.medSeq = medSeq;	
	}
	
	/**
	 * Get medSeq : 内部序号. MED_SEQ: NUMBER(18) 
	 */
	public Long getMedSeq(){
		return this.medSeq;	
	}
	
	/**
	 * Set version : VERSION. VERSION: NUMERIC(10) 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: NUMERIC(10) 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set medPath : 路径. MED_PATH: VARCHAR2(256) 
	 */
	public void setMedPath(String medPath){
		this.medPath = medPath;	
	}
	
	/**
	 * Get medPath : 路径. MED_PATH: VARCHAR2(256) 
	 */
	public String getMedPath(){
		return this.medPath;	
	}
	
	/**
	 * Set medDir : 目录. MED_DIR: VARCHAR2(256) 
	 */
	public void setMedDir(String medDir){
		this.medDir = medDir;	
	}
	
	/**
	 * Get medDir : 目录. MED_DIR: VARCHAR2(256) 
	 */
	public String getMedDir(){
		return this.medDir;	
	}
	
	/**
	 * Set medType : 类型. MED_TYPE: VARCHAR2(4) 
	 */
	public void setMedType(String medType){
		this.medType = medType;	
	}
	
	/**
	 * Get medType : 类型. MED_TYPE: VARCHAR2(4) 
	 */
	public String getMedType(){
		return this.medType;	
	}
	
	/**
	 * Set medName : 名称. MED_NAME: VARCHAR2(256) 
	 */
	public void setMedName(String medName){
		this.medName = medName;	
	}
	
	/**
	 * Get medName : 名称. MED_NAME: VARCHAR2(256) 
	 */
	public String getMedName(){
		return this.medName;	
	}
	
	public byte[] getMedThumb() {
		return medThumb;
	}

	public void setMedThumb(byte[] medThumb) {
		if (null != medThumb) {
			this.medThumb = Arrays.copyOf(medThumb,
					medThumb.length);
		} else {
			this.medThumb = null;
		}
	}

	public void setMedContent(byte[] medContent) {
		if (null != medContent) {
			this.medContent = Arrays.copyOf(medContent,
					medContent.length);
		} else {
			this.medContent = null;
		}
	}
	
	public byte[] getMedContent() {
		return medContent;
	}

	/**
	 * Set medDesc : 描述. MED_DESC: VARCHAR2(256) 
	 */
	public void setMedDesc(String medDesc){
		this.medDesc = medDesc;	
	}
	
	/**
	 * Get medDesc : 描述. MED_DESC: VARCHAR2(256) 
	 */
	public String getMedDesc(){
		return this.medDesc;	
	}
	
	/**
	 * Set mimeType : MIME类型. MIME_TYPE: VARCHAR2(100) 
	 */
	public void setMimeType(String mimeType){
		this.mimeType = mimeType;	
	}
	
	/**
	 * Get mimeType : MIME类型. MIME_TYPE: VARCHAR2(100) 
	 */
	public String getMimeType(){
		return this.mimeType;	
	}
	
	/**
	 * Set customerCode : 会员代码. CUSTOMER_CODE: NUMBER(10) 
	 */
	public void setCustomerCode(Long customerCode){
		this.customerCode = customerCode;	
	}
	
	/**
	 * Get customerCode : 会员代码. CUSTOMER_CODE: NUMBER(10) 
	 */
	public Long getCustomerCode(){
		return this.customerCode;	
	}
	
	/**
	 * Set medInfo : 图片基本信息. MED_INFO: VARCHAR2(400) 
	 */
	public void setMedInfo(String medInfo){
		this.medInfo = medInfo;	
	}
	
	/**
	 * Get medInfo : 图片基本信息. MED_INFO: VARCHAR2(400) 
	 */
	public String getMedInfo(){
		return this.medInfo;	
	}
	
	/**
	 * Set recCrtTime : 记录创建时间. REC_CRT_TIME: CHAR(14) 
	 */
	public void setRecCrtTime(String recCrtTime){
		this.recCrtTime = recCrtTime;	
	}
	
	/**
	 * Get recCrtTime : 记录创建时间. REC_CRT_TIME: CHAR(14) 
	 */
	public String getRecCrtTime(){
		return this.recCrtTime;	
	}
	
	/**
	 * Set recCrtAcc : 记录创建用户帐号. REC_CRT_ACC: VARCHAR2(30) 
	 */
	public void setRecCrtAcc(String recCrtAcc){
		this.recCrtAcc = recCrtAcc;	
	}
	
	/**
	 * Get recCrtAcc : 记录创建用户帐号. REC_CRT_ACC: VARCHAR2(30) 
	 */
	public String getRecCrtAcc(){
		return this.recCrtAcc;	
	}
	@Override
	public String getContentType() {
		return this.getMimeType();
	}

	@Override
	public String getEncode() {
		return null;
	}

	@Override
	public byte[] getContent() {
		return this.medThumb == null ? this.getMedContent() : this.medThumb ;
	}
}