package com.jiuyv.hhc.model.common ;

// Generated by AutoCode4J
/**
 * EntityBean: 系统代码表 : TBL_SYS_CODE
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class SysCodeVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** codeType : 类别. CODE_TYPE: varchar(40) */
	private String codeType ;
	
	/** codeNo : 代码. CODE_NO: varchar(10) */
	private String codeNo ;
	
	/** codeTypeName : 类别名称. CODE_TYPE_NAME: varchar(40) */
	private String codeTypeName ;
	
	/** codeLang : 代码语言. CODE_LANG: varchar(5) */
	private String codeLang ;
	
	/** codeFlag : 代码标示. CODE_FLAG: char(1) */
	private String codeFlag ;
	
	/** codeName : 代码名称. CODE_NAME: varchar(40) */
	private String codeName ;
	
	/** codeSort : 排序号. CODE_SORT: decimal(5) */
	private Double codeSort ;
	
	/** lastUptTime : 最后更新时间. LAST_UPT_TIME: char(14) */
	private String lastUptTime ;
	
	/** lastUptAcc : 最后更新账户. LAST_UPT_ACC: varchar(10) */
	private String lastUptAcc ;
	
	/** lastUptOrg : 最后更新机构. LAST_UPT_ORG: varchar(30) */
	private String lastUptOrg ;
	
	/** reserved1 : 保留域1. RESERVED1: varchar(100) */
	private String reserved1 ;
	
	/** reserved2 : 保留域2. RESERVED2: varchar(100) */
	private String reserved2 ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public SysCodeVo() {
		// Default Construtor
	}
	
	public SysCodeVo(String codeType, String codeNo) {
		this.codeType = codeType;
		this.codeNo = codeNo;
	}
		
	// -- Setter And Getter
	/**
	 * Set codeType : 类别. CODE_TYPE: varchar(40) 
	 */
	public void setCodeType(String codeType){
		this.codeType = codeType;	
	}
	
	/**
	 * Get codeType : 类别. CODE_TYPE: varchar(40) 
	 */
	public String getCodeType(){
		return this.codeType;	
	}
	
	/**
	 * Set codeNo : 代码. CODE_NO: varchar(10) 
	 */
	public void setCodeNo(String codeNo){
		this.codeNo = codeNo;	
	}
	
	/**
	 * Get codeNo : 代码. CODE_NO: varchar(10) 
	 */
	public String getCodeNo(){
		return this.codeNo;	
	}
	
	/**
	 * Set codeTypeName : 类别名称. CODE_TYPE_NAME: varchar(40) 
	 */
	public void setCodeTypeName(String codeTypeName){
		this.codeTypeName = codeTypeName;	
	}
	
	/**
	 * Get codeTypeName : 类别名称. CODE_TYPE_NAME: varchar(40) 
	 */
	public String getCodeTypeName(){
		return this.codeTypeName;	
	}
	
	/**
	 * Set codeLang : 代码语言. CODE_LANG: varchar(5) 
	 */
	public void setCodeLang(String codeLang){
		this.codeLang = codeLang;	
	}
	
	/**
	 * Get codeLang : 代码语言. CODE_LANG: varchar(5) 
	 */
	public String getCodeLang(){
		return this.codeLang;	
	}
	
	/**
	 * Set codeFlag : 代码标示. CODE_FLAG: char(1) 
	 */
	public void setCodeFlag(String codeFlag){
		this.codeFlag = codeFlag;	
	}
	
	/**
	 * Get codeFlag : 代码标示. CODE_FLAG: char(1) 
	 */
	public String getCodeFlag(){
		return this.codeFlag;	
	}
	
	/**
	 * Set codeName : 代码名称. CODE_NAME: varchar(40) 
	 */
	public void setCodeName(String codeName){
		this.codeName = codeName;	
	}
	
	/**
	 * Get codeName : 代码名称. CODE_NAME: varchar(40) 
	 */
	public String getCodeName(){
		return this.codeName;	
	}
	
	/**
	 * Set codeSort : 排序号. CODE_SORT: decimal(5) 
	 */
	public void setCodeSort(Double codeSort){
		this.codeSort = codeSort;	
	}
	
	/**
	 * Get codeSort : 排序号. CODE_SORT: decimal(5) 
	 */
	public Double getCodeSort(){
		return this.codeSort;	
	}
	
	/**
	 * Set lastUptTime : 最后更新时间. LAST_UPT_TIME: char(14) 
	 */
	public void setLastUptTime(String lastUptTime){
		this.lastUptTime = lastUptTime;	
	}
	
	/**
	 * Get lastUptTime : 最后更新时间. LAST_UPT_TIME: char(14) 
	 */
	public String getLastUptTime(){
		return this.lastUptTime;	
	}
	
	/**
	 * Set lastUptAcc : 最后更新账户. LAST_UPT_ACC: varchar(10) 
	 */
	public void setLastUptAcc(String lastUptAcc){
		this.lastUptAcc = lastUptAcc;	
	}
	
	/**
	 * Get lastUptAcc : 最后更新账户. LAST_UPT_ACC: varchar(10) 
	 */
	public String getLastUptAcc(){
		return this.lastUptAcc;	
	}
	
	/**
	 * Set lastUptOrg : 最后更新机构. LAST_UPT_ORG: varchar(30) 
	 */
	public void setLastUptOrg(String lastUptOrg){
		this.lastUptOrg = lastUptOrg;	
	}
	
	/**
	 * Get lastUptOrg : 最后更新机构. LAST_UPT_ORG: varchar(30) 
	 */
	public String getLastUptOrg(){
		return this.lastUptOrg;	
	}
	
	/**
	 * Set reserved1 : 保留域1. RESERVED1: varchar(100) 
	 */
	public void setReserved1(String reserved1){
		this.reserved1 = reserved1;	
	}
	
	/**
	 * Get reserved1 : 保留域1. RESERVED1: varchar(100) 
	 */
	public String getReserved1(){
		return this.reserved1;	
	}
	
	/**
	 * Set reserved2 : 保留域2. RESERVED2: varchar(100) 
	 */
	public void setReserved2(String reserved2){
		this.reserved2 = reserved2;	
	}
	
	/**
	 * Get reserved2 : 保留域2. RESERVED2: varchar(100) 
	 */
	public String getReserved2(){
		return this.reserved2;	
	}
	
}