package com.jiuyv.hhc.model.loan.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.loan.MhtRiskDataVo;

// Generated by AutoCode4J
/**
 * Interface: 商户风险统计信息 : TBL_MHT_RISK_DATA
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface MhtRiskDataDao extends BaseDao<MhtRiskDataVo>{
	
	/** mapped key is : com.jiuyv.hhc.model.loan.dao.MhtRiskDataDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.loan.dao.MhtRiskDataDao.filterQuery";

	/**
	 * Find MhtRiskDataVo by Primary Key. 
	 * 
	 * @param riskId : 风险数据号	 
	 * @return MhtRiskDataVo : 商户风险统计信息
	 */
	MhtRiskDataVo findByKey(Long riskId ) ;
	
	/**
	 * Update MhtRiskDataVo by Primary Key.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int updateByKey(MhtRiskDataVo vo);
	

	/**
	 * Insert MhtRiskDataVo.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int insert(MhtRiskDataVo vo) ;


	int deleteByMhtCode(MhtRiskDataVo vo);
}