package com.jiuyv.hhc.model.loan.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.loan.MhtTransAfterLoanVo;

// Generated by AutoCode4J
/**
 * Interface: 商户贷后日均交易数据表 : TBL_MHT_TRANS_ATER_LOAN
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface MhtTransAfterLoanDao extends BaseDao<MhtTransAfterLoanVo>{
	
	/** mapped key is : com.jiuyv.hhc.model.loan.dao.MhtTransAfterLoanDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.loan.dao.MhtTransAfterLoanDao.filterQuery";

	/**
	 * Find MhtTransAfterLoanVo by Primary Key. 
	 * 
	 * @param mchntCode : 内部商户号
	 * @param transDt : 交易日期	 
	 * @return MhtTransAfterLoanVo : 商户贷后日均交易数据表
	 */
	MhtTransAfterLoanVo findByKey(Long mchntCode , String transDt ) ;
	
	/**
	 * Update MhtTransAfterLoanVo by Primary Key.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int updateByKey(MhtTransAfterLoanVo vo);
	

	/**
	 * Insert MhtTransAfterLoanVo.
	 * 
	 * @return effect rows.
	 * @author AutoCode4J
	 */
	int insert(MhtTransAfterLoanVo vo) ;

	int deleteByMhtCode(MhtTransAfterLoanVo vo);

}