package com.jiuyv.hhc.model.loan.dao ;

import com.jiuyv.common.database.BaseDao;
import com.jiuyv.hhc.model.loan.*;

// Generated by AutoCode4J
/**
 * Interface: 接口通信记录表 : TBL_TXN_TRANS_LOG
 * This is a interface. 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public interface TxnTransLogDao extends BaseDao<TxnTransLogVo> {
	
	/** mapped key is : com.jiuyv.hhc.model.loan.dao.TxnTransLogDao.filterQuery */
	String MAPPED_FIND = "com.jiuyv.hhc.model.loan.dao.TxnTransLogDao.filterQuery";

	String MAPPED_AMT_FIND = "com.jiuyv.hhc.model.loan.dao.TxnTransLogDao.filterQueryAmt";

	/**
	 * Find TxnTransLogVo by Primary Key. 
	 * 
	 * @param logSeq : 序列号	 
	 * @return TxnTransLogVo : 接口通信记录表
	 */
	TxnTransLogVo findByKey(Long logSeq ) ;
}
