package com.jiuyv.hhc.model.loan ;

// Generated by AutoCode4J
/**
 * EntityBean: [New]贷款记录信息表 : CZD_BIZ_LOAN_DATA
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class BizLoanDataVo implements java.io.Serializable { 

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** loanId : 贷款编号. LOAN_ID: VARCHAR2(32) */
	private String loanId ;
	
	/** version : VERSION. VERSION: NUMERIC(10) */
	private Long version ;
	
	/** mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) */
	private Long mchntCode ;
	
	/** cupLoanId : 银联贷款编号. CUP_LOAN_ID: VARCHAR2(40) */
	private String cupLoanId ;
	
	/** licNo : 营业执照号码. LIC_NO: VARCHAR2(70) */
	private String licNo ;
	
	/** artifCertifId : 法人代表证件号. ARTIF_CERTIF_ID: VARCHAR2(22) */
	private String artifCertifId ;
	
	/** artifNm : 法人代表姓名. ARTIF_NM: VARCHAR2(40) */
	private String artifNm ;
	
	/** creditSt : 贷款状态. CREDIT_ST: VARCHAR2(2) */
	private String creditSt ;
	
	/** mchntSt : 商户状态. MCHNT_ST: VARCHAR2(2) */
	private String mchntSt ;
	
	/** cancelFlag : 用户撤销标识. CANCEL_FLAG: VARCHAR2(1) */
	private String cancelFlag ;
	
	/** lenderId : 资金方编码. LENDER_ID: VARCHAR2(40) */
	private String lenderId ;
	
	/** reqLoanAt : 申请贷款金额. REQ_LOAN_AT: NUMBER(12) */
	private Long reqLoanAt ;
	
	/** loanAt : 贷款/放贷金额. LOAN_AT: NUMBER(12) */
	private Long loanAt ;
	
	/** loanCycle : 贷款周期. LOAN_CYCLE: NUMBER(10) */
	private Long loanCycle ;
	
	/** loanRt : 贷款利率. LOAN_RT: NUMBER(10) */
	private Long loanRt ;
	
	/** cardCreditLimit : 银行卡授信额度. CARD_CREDIT_LIMIT: NUMBER(12) */
	private Long cardCreditLimit ;
	
	/** cardUseLimit : 银行卡使用额度. CARD_USE_LIMIT: NUMBER(12) */
	private Long cardUseLimit ;
	
	/** cardExpire : 银行卡有效期. CARD_EXPIRE: VARCHAR2(8) */
	private String cardExpire ;
	
	/** cardNo : 银行卡号. CARD_NO: VARCHAR2(30) */
	private String cardNo ;
	
	/** loanSuccTm : 放款成功时间. LOAN_SUCC_TM: VARCHAR2(14) */
	private String loanSuccTm ;
	
	/** loanBalance : 贷款余额. LOAN_BALANCE: NUMBER(12) */
	private Long loanBalance ;
	
	/** loanProd : 贷款产品. LOAN_PROD: VARCHAR2(8) */
	private String loanProd ;
	
	/** svcFeeBenefit : 服务费收益. SVC_FEE_BENEFIT: NUMBER(12) */
	private Long svcFeeBenefit ;
	
	/** allotTp : 分润方式. ALLOT_TP: VARCHAR2(20) */
	private String allotTp ;
	
	/** exceedAt : 逾期金额. EXCEED_AT: NUMBER(12) */
	private Long exceedAt ;
	
	/** exceedNum : 逾期笔数. EXCEED_NUM: NUMBER(11) */
	private Long exceedNum ;
	
	/** loanExpire : 贷款有效期. LOAN_EXPIRE: VARCHAR2(8) */
	private String loanExpire ;
	
	/** remark : 备注. REMARK: VARCHAR(200) */
	private String remark ;
	
	/** loanReqTime : 贷款申请时间. LOAN_REQ_TIME: CHAR(14) */
	private String loanReqTime ;
	
	/** loanProcResp : 贷款处理意见. LOAN_PROC_RESP: NVARCHAR2(200) */
	private String loanProcResp ;
	
	/** loanProcAcc : 贷款处理账户. LOAN_PROC_ACC: NVARCHAR2(30) */
	private String loanProcAcc ;
	
	/** loanProcTime : 贷款处理时间. LOAN_PROC_TIME: CHAR(14) */
	private String loanProcTime ;
	
	/** lastUptOrg : 最后更新机构. LAST_UPT_ORG: NVARCHAR2(30) */
	private String lastUptOrg ;
	
	/** lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) */
	private String lastUptTime ;
	
	/** lastUptAcc : 最后修改用户帐号. LAST_UPT_ACC: NVARCHAR2(30) */
	private String lastUptAcc ;
	
	/** recAcc : 记录创建账户. REC_ACC: NVARCHAR2(30) */
	private String recAcc ;
	
	// extended 
	
	private String creditStDesc;
	
	/** mchntCd : 商户代码. MCHNT_CD: VARCHAR(15) */
	private String mchntCd ;
	
	/** mchntCnName : 商户中文名称. MCHNT_CN_NAME: VARCHAR(100) */
	private String mchntCnName ;
	
	/** cancelFlagDesc : 用户撤销标识.*/
	private String cancelFlagDesc ;
	
	/** 会员编号 */
	private Long customerCode ; 
	/** 注册手机号 */
	private String customerMobile;
	
	/** recAccDesc : 记录创建账户. */
	private String recAccDesc ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public BizLoanDataVo() {
		// Default Construtor
	}
	
	public BizLoanDataVo(String loanId) {
		this.loanId = loanId;
	}
		
	// -- Setter And Getter
	/**
	 * Set loanId : 贷款编号. LOAN_ID: VARCHAR2(32) 
	 */
	public void setLoanId(String loanId){
		this.loanId = loanId;	
	}
	
	/**
	 * Get loanId : 贷款编号. LOAN_ID: VARCHAR2(32) 
	 */
	public String getLoanId(){
		return this.loanId;	
	}
	
	/**
	 * Set version : VERSION. VERSION: NUMERIC(10) 
	 */
	public void setVersion(Long version){
		this.version = version;	
	}
	
	/**
	 * Get version : VERSION. VERSION: NUMERIC(10) 
	 */
	public Long getVersion(){
		return this.version;	
	}
	
	/**
	 * Set mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public void setMchntCode(Long mchntCode){
		this.mchntCode = mchntCode;	
	}
	
	/**
	 * Get mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public Long getMchntCode(){
		return this.mchntCode;	
	}
	
	/**
	 * Set cupLoanId : 银联贷款编号. CUP_LOAN_ID: VARCHAR2(40) 
	 */
	public void setCupLoanId(String cupLoanId){
		this.cupLoanId = cupLoanId;	
	}
	
	/**
	 * Get cupLoanId : 银联贷款编号. CUP_LOAN_ID: VARCHAR2(40) 
	 */
	public String getCupLoanId(){
		return this.cupLoanId;	
	}
	
	/**
	 * Set licNo : 营业执照号码. LIC_NO: VARCHAR2(70) 
	 */
	public void setLicNo(String licNo){
		this.licNo = licNo;	
	}
	
	/**
	 * Get licNo : 营业执照号码. LIC_NO: VARCHAR2(70) 
	 */
	public String getLicNo(){
		return this.licNo;	
	}
	
	/**
	 * Set artifCertifId : 法人代表证件号. ARTIF_CERTIF_ID: VARCHAR2(22) 
	 */
	public void setArtifCertifId(String artifCertifId){
		this.artifCertifId = artifCertifId;	
	}
	
	/**
	 * Get artifCertifId : 法人代表证件号. ARTIF_CERTIF_ID: VARCHAR2(22) 
	 */
	public String getArtifCertifId(){
		return this.artifCertifId;	
	}
	
	/**
	 * Set artifNm : 法人代表姓名. ARTIF_NM: VARCHAR2(40) 
	 */
	public void setArtifNm(String artifNm){
		this.artifNm = artifNm;	
	}
	
	/**
	 * Get artifNm : 法人代表姓名. ARTIF_NM: VARCHAR2(40) 
	 */
	public String getArtifNm(){
		return this.artifNm;	
	}
	
	/**
	 * Set creditSt : 贷款状态. CREDIT_ST: VARCHAR2(2) 
	 */
	public void setCreditSt(String creditSt){
		this.creditSt = creditSt;	
	}
	
	/**
	 * Get creditSt : 贷款状态. CREDIT_ST: VARCHAR2(2) 
	 */
	public String getCreditSt(){
		return this.creditSt;	
	}
	
	/**
	 * Set mchntSt : 商户状态. MCHNT_ST: VARCHAR2(2) 
	 */
	public void setMchntSt(String mchntSt){
		this.mchntSt = mchntSt;	
	}
	
	/**
	 * Get mchntSt : 商户状态. MCHNT_ST: VARCHAR2(2) 
	 */
	public String getMchntSt(){
		return this.mchntSt;	
	}
	
	/**
	 * Set lenderId : 资金方编码. LENDER_ID: VARCHAR2(40) 
	 */
	public void setLenderId(String lenderId){
		this.lenderId = lenderId;	
	}
	
	/**
	 * Get lenderId : 资金方编码. LENDER_ID: VARCHAR2(40) 
	 */
	public String getLenderId(){
		return this.lenderId;	
	}
	
	/**
	 * Set reqLoanAt : 申请贷款金额. REQ_LOAN_AT: NUMBER(12) 
	 */
	public void setReqLoanAt(Long reqLoanAt){
		this.reqLoanAt = reqLoanAt;	
	}
	
	/**
	 * Get reqLoanAt : 申请贷款金额. REQ_LOAN_AT: NUMBER(12) 
	 */
	public Long getReqLoanAt(){
		return this.reqLoanAt;	
	}
	
	/**
	 * Set loanAt : 贷款/放贷金额. LOAN_AT: NUMBER(12) 
	 */
	public void setLoanAt(Long loanAt){
		this.loanAt = loanAt;	
	}
	
	/**
	 * Get loanAt : 贷款/放贷金额. LOAN_AT: NUMBER(12) 
	 */
	public Long getLoanAt(){
		return this.loanAt;	
	}
	
	/**
	 * Set loanCycle : 贷款周期. LOAN_CYCLE: NUMBER(10) 
	 */
	public void setLoanCycle(Long loanCycle){
		this.loanCycle = loanCycle;	
	}
	
	/**
	 * Get loanCycle : 贷款周期. LOAN_CYCLE: NUMBER(10) 
	 */
	public Long getLoanCycle(){
		return this.loanCycle;	
	}
	
	/**
	 * Set loanRt : 贷款利率. LOAN_RT: NUMBER(10) 
	 */
	public void setLoanRt(Long loanRt){
		this.loanRt = loanRt;	
	}
	
	/**
	 * Get loanRt : 贷款利率. LOAN_RT: NUMBER(10) 
	 */
	public Long getLoanRt(){
		return this.loanRt;	
	}
	
	/**
	 * Set cardCreditLimit : 银行卡授信额度. CARD_CREDIT_LIMIT: NUMBER(12) 
	 */
	public void setCardCreditLimit(Long cardCreditLimit){
		this.cardCreditLimit = cardCreditLimit;	
	}
	
	/**
	 * Get cardCreditLimit : 银行卡授信额度. CARD_CREDIT_LIMIT: NUMBER(12) 
	 */
	public Long getCardCreditLimit(){
		return this.cardCreditLimit;	
	}
	
	/**
	 * Set cardUseLimit : 银行卡使用额度. CARD_USE_LIMIT: NUMBER(12) 
	 */
	public void setCardUseLimit(Long cardUseLimit){
		this.cardUseLimit = cardUseLimit;	
	}
	
	/**
	 * Get cardUseLimit : 银行卡使用额度. CARD_USE_LIMIT: NUMBER(12) 
	 */
	public Long getCardUseLimit(){
		return this.cardUseLimit;	
	}
	
	/**
	 * Set cardExpire : 银行卡有效期. CARD_EXPIRE: VARCHAR2(8) 
	 */
	public void setCardExpire(String cardExpire){
		this.cardExpire = cardExpire;	
	}
	
	/**
	 * Get cardExpire : 银行卡有效期. CARD_EXPIRE: VARCHAR2(8) 
	 */
	public String getCardExpire(){
		return this.cardExpire;	
	}
	
	/**
	 * Set cardNo : 银行卡号. CARD_NO: VARCHAR2(30) 
	 */
	public void setCardNo(String cardNo){
		this.cardNo = cardNo;	
	}
	
	/**
	 * Get cardNo : 银行卡号. CARD_NO: VARCHAR2(30) 
	 */
	public String getCardNo(){
		return this.cardNo;	
	}
	
	/**
	 * Set loanSuccTm : 放款成功时间. LOAN_SUCC_TM: VARCHAR2(14) 
	 */
	public void setLoanSuccTm(String loanSuccTm){
		this.loanSuccTm = loanSuccTm;	
	}
	
	/**
	 * Get loanSuccTm : 放款成功时间. LOAN_SUCC_TM: VARCHAR2(14) 
	 */
	public String getLoanSuccTm(){
		return this.loanSuccTm;	
	}
	
	/**
	 * Set loanBalance : 贷款余额. LOAN_BALANCE: NUMBER(12) 
	 */
	public void setLoanBalance(Long loanBalance){
		this.loanBalance = loanBalance;	
	}
	
	/**
	 * Get loanBalance : 贷款余额. LOAN_BALANCE: NUMBER(12) 
	 */
	public Long getLoanBalance(){
		return this.loanBalance;	
	}
	
	/**
	 * Set loanProd : 贷款产品. LOAN_PROD: VARCHAR2(8) 
	 */
	public void setLoanProd(String loanProd){
		this.loanProd = loanProd;	
	}
	
	/**
	 * Get loanProd : 贷款产品. LOAN_PROD: VARCHAR2(8) 
	 */
	public String getLoanProd(){
		return this.loanProd;	
	}
	
	/**
	 * Set svcFeeBenefit : 服务费收益. SVC_FEE_BENEFIT: NUMBER(12) 
	 */
	public void setSvcFeeBenefit(Long svcFeeBenefit){
		this.svcFeeBenefit = svcFeeBenefit;	
	}
	
	/**
	 * Get svcFeeBenefit : 服务费收益. SVC_FEE_BENEFIT: NUMBER(12) 
	 */
	public Long getSvcFeeBenefit(){
		return this.svcFeeBenefit;	
	}
	
	/**
	 * Set allotTp : 分润方式. ALLOT_TP: VARCHAR2(20) 
	 */
	public void setAllotTp(String allotTp){
		this.allotTp = allotTp;	
	}
	
	/**
	 * Get allotTp : 分润方式. ALLOT_TP: VARCHAR2(20) 
	 */
	public String getAllotTp(){
		return this.allotTp;	
	}
	
	/**
	 * Set exceedAt : 逾期金额. EXCEED_AT: NUMBER(12) 
	 */
	public void setExceedAt(Long exceedAt){
		this.exceedAt = exceedAt;	
	}
	
	/**
	 * Get exceedAt : 逾期金额. EXCEED_AT: NUMBER(12) 
	 */
	public Long getExceedAt(){
		return this.exceedAt;	
	}
	
	/**
	 * Set exceedNum : 逾期笔数. EXCEED_NUM: NUMBER(11) 
	 */
	public void setExceedNum(Long exceedNum){
		this.exceedNum = exceedNum;	
	}
	
	/**
	 * Get exceedNum : 逾期笔数. EXCEED_NUM: NUMBER(11) 
	 */
	public Long getExceedNum(){
		return this.exceedNum;	
	}
	
	/**
	 * Set loanExpire : 贷款有效期. LOAN_EXPIRE: VARCHAR2(8) 
	 */
	public void setLoanExpire(String loanExpire){
		this.loanExpire = loanExpire;	
	}
	
	/**
	 * Get loanExpire : 贷款有效期. LOAN_EXPIRE: VARCHAR2(8) 
	 */
	public String getLoanExpire(){
		return this.loanExpire;	
	}
	
	/**
	 * Set remark : 备注. REMARK: VARCHAR(200) 
	 */
	public void setRemark(String remark){
		this.remark = remark;
	}
	
	/**
	 * Get remark : 备注. REMARK: VARCHAR(200) 
	 */
	public String getRemark(){
		return this.remark;	
	}
	
	/**
	 * Set loanReqTime : 贷款申请时间. LOAN_REQ_TIME: CHAR(14) 
	 */
	public void setLoanReqTime(String loanReqTime){
		this.loanReqTime = loanReqTime;	
	}
	
	/**
	 * Get loanReqTime : 贷款申请时间. LOAN_REQ_TIME: CHAR(14) 
	 */
	public String getLoanReqTime(){
		return this.loanReqTime;	
	}
	
	/**
	 * Set loanProcResp : 贷款处理意见. LOAN_PROC_RESP: NVARCHAR2(200) 
	 */
	public void setLoanProcResp(String loanProcResp){
		this.loanProcResp = loanProcResp;	
	}
	
	/**
	 * Get loanProcResp : 贷款处理意见. LOAN_PROC_RESP: NVARCHAR2(200) 
	 */
	public String getLoanProcResp(){
		return this.loanProcResp;	
	}
	
	/**
	 * Set loanProcAcc : 贷款处理账户. LOAN_PROC_ACC: NVARCHAR2(30) 
	 */
	public void setLoanProcAcc(String loanProcAcc){
		this.loanProcAcc = loanProcAcc;	
	}
	
	/**
	 * Get loanProcAcc : 贷款处理账户. LOAN_PROC_ACC: NVARCHAR2(30) 
	 */
	public String getLoanProcAcc(){
		return this.loanProcAcc;	
	}
	
	/**
	 * Set loanProcTime : 贷款处理时间. LOAN_PROC_TIME: CHAR(14) 
	 */
	public void setLoanProcTime(String loanProcTime){
		this.loanProcTime = loanProcTime;	
	}
	
	/**
	 * Get loanProcTime : 贷款处理时间. LOAN_PROC_TIME: CHAR(14) 
	 */
	public String getLoanProcTime(){
		return this.loanProcTime;	
	}
	
	/**
	 * Set lastUptOrg : 最后更新机构. LAST_UPT_ORG: NVARCHAR2(30) 
	 */
	public void setLastUptOrg(String lastUptOrg){
		this.lastUptOrg = lastUptOrg;	
	}
	
	/**
	 * Get lastUptOrg : 最后更新机构. LAST_UPT_ORG: NVARCHAR2(30) 
	 */
	public String getLastUptOrg(){
		return this.lastUptOrg;	
	}
	
	/**
	 * Set lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public void setLastUptTime(String lastUptTime){
		this.lastUptTime = lastUptTime;	
	}
	
	/**
	 * Get lastUptTime : 最后修改时间. LAST_UPT_TIME: CHAR(14) 
	 */
	public String getLastUptTime(){
		return this.lastUptTime;	
	}
	
	/**
	 * Set lastUptAcc : 最后修改用户帐号. LAST_UPT_ACC: NVARCHAR2(30) 
	 */
	public void setLastUptAcc(String lastUptAcc){
		this.lastUptAcc = lastUptAcc;	
	}
	
	/**
	 * Get lastUptAcc : 最后修改用户帐号. LAST_UPT_ACC: NVARCHAR2(30) 
	 */
	public String getLastUptAcc(){
		return this.lastUptAcc;	
	}

	/**
	 * @return the mchntCd
	 */
	public String getMchntCd() {
		return mchntCd;
	}

	/**
	 * @param mchntCd the mchntCd to set
	 */
	public void setMchntCd(String mchntCd) {
		this.mchntCd = mchntCd;
	}

	/**
	 * @return the mchntCnName
	 */
	public String getMchntCnName() {
		return mchntCnName;
	}

	/**
	 * @param mchntCnName the mchntCnName to set
	 */
	public void setMchntCnName(String mchntCnName) {
		this.mchntCnName = mchntCnName;
	}

	/**
	 * @return the creditStDesc
	 */
	public String getCreditStDesc() {
		return creditStDesc;
	}

	/**
	 * @param creditStDesc the creditStDesc to set
	 */
	public void setCreditStDesc(String creditStDesc) {
		this.creditStDesc = creditStDesc;
	}

	/**
	 * @return the cancelFlag
	 */
	public String getCancelFlag() {
		return cancelFlag;
	}

	/**
	 * @param cancelFlag the cancelFlag to set
	 */
	public void setCancelFlag(String cancelFlag) {
		this.cancelFlag = cancelFlag;
	}

	/**
	 * @return the cancelFlagDesc
	 */
	public String getCancelFlagDesc() {
		return cancelFlagDesc;
	}

	/**
	 * @param cancelFlagDesc the cancelFlagDesc to set
	 */
	public void setCancelFlagDesc(String cancelFlagDesc) {
		this.cancelFlagDesc = cancelFlagDesc;
	}

	/**
	 * @return the customerCode
	 */
	public Long getCustomerCode() {
		return customerCode;
	}

	/**
	 * @param customerCode the customerCode to set
	 */
	public void setCustomerCode(Long customerCode) {
		this.customerCode = customerCode;
	}

	/**
	 * @return the customerMobile
	 */
	public String getCustomerMobile() {
		return customerMobile;
	}

	/**
	 * @param customerMobile the customerMobile to set
	 */
	public void setCustomerMobile(String customerMobile) {
		this.customerMobile = customerMobile;
	}

	/**
	 * @return the recAcc
	 */
	public String getRecAcc() {
		return recAcc;
	}

	/**
	 * @param recAcc the recAcc to set
	 */
	public void setRecAcc(String recAcc) {
		this.recAcc = recAcc;
	}

	/**
	 * @return the recAccDesc
	 */
	public String getRecAccDesc() {
		return recAccDesc;
	}

	/**
	 * @param recAccDesc the recAccDesc to set
	 */
	public void setRecAccDesc(String recAccDesc) {
		this.recAccDesc = recAccDesc;
	}
	
}