package com.jiuyv.hhc.model.loan ;

// Generated by AutoCode4J
/**
 * EntityBean: 商户历史交易记录 : TBL_MHT_HIS_TRAN
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MhtHisTranVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) */
	private Long mchntCode ;
	
	/** hisTransMonth : 统计月份. HIS_TRANS_MONTH: VARCHAR(30) */
	private String hisTransMonth ;
	
	/** monthTransAt : 月交易额. MONTH_TRANS_AT: VARCHAR(30) */
	private String monthTransAt ;
	
	/** monthTransAtYear : 月交易额同比. MONTH_TRANS_AT_YEAR: VARCHAR(30) */
	private String monthTransAtYear ;
	
	/** monthTransNum : 月交易笔数. MONTH_TRANS_NUM: VARCHAR(30) */
	private String monthTransNum ;
	
	/** monthCusNum : 月消费客户数. MONTH_CUS_NUM: VARCHAR(30) */
	private String monthCusNum ;
	
	/** monthRepeatCusNum : 月重复消费客户数. MONTH_REPEAT_CUS_NUM: VARCHAR(30) */
	private String monthRepeatCusNum ;
	
	/** creditDebitRatio : 贷记卡与借记卡交易比. CREDIT_DEBIT_RATIO: VARCHAR(30) */
	private String creditDebitRatio ;
	
	/** remark : 备注. REMARK: VARCHAR(200) */
	private String remark ;
	
	/** recTime : 记录创建时间. REC_TIME: CHAR(14) */
	private String recTime ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public MhtHisTranVo() {
		// Default Construtor
	}
	
	public MhtHisTranVo(Long mchntCode, String hisTransMonth) {
		this.mchntCode = mchntCode;
		this.hisTransMonth = hisTransMonth;
	}
		
	// -- Setter And Getter
	/**
	 * Set mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public void setMchntCode(Long mchntCode){
		this.mchntCode = mchntCode;	
	}
	
	/**
	 * Get mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public Long getMchntCode(){
		return this.mchntCode;	
	}
	
	/**
	 * Set hisTransMonth : 统计月份. HIS_TRANS_MONTH: VARCHAR(30) 
	 */
	public void setHisTransMonth(String hisTransMonth){
		this.hisTransMonth = hisTransMonth;	
	}
	
	/**
	 * Get hisTransMonth : 统计月份. HIS_TRANS_MONTH: VARCHAR(30) 
	 */
	public String getHisTransMonth(){
		return this.hisTransMonth;	
	}
	
	/**
	 * Set monthTransAt : 月交易额. MONTH_TRANS_AT: VARCHAR(30) 
	 */
	public void setMonthTransAt(String monthTransAt){
		this.monthTransAt = monthTransAt;	
	}
	
	/**
	 * Get monthTransAt : 月交易额. MONTH_TRANS_AT: VARCHAR(30) 
	 */
	public String getMonthTransAt(){
		return this.monthTransAt;	
	}
	
	/**
	 * Set monthTransAtYear : 月交易额同比. MONTH_TRANS_AT_YEAR: VARCHAR(30) 
	 */
	public void setMonthTransAtYear(String monthTransAtYear){
		this.monthTransAtYear = monthTransAtYear;	
	}
	
	/**
	 * Get monthTransAtYear : 月交易额同比. MONTH_TRANS_AT_YEAR: VARCHAR(30) 
	 */
	public String getMonthTransAtYear(){
		return this.monthTransAtYear;	
	}
	
	/**
	 * Set monthTransNum : 月交易笔数. MONTH_TRANS_NUM: VARCHAR(30) 
	 */
	public void setMonthTransNum(String monthTransNum){
		this.monthTransNum = monthTransNum;	
	}
	
	/**
	 * Get monthTransNum : 月交易笔数. MONTH_TRANS_NUM: VARCHAR(30) 
	 */
	public String getMonthTransNum(){
		return this.monthTransNum;	
	}
	
	/**
	 * Set monthCusNum : 月消费客户数. MONTH_CUS_NUM: VARCHAR(30) 
	 */
	public void setMonthCusNum(String monthCusNum){
		this.monthCusNum = monthCusNum;	
	}
	
	/**
	 * Get monthCusNum : 月消费客户数. MONTH_CUS_NUM: VARCHAR(30) 
	 */
	public String getMonthCusNum(){
		return this.monthCusNum;	
	}
	
	/**
	 * Set monthRepeatCusNum : 月重复消费客户数. MONTH_REPEAT_CUS_NUM: VARCHAR(30) 
	 */
	public void setMonthRepeatCusNum(String monthRepeatCusNum){
		this.monthRepeatCusNum = monthRepeatCusNum;	
	}
	
	/**
	 * Get monthRepeatCusNum : 月重复消费客户数. MONTH_REPEAT_CUS_NUM: VARCHAR(30) 
	 */
	public String getMonthRepeatCusNum(){
		return this.monthRepeatCusNum;	
	}
	
	/**
	 * Set creditDebitRatio : 贷记卡与借记卡交易比. CREDIT_DEBIT_RATIO: VARCHAR(30) 
	 */
	public void setCreditDebitRatio(String creditDebitRatio){
		this.creditDebitRatio = creditDebitRatio;	
	}
	
	/**
	 * Get creditDebitRatio : 贷记卡与借记卡交易比. CREDIT_DEBIT_RATIO: VARCHAR(30) 
	 */
	public String getCreditDebitRatio(){
		return this.creditDebitRatio;	
	}
	
	/**
	 * Set remark : 备注. REMARK: VARCHAR(200) 
	 */
	public void setRemark(String remark){
		this.remark = remark;	
	}
	
	/**
	 * Get remark : 备注. REMARK: VARCHAR(200) 
	 */
	public String getRemark(){
		return this.remark;	
	}
	
	/**
	 * Set recTime : 记录创建时间. REC_TIME: CHAR(14) 
	 */
	public void setRecTime(String recTime){
		this.recTime = recTime;	
	}
	
	/**
	 * Get recTime : 记录创建时间. REC_TIME: CHAR(14) 
	 */
	public String getRecTime(){
		return this.recTime;	
	}
	
}