package com.jiuyv.hhc.model.loan ;

// Generated by AutoCode4J
/**
 * EntityBean: 商户贷后日均交易数据表 : TBL_MHT_TRANS_ATER_LOAN
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class MhtTransAfterLoanVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) */
	private Long mchntCode ;
	
	/** transDt : 交易日期. TRANS_DT: VARCHAR(30) */
	private String transDt ;
	
	/** daliyTransAt : 当日交易额. DALIY_TRANS_AT: VARCHAR(30) */
	private String daliyTransAt ;
	
	/** daliyTransNum : 当日交易笔数. DALIY_TRANS_NUM: VARCHAR(30) */
	private String daliyTransNum ;
	
	/** daliyCusNum : 当日消费客户数. DALIY_CUS_NUM: VARCHAR(30) */
	private String daliyCusNum ;
	
	/** daliyRepeatCusNum : 当日重复消费客户数. DALIY_REPEAT_CUS_NUM: VARCHAR(30) */
	private String daliyRepeatCusNum ;
	
	/** creditDebitRatio : 贷记卡与借记卡交易比. CREDIT_DEBIT_RATIO: VARCHAR(30) */
	private String creditDebitRatio ;
	
	/** remark : 备注. REMARK: VARCHAR(200) */
	private String remark ;
	
	/** recTime : 记录创建时间. REC_TIME: CHAR(14) */
	private String recTime ;
	
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public MhtTransAfterLoanVo() {
		// Default Construtor
	}
	
	public MhtTransAfterLoanVo(Long mchntCode, String transDt) {
		this.mchntCode = mchntCode;
		this.transDt = transDt;
	}
		
	// -- Setter And Getter
	/**
	 * Set mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public void setMchntCode(Long mchntCode){
		this.mchntCode = mchntCode;	
	}
	
	/**
	 * Get mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public Long getMchntCode(){
		return this.mchntCode;	
	}
	
	/**
	 * Set transDt : 交易日期. TRANS_DT: VARCHAR(30) 
	 */
	public void setTransDt(String transDt){
		this.transDt = transDt;	
	}
	
	/**
	 * Get transDt : 交易日期. TRANS_DT: VARCHAR(30) 
	 */
	public String getTransDt(){
		return this.transDt;	
	}
	
	/**
	 * Set daliyTransAt : 当日交易额. DALIY_TRANS_AT: VARCHAR(30) 
	 */
	public void setDaliyTransAt(String daliyTransAt){
		this.daliyTransAt = daliyTransAt;	
	}
	
	/**
	 * Get daliyTransAt : 当日交易额. DALIY_TRANS_AT: VARCHAR(30) 
	 */
	public String getDaliyTransAt(){
		return this.daliyTransAt;	
	}
	
	/**
	 * Set daliyTransNum : 当日交易笔数. DALIY_TRANS_NUM: VARCHAR(30) 
	 */
	public void setDaliyTransNum(String daliyTransNum){
		this.daliyTransNum = daliyTransNum;	
	}
	
	/**
	 * Get daliyTransNum : 当日交易笔数. DALIY_TRANS_NUM: VARCHAR(30) 
	 */
	public String getDaliyTransNum(){
		return this.daliyTransNum;	
	}
	
	/**
	 * Set daliyCusNum : 当日消费客户数. DALIY_CUS_NUM: VARCHAR(30) 
	 */
	public void setDaliyCusNum(String daliyCusNum){
		this.daliyCusNum = daliyCusNum;	
	}
	
	/**
	 * Get daliyCusNum : 当日消费客户数. DALIY_CUS_NUM: VARCHAR(30) 
	 */
	public String getDaliyCusNum(){
		return this.daliyCusNum;	
	}
	
	/**
	 * Set daliyRepeatCusNum : 当日重复消费客户数. DALIY_REPEAT_CUS_NUM: VARCHAR(30) 
	 */
	public void setDaliyRepeatCusNum(String daliyRepeatCusNum){
		this.daliyRepeatCusNum = daliyRepeatCusNum;	
	}
	
	/**
	 * Get daliyRepeatCusNum : 当日重复消费客户数. DALIY_REPEAT_CUS_NUM: VARCHAR(30) 
	 */
	public String getDaliyRepeatCusNum(){
		return this.daliyRepeatCusNum;	
	}
	
	/**
	 * Set creditDebitRatio : 贷记卡与借记卡交易比. CREDIT_DEBIT_RATIO: VARCHAR(30) 
	 */
	public void setCreditDebitRatio(String creditDebitRatio){
		this.creditDebitRatio = creditDebitRatio;	
	}
	
	/**
	 * Get creditDebitRatio : 贷记卡与借记卡交易比. CREDIT_DEBIT_RATIO: VARCHAR(30) 
	 */
	public String getCreditDebitRatio(){
		return this.creditDebitRatio;	
	}
	
	/**
	 * Set remark : 备注. REMARK: VARCHAR(200) 
	 */
	public void setRemark(String remark){
		this.remark = remark;	
	}
	
	/**
	 * Get remark : 备注. REMARK: VARCHAR(200) 
	 */
	public String getRemark(){
		return this.remark;	
	}
	
	/**
	 * Set recTime : 记录创建时间. REC_TIME: CHAR(14) 
	 */
	public void setRecTime(String recTime){
		this.recTime = recTime;	
	}
	
	/**
	 * Get recTime : 记录创建时间. REC_TIME: CHAR(14) 
	 */
	public String getRecTime(){
		return this.recTime;	
	}
	
}