package com.jiuyv.hhc.model.loan ;

// Generated by AutoCode4J
/**
 * EntityBean: 接口通信记录表 : TBL_TXN_TRANS_LOG
 * This is a value object(VO). 
 * Description: 
 * 
 * @author AutoCode4J
 * @version 1.0
 */
public class TxnTransLogVo implements java.io.Serializable {

	/** default Serial Version UID*/
	private static final long serialVersionUID = 1L;
	// -- Fields --
	/** logSeq : 序列号. LOG_SEQ: NUMBER(10) */
	private Long logSeq ;
	
	/** transType : 交易类型. TRANS_TYPE: VARCHAR2(20) */
	private String transType ;
	
	/** transDate : 交易日期. TRANS_DATE: VARCHAR2(8) */
	private String transDate ;
	
	/** transTime : 交易时间. TRANS_TIME: CHAR(14) */
	private String transTime ;
	
	/** mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) */
	private Long mchntCode ;
	
	/** mchntCd : 商户代码. MCHNT_CD: VARCHAR(15) */
	private String mchntCd ;
	
	/** licNo : 营业执照号码. LIC_NO: VARCHAR(70) */
	private String licNo ;
	
	/** artifCertifId : 法人代表证件号. ARTIF_CERTIF_ID: VARCHAR(22) */
	private String artifCertifId ;
	
	/** filePath : 附件路径. FILE_PATH: VARCHAR2(200) */
	private String filePath ;
	
	/** resultCode : 应答码. RESULT_CODE: VARCHAR2(10) */
	private String resultCode ;
	
	/** resultDesc : 应答信息. RESULT_DESC: VARCHAR2(200) */
	private String resultDesc ;
	
	/** oprAcct : 操作账号. OPR_ACCT: VARCHAR2(30) */
	private String oprAcct ;
	
	
	// -- Extended --
	/** transTypeDesc : 交易类型. */
	private String transTypeDesc;
	/** 费用 */
	private Long amount;
	/** 商户名称 */
	private String mchntName ;
	// -- Constructor --
	/**
	 * Constructor
	 * 
	 */
	public TxnTransLogVo() {
		// Default Construtor
	}
	
	public TxnTransLogVo(Long logSeq) {
		this.logSeq = logSeq;
	}
		
	// -- Setter And Getter
	/**
	 * Set logSeq : 序列号. LOG_SEQ: NUMBER(10) 
	 */
	public void setLogSeq(Long logSeq){
		this.logSeq = logSeq;	
	}
	
	/**
	 * Get logSeq : 序列号. LOG_SEQ: NUMBER(10) 
	 */
	public Long getLogSeq(){
		return this.logSeq;	
	}
	
	/**
	 * Set transType : 交易类型. TRANS_TYPE: VARCHAR2(20) 
	 */
	public void setTransType(String transType){
		this.transType = transType;	
	}
	
	/**
	 * Get transType : 交易类型. TRANS_TYPE: VARCHAR2(20) 
	 */
	public String getTransType(){
		return this.transType;	
	}
	
	/**
	 * Set transDate : 交易日期. TRANS_DATE: VARCHAR2(8) 
	 */
	public void setTransDate(String transDate){
		this.transDate = transDate;	
	}
	
	/**
	 * Get transDate : 交易日期. TRANS_DATE: VARCHAR2(8) 
	 */
	public String getTransDate(){
		return this.transDate;	
	}
	
	/**
	 * Set transTime : 交易时间. TRANS_TIME: CHAR(14) 
	 */
	public void setTransTime(String transTime){
		this.transTime = transTime;	
	}
	
	/**
	 * Get transTime : 交易时间. TRANS_TIME: CHAR(14) 
	 */
	public String getTransTime(){
		return this.transTime;	
	}
	
	/**
	 * Set mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public void setMchntCode(Long mchntCode){
		this.mchntCode = mchntCode;	
	}
	
	/**
	 * Get mchntCode : 内部商户号. MCHNT_CODE: NUMBER(10) 
	 */
	public Long getMchntCode(){
		return this.mchntCode;	
	}
	
	/**
	 * Set mchntCd : 商户代码. MCHNT_CD: VARCHAR(15) 
	 */
	public void setMchntCd(String mchntCd){
		this.mchntCd = mchntCd;	
	}
	
	/**
	 * Get mchntCd : 商户代码. MCHNT_CD: VARCHAR(15) 
	 */
	public String getMchntCd(){
		return this.mchntCd;	
	}
	
	/**
	 * Set licNo : 营业执照号码. LIC_NO: VARCHAR(70) 
	 */
	public void setLicNo(String licNo){
		this.licNo = licNo;	
	}
	
	/**
	 * Get licNo : 营业执照号码. LIC_NO: VARCHAR(70) 
	 */
	public String getLicNo(){
		return this.licNo;	
	}
	
	/**
	 * Set artifCertifId : 法人代表证件号. ARTIF_CERTIF_ID: VARCHAR(22) 
	 */
	public void setArtifCertifId(String artifCertifId){
		this.artifCertifId = artifCertifId;	
	}
	
	/**
	 * Get artifCertifId : 法人代表证件号. ARTIF_CERTIF_ID: VARCHAR(22) 
	 */
	public String getArtifCertifId(){
		return this.artifCertifId;	
	}
	
	/**
	 * Set filePath : 附件路径. FILE_PATH: VARCHAR2(200) 
	 */
	public void setFilePath(String filePath){
		this.filePath = filePath;	
	}
	
	/**
	 * Get filePath : 附件路径. FILE_PATH: VARCHAR2(200) 
	 */
	public String getFilePath(){
		return this.filePath;	
	}
	
	/**
	 * Set resultCode : 应答码. RESULT_CODE: VARCHAR2(10) 
	 */
	public void setResultCode(String resultCode){
		this.resultCode = resultCode;	
	}
	
	/**
	 * Get resultCode : 应答码. RESULT_CODE: VARCHAR2(10) 
	 */
	public String getResultCode(){
		return this.resultCode;	
	}
	
	/**
	 * Set resultDesc : 应答信息. RESULT_DESC: VARCHAR2(200) 
	 */
	public void setResultDesc(String resultDesc){
		this.resultDesc = resultDesc;	
	}
	
	/**
	 * Get resultDesc : 应答信息. RESULT_DESC: VARCHAR2(200) 
	 */
	public String getResultDesc(){
		return this.resultDesc;	
	}

	/**
	 * @return the transTypeDesc
	 */
	public String getTransTypeDesc() {
		return transTypeDesc;
	}

	/**
	 * @param transTypeDesc the transTypeDesc to set
	 */
	public void setTransTypeDesc(String transTypeDesc) {
		this.transTypeDesc = transTypeDesc;
	}

	/**
	 * @return the oprAcct
	 */
	public String getOprAcct() {
		return oprAcct;
	}

	/**
	 * @param oprAcct the oprAcct to set
	 */
	public void setOprAcct(String oprAcct) {
		this.oprAcct = oprAcct;
	}

	/**
	 * @return the amount
	 */
	public Long getAmount() {
		return amount;
	}

	/**
	 * @param amount the amount to set
	 */
	public void setAmount(Long amount) {
		this.amount = amount;
	}

	/**
	 * @return the mchntName
	 */
	public String getMchntName() {
		return mchntName;
	}

	/**
	 * @param mchntName the mchntName to set
	 */
	public void setMchntName(String mchntName) {
		this.mchntName = mchntName;
	}
	
}